FROM alpine:latest
RUN apk --no-cache add ca-certificates tzdata libc6-compat
WORKDIR /app
COPY message-consolidator-vps ./chat-analyzer
COPY static ./static
VOLUME ["/data"]
EXPOSE 8080
CMD ["./chat-analyzer"]
