# WhaTap Go Agent Configuration
# https://docs.whatap.io/golang/install-agent#set-whatap-conf

# Access Key (Required)
license=x6060048chncb-z3u8cglfoj7pno-z5ol65j7pa5kiu

# WhaTap Server IP (Required)
whatap.server.host=107.23.220.101/54.236.221.105

# Application Name
app_name=message-consolidator
whatap.okind=jjsong
whatap.onode=GCPVM

# Monitoring Options
profile_sql_param_enabled=true

# Logsink Options (Application Log Collection)
logsink_enabled=true
logsink.files=/app/logs/app.log,/app/logs/ai_inference.log

object_name={type}-{ip2}-{ip3}-{cmd_full}
