// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: achievements_seed.sql

package db

import (
	"context"
)

const deleteAllAchievements = `-- name: DeleteAllAchievements :exec
DELETE FROM achievements
`

func (q *Queries) DeleteAllAchievements(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllAchievements)
	return err
}

const getAchievementsCount = `-- name: GetAchievementsCount :one
SELECT COUNT(*) FROM achievements
`

func (q *Queries) GetAchievementsCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getAchievementsCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const seedAchievements = `-- name: SeedAchievements :exec
INSERT INTO achievements (name, description, icon, criteria_type, criteria_value, target_value, xp_reward) VALUES 
('Morning Star', 'Completed task before 9 AM', 'morning_star', 'early_bird', 1, 1, 50),
('First Step', 'Completed first task', 'task', 'total_tasks', 1, 1, 10),
('Steady Effort', 'Completed 5 tasks', 'task', 'total_tasks', 5, 5, 20),
('Experienced User', 'Completed 10 tasks', 'task', 'total_tasks', 10, 10, 50),
('Level Up', 'Reached level 2', 'level', 'level', 2, 2, 30),
('3 Day Streak', 'Completed tasks for 3 consecutive days', 'streak', 'streak', 3, 3, 20),
('Weekly Passion', 'Completed tasks for 7 consecutive days', 'streak', 'streak', 7, 7, 100),
('Perfectionist', 'Completed 50 tasks', 'task', 'total_tasks', 50, 50, 200),
('Master', 'Completed 100 tasks', 'task', 'total_tasks', 100, 100, 500)
`

func (q *Queries) SeedAchievements(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, seedAchievements)
	return err
}
