// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: add_filtered_count.sql

package db

import (
	"context"
)

const migrateTokenUsageAddFilteredCount = `-- name: MigrateTokenUsageAddFilteredCount :exec
ALTER TABLE token_usage ADD COLUMN filtered_count INTEGER DEFAULT 0
`

func (q *Queries) MigrateTokenUsageAddFilteredCount(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, migrateTokenUsageAddFilteredCount)
	return err
}
