// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ai_inference_logs.sql

package db

import (
	"context"
	"database/sql"
)

const insertAIInferenceLog = `-- name: InsertAIInferenceLog :exec
INSERT INTO ai_inference_logs (message_id, source, original_text, raw_response)
VALUES (?, ?, ?, ?)
`

type InsertAIInferenceLogParams struct {
	MessageID    sql.NullInt64  `json:"message_id"`
	Source       sql.NullString `json:"source"`
	OriginalText sql.NullString `json:"original_text"`
	RawResponse  sql.NullString `json:"raw_response"`
}

func (q *Queries) InsertAIInferenceLog(ctx context.Context, arg InsertAIInferenceLogParams) error {
	_, err := q.db.ExecContext(ctx, insertAIInferenceLog,
		arg.MessageID,
		arg.Source,
		arg.OriginalText,
		arg.RawResponse,
	)
	return err
}
