// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ai_inference_logs.sql

package db

import (
	"context"
	"database/sql"
)

const insertAIInferenceLog = `-- name: InsertAIInferenceLog :exec
INSERT INTO ai_inference_logs (message_id, source)
VALUES (?, ?)
`

type InsertAIInferenceLogParams struct {
	MessageID sql.NullInt64  `json:"message_id"`
	Source    sql.NullString `json:"source"`
}

func (q *Queries) InsertAIInferenceLog(ctx context.Context, arg InsertAIInferenceLogParams) error {
	_, err := q.db.ExecContext(ctx, insertAIInferenceLog, arg.MessageID, arg.Source)
	return err
}
