// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: aliases.sql

package db

import (
	"context"
	"database/sql"
)

const addContactAlias = `-- name: AddContactAlias :exec
INSERT INTO contact_aliases (contact_id, identifier_type, identifier_value, source, trust_level)
VALUES (?, ?, ?, ?, ?)
`

type AddContactAliasParams struct {
	ContactID       int64         `json:"contact_id"`
	IdentifierType  string        `json:"identifier_type"`
	IdentifierValue string        `json:"identifier_value"`
	Source          string        `json:"source"`
	TrustLevel      sql.NullInt64 `json:"trust_level"`
}

func (q *Queries) AddContactAlias(ctx context.Context, arg AddContactAliasParams) error {
	_, err := q.db.ExecContext(ctx, addContactAlias,
		arg.ContactID,
		arg.IdentifierType,
		arg.IdentifierValue,
		arg.Source,
		arg.TrustLevel,
	)
	return err
}

const createUserAlias = `-- name: CreateUserAlias :exec
INSERT INTO user_aliases (user_id, alias_name) 
VALUES (?, ?) 
ON CONFLICT (user_id, alias_name) 
DO NOTHING
`

type CreateUserAliasParams struct {
	UserID    int64  `json:"user_id"`
	AliasName string `json:"alias_name"`
}

func (q *Queries) CreateUserAlias(ctx context.Context, arg CreateUserAliasParams) error {
	_, err := q.db.ExecContext(ctx, createUserAlias, arg.UserID, arg.AliasName)
	return err
}

const deleteTenantAlias = `-- name: DeleteTenantAlias :exec
DELETE FROM tenant_aliases WHERE user_email = ? AND original_name = ?
`

type DeleteTenantAliasParams struct {
	UserEmail    string `json:"user_email"`
	OriginalName string `json:"original_name"`
}

func (q *Queries) DeleteTenantAlias(ctx context.Context, arg DeleteTenantAliasParams) error {
	_, err := q.db.ExecContext(ctx, deleteTenantAlias, arg.UserEmail, arg.OriginalName)
	return err
}

const deleteUserAlias = `-- name: DeleteUserAlias :exec
DELETE FROM user_aliases WHERE user_id = ? AND alias_name = ?
`

type DeleteUserAliasParams struct {
	UserID    int64  `json:"user_id"`
	AliasName string `json:"alias_name"`
}

func (q *Queries) DeleteUserAlias(ctx context.Context, arg DeleteUserAliasParams) error {
	_, err := q.db.ExecContext(ctx, deleteUserAlias, arg.UserID, arg.AliasName)
	return err
}

const getAllTenantAliases = `-- name: GetAllTenantAliases :many
SELECT user_email, original_name, primary_name FROM tenant_aliases
`

type GetAllTenantAliasesRow struct {
	UserEmail    string `json:"user_email"`
	OriginalName string `json:"original_name"`
	PrimaryName  string `json:"primary_name"`
}

func (q *Queries) GetAllTenantAliases(ctx context.Context) ([]GetAllTenantAliasesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllTenantAliases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllTenantAliasesRow
	for rows.Next() {
		var i GetAllTenantAliasesRow
		if err := rows.Scan(&i.UserEmail, &i.OriginalName, &i.PrimaryName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllUserAliases = `-- name: GetAllUserAliases :many
SELECT user_id, alias_name FROM user_aliases
`

type GetAllUserAliasesRow struct {
	UserID    int64  `json:"user_id"`
	AliasName string `json:"alias_name"`
}

func (q *Queries) GetAllUserAliases(ctx context.Context) ([]GetAllUserAliasesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllUserAliases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllUserAliasesRow
	for rows.Next() {
		var i GetAllUserAliasesRow
		if err := rows.Scan(&i.UserID, &i.AliasName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getContactAliases = `-- name: GetContactAliases :many
SELECT contact_id, identifier_type, identifier_value, source, trust_level FROM contact_aliases WHERE contact_id = ?
`

type GetContactAliasesRow struct {
	ContactID       int64         `json:"contact_id"`
	IdentifierType  string        `json:"identifier_type"`
	IdentifierValue string        `json:"identifier_value"`
	Source          string        `json:"source"`
	TrustLevel      sql.NullInt64 `json:"trust_level"`
}

func (q *Queries) GetContactAliases(ctx context.Context, contactID int64) ([]GetContactAliasesRow, error) {
	rows, err := q.db.QueryContext(ctx, getContactAliases, contactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetContactAliasesRow
	for rows.Next() {
		var i GetContactAliasesRow
		if err := rows.Scan(
			&i.ContactID,
			&i.IdentifierType,
			&i.IdentifierValue,
			&i.Source,
			&i.TrustLevel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserAliases = `-- name: GetUserAliases :many
SELECT alias_name FROM user_aliases WHERE user_id = ?
`

func (q *Queries) GetUserAliases(ctx context.Context, userID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getUserAliases, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var alias_name string
		if err := rows.Scan(&alias_name); err != nil {
			return nil, err
		}
		items = append(items, alias_name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTenantAlias = `-- name: UpsertTenantAlias :exec
INSERT INTO tenant_aliases (user_email, original_name, primary_name) 
VALUES (?, ?, ?) 
ON CONFLICT (user_email, original_name) 
DO UPDATE SET primary_name = EXCLUDED.primary_name
`

type UpsertTenantAliasParams struct {
	UserEmail    string `json:"user_email"`
	OriginalName string `json:"original_name"`
	PrimaryName  string `json:"primary_name"`
}

func (q *Queries) UpsertTenantAlias(ctx context.Context, arg UpsertTenantAliasParams) error {
	_, err := q.db.ExecContext(ctx, upsertTenantAlias, arg.UserEmail, arg.OriginalName, arg.PrimaryName)
	return err
}
