// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: app_settings.sql

package db

import (
	"context"
)

const deleteAppSetting = `-- name: DeleteAppSetting :exec
DELETE FROM app_settings WHERE key = ?1
`

func (q *Queries) DeleteAppSetting(ctx context.Context, key string) error {
	_, err := q.db.ExecContext(ctx, deleteAppSetting, key)
	return err
}

const getAppSetting = `-- name: GetAppSetting :one
SELECT key, value, updated_at, updated_by FROM app_settings WHERE key = ?1
`

func (q *Queries) GetAppSetting(ctx context.Context, key string) (AppSetting, error) {
	row := q.db.QueryRowContext(ctx, getAppSetting, key)
	var i AppSetting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const listAppSettings = `-- name: ListAppSettings :many
SELECT key, value, updated_at, updated_by FROM app_settings
`

func (q *Queries) ListAppSettings(ctx context.Context) ([]AppSetting, error) {
	rows, err := q.db.QueryContext(ctx, listAppSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppSetting
	for rows.Next() {
		var i AppSetting
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAppSetting = `-- name: UpsertAppSetting :exec
INSERT INTO app_settings (key, value, updated_by, updated_at)
VALUES (?1, ?2, ?3, CURRENT_TIMESTAMP)
ON CONFLICT(key) DO UPDATE SET
    value = EXCLUDED.value,
    updated_by = EXCLUDED.updated_by,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertAppSettingParams struct {
	Key       string `json:"key"`
	Value     string `json:"value"`
	UpdatedBy string `json:"updated_by"`
}

func (q *Queries) UpsertAppSetting(ctx context.Context, arg UpsertAppSettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertAppSetting, arg.Key, arg.Value, arg.UpdatedBy)
	return err
}
