// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contacts.sql

package db

import (
	"context"
	"database/sql"
)

const deleteContactMapping = `-- name: DeleteContactMapping :exec
DELETE FROM contacts
WHERE tenant_email = ? AND canonical_id = ?
`

type DeleteContactMappingParams struct {
	TenantEmail string `json:"tenant_email"`
	CanonicalID string `json:"canonical_id"`
}

func (q *Queries) DeleteContactMapping(ctx context.Context, arg DeleteContactMappingParams) error {
	_, err := q.db.ExecContext(ctx, deleteContactMapping, arg.TenantEmail, arg.CanonicalID)
	return err
}

const flattenChildren = `-- name: FlattenChildren :exec
UPDATE contacts
SET master_contact_id = ?
WHERE tenant_email = ? AND master_contact_id = ?
`

type FlattenChildrenParams struct {
	MasterContactID   sql.NullInt64 `json:"master_contact_id"`
	TenantEmail       string        `json:"tenant_email"`
	MasterContactID_2 sql.NullInt64 `json:"master_contact_id_2"`
}

func (q *Queries) FlattenChildren(ctx context.Context, arg FlattenChildrenParams) error {
	_, err := q.db.ExecContext(ctx, flattenChildren, arg.MasterContactID, arg.TenantEmail, arg.MasterContactID_2)
	return err
}

const getContactByIdentifier = `-- name: GetContactByIdentifier :many
SELECT id, tenant_email, canonical_id, display_name, source, master_contact_id, contact_type
FROM contacts 
WHERE tenant_email = ? 
AND (canonical_id = ? OR display_name = ?)
`

type GetContactByIdentifierParams struct {
	TenantEmail string `json:"tenant_email"`
	CanonicalID string `json:"canonical_id"`
	DisplayName string `json:"display_name"`
}

type GetContactByIdentifierRow struct {
	ID              int64          `json:"id"`
	TenantEmail     string         `json:"tenant_email"`
	CanonicalID     string         `json:"canonical_id"`
	DisplayName     string         `json:"display_name"`
	Source          sql.NullString `json:"source"`
	MasterContactID sql.NullInt64  `json:"master_contact_id"`
	ContactType     sql.NullString `json:"contact_type"`
}

func (q *Queries) GetContactByIdentifier(ctx context.Context, arg GetContactByIdentifierParams) ([]GetContactByIdentifierRow, error) {
	rows, err := q.db.QueryContext(ctx, getContactByIdentifier, arg.TenantEmail, arg.CanonicalID, arg.DisplayName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetContactByIdentifierRow
	for rows.Next() {
		var i GetContactByIdentifierRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantEmail,
			&i.CanonicalID,
			&i.DisplayName,
			&i.Source,
			&i.MasterContactID,
			&i.ContactType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getContactTypeDistribution = `-- name: GetContactTypeDistribution :many
SELECT contact_type, COUNT(*) as count
FROM contacts
WHERE tenant_email = ?
GROUP BY contact_type
`

type GetContactTypeDistributionRow struct {
	ContactType sql.NullString `json:"contact_type"`
	Count       int64          `json:"count"`
}

func (q *Queries) GetContactTypeDistribution(ctx context.Context, tenantEmail string) ([]GetContactTypeDistributionRow, error) {
	rows, err := q.db.QueryContext(ctx, getContactTypeDistribution, tenantEmail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetContactTypeDistributionRow
	for rows.Next() {
		var i GetContactTypeDistributionRow
		if err := rows.Scan(&i.ContactType, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLinkedContacts = `-- name: GetLinkedContacts :many
SELECT id, tenant_email, canonical_id, display_name, source, master_contact_id, contact_type
FROM contacts
WHERE tenant_email = ? AND master_contact_id IS NOT NULL
`

type GetLinkedContactsRow struct {
	ID              int64          `json:"id"`
	TenantEmail     string         `json:"tenant_email"`
	CanonicalID     string         `json:"canonical_id"`
	DisplayName     string         `json:"display_name"`
	Source          sql.NullString `json:"source"`
	MasterContactID sql.NullInt64  `json:"master_contact_id"`
	ContactType     sql.NullString `json:"contact_type"`
}

func (q *Queries) GetLinkedContacts(ctx context.Context, tenantEmail string) ([]GetLinkedContactsRow, error) {
	rows, err := q.db.QueryContext(ctx, getLinkedContacts, tenantEmail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLinkedContactsRow
	for rows.Next() {
		var i GetLinkedContactsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantEmail,
			&i.CanonicalID,
			&i.DisplayName,
			&i.Source,
			&i.MasterContactID,
			&i.ContactType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadContactsAll = `-- name: LoadContactsAll :many
SELECT tenant_email, canonical_id, display_name, source, contact_type FROM contacts
`

type LoadContactsAllRow struct {
	TenantEmail string         `json:"tenant_email"`
	CanonicalID string         `json:"canonical_id"`
	DisplayName string         `json:"display_name"`
	Source      sql.NullString `json:"source"`
	ContactType sql.NullString `json:"contact_type"`
}

func (q *Queries) LoadContactsAll(ctx context.Context) ([]LoadContactsAllRow, error) {
	rows, err := q.db.QueryContext(ctx, loadContactsAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoadContactsAllRow
	for rows.Next() {
		var i LoadContactsAllRow
		if err := rows.Scan(
			&i.TenantEmail,
			&i.CanonicalID,
			&i.DisplayName,
			&i.Source,
			&i.ContactType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchContacts = `-- name: SearchContacts :many
SELECT id, tenant_email, canonical_id, display_name, source, master_contact_id, contact_type
FROM contacts
WHERE tenant_email = ?
AND (display_name LIKE '%' || ? || '%' 
     OR canonical_id LIKE '%' || ? || '%')
LIMIT 20
`

type SearchContactsParams struct {
	TenantEmail string         `json:"tenant_email"`
	Column2     sql.NullString `json:"column_2"`
	Column3     sql.NullString `json:"column_3"`
}

type SearchContactsRow struct {
	ID              int64          `json:"id"`
	TenantEmail     string         `json:"tenant_email"`
	CanonicalID     string         `json:"canonical_id"`
	DisplayName     string         `json:"display_name"`
	Source          sql.NullString `json:"source"`
	MasterContactID sql.NullInt64  `json:"master_contact_id"`
	ContactType     sql.NullString `json:"contact_type"`
}

func (q *Queries) SearchContacts(ctx context.Context, arg SearchContactsParams) ([]SearchContactsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchContacts, arg.TenantEmail, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchContactsRow
	for rows.Next() {
		var i SearchContactsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantEmail,
			&i.CanonicalID,
			&i.DisplayName,
			&i.Source,
			&i.MasterContactID,
			&i.ContactType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unlinkContact = `-- name: UnlinkContact :exec
UPDATE contacts
SET master_contact_id = NULL
WHERE tenant_email = ? AND id = ?
`

type UnlinkContactParams struct {
	TenantEmail string `json:"tenant_email"`
	ID          int64  `json:"id"`
}

func (q *Queries) UnlinkContact(ctx context.Context, arg UnlinkContactParams) error {
	_, err := q.db.ExecContext(ctx, unlinkContact, arg.TenantEmail, arg.ID)
	return err
}

const updateContactLink = `-- name: UpdateContactLink :exec
UPDATE contacts
SET master_contact_id = ?
WHERE tenant_email = ? AND id = ?
`

type UpdateContactLinkParams struct {
	MasterContactID sql.NullInt64 `json:"master_contact_id"`
	TenantEmail     string        `json:"tenant_email"`
	ID              int64         `json:"id"`
}

func (q *Queries) UpdateContactLink(ctx context.Context, arg UpdateContactLinkParams) error {
	_, err := q.db.ExecContext(ctx, updateContactLink, arg.MasterContactID, arg.TenantEmail, arg.ID)
	return err
}

const updateContactType = `-- name: UpdateContactType :exec
UPDATE contacts
SET contact_type = ?
WHERE id = ?
`

type UpdateContactTypeParams struct {
	ContactType sql.NullString `json:"contact_type"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdateContactType(ctx context.Context, arg UpdateContactTypeParams) error {
	_, err := q.db.ExecContext(ctx, updateContactType, arg.ContactType, arg.ID)
	return err
}

const upsertContactMapping = `-- name: UpsertContactMapping :one
INSERT INTO contacts (tenant_email, canonical_id, display_name, source)
VALUES (?, ?, ?, ?)
ON CONFLICT(tenant_email, canonical_id) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    source = EXCLUDED.source
RETURNING id
`

type UpsertContactMappingParams struct {
	TenantEmail string         `json:"tenant_email"`
	CanonicalID string         `json:"canonical_id"`
	DisplayName string         `json:"display_name"`
	Source      sql.NullString `json:"source"`
}

func (q *Queries) UpsertContactMapping(ctx context.Context, arg UpsertContactMappingParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertContactMapping,
		arg.TenantEmail,
		arg.CanonicalID,
		arg.DisplayName,
		arg.Source,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertContactMappingSimple = `-- name: UpsertContactMappingSimple :one
INSERT INTO contacts (tenant_email, canonical_id, display_name, source)
VALUES (?, ?, ?, ?)
ON CONFLICT(tenant_email, canonical_id) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    source = EXCLUDED.source
RETURNING id
`

type UpsertContactMappingSimpleParams struct {
	TenantEmail string         `json:"tenant_email"`
	CanonicalID string         `json:"canonical_id"`
	DisplayName string         `json:"display_name"`
	Source      sql.NullString `json:"source"`
}

func (q *Queries) UpsertContactMappingSimple(ctx context.Context, arg UpsertContactMappingSimpleParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertContactMappingSimple,
		arg.TenantEmail,
		arg.CanonicalID,
		arg.DisplayName,
		arg.Source,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
