// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contacts.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const deleteContactMapping = `-- name: DeleteContactMapping :exec
DELETE FROM contacts
WHERE tenant_email = ? AND canonical_id = ?
`

type DeleteContactMappingParams struct {
	TenantEmail string `json:"tenant_email"`
	CanonicalID string `json:"canonical_id"`
}

func (q *Queries) DeleteContactMapping(ctx context.Context, arg DeleteContactMappingParams) error {
	_, err := q.db.ExecContext(ctx, deleteContactMapping, arg.TenantEmail, arg.CanonicalID)
	return err
}

const getAliasesByValues = `-- name: GetAliasesByValues :many
SELECT identifier_value, contact_id FROM contact_aliases WHERE identifier_value IN (/*SLICE:values*/?)
`

type GetAliasesByValuesRow struct {
	IdentifierValue string `json:"identifier_value"`
	ContactID       int64  `json:"contact_id"`
}

func (q *Queries) GetAliasesByValues(ctx context.Context, values []string) ([]GetAliasesByValuesRow, error) {
	query := getAliasesByValues
	var queryParams []interface{}
	if len(values) > 0 {
		for _, v := range values {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:values*/?", strings.Repeat(",?", len(values))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:values*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAliasesByValuesRow
	for rows.Next() {
		var i GetAliasesByValuesRow
		if err := rows.Scan(&i.IdentifierValue, &i.ContactID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getContactByID = `-- name: GetContactByID :one
SELECT id, tenant_email, canonical_id, display_name, source, master_contact_id, contact_type FROM contacts WHERE tenant_email = ? AND id = ?
`

type GetContactByIDParams struct {
	TenantEmail string `json:"tenant_email"`
	ID          int64  `json:"id"`
}

type GetContactByIDRow struct {
	ID              int64          `json:"id"`
	TenantEmail     string         `json:"tenant_email"`
	CanonicalID     string         `json:"canonical_id"`
	DisplayName     string         `json:"display_name"`
	Source          sql.NullString `json:"source"`
	MasterContactID sql.NullInt64  `json:"master_contact_id"`
	ContactType     sql.NullString `json:"contact_type"`
}

func (q *Queries) GetContactByID(ctx context.Context, arg GetContactByIDParams) (GetContactByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getContactByID, arg.TenantEmail, arg.ID)
	var i GetContactByIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantEmail,
		&i.CanonicalID,
		&i.DisplayName,
		&i.Source,
		&i.MasterContactID,
		&i.ContactType,
	)
	return i, err
}

const getContactByIdentifier = `-- name: GetContactByIdentifier :many
SELECT id, tenant_email, canonical_id, display_name, source, master_contact_id, contact_type
FROM contacts 
WHERE tenant_email = ? 
AND (canonical_id = ? OR display_name = ?)
`

type GetContactByIdentifierParams struct {
	TenantEmail string `json:"tenant_email"`
	CanonicalID string `json:"canonical_id"`
	DisplayName string `json:"display_name"`
}

type GetContactByIdentifierRow struct {
	ID              int64          `json:"id"`
	TenantEmail     string         `json:"tenant_email"`
	CanonicalID     string         `json:"canonical_id"`
	DisplayName     string         `json:"display_name"`
	Source          sql.NullString `json:"source"`
	MasterContactID sql.NullInt64  `json:"master_contact_id"`
	ContactType     sql.NullString `json:"contact_type"`
}

func (q *Queries) GetContactByIdentifier(ctx context.Context, arg GetContactByIdentifierParams) ([]GetContactByIdentifierRow, error) {
	rows, err := q.db.QueryContext(ctx, getContactByIdentifier, arg.TenantEmail, arg.CanonicalID, arg.DisplayName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetContactByIdentifierRow
	for rows.Next() {
		var i GetContactByIdentifierRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantEmail,
			&i.CanonicalID,
			&i.DisplayName,
			&i.Source,
			&i.MasterContactID,
			&i.ContactType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getContactsByTenant = `-- name: GetContactsByTenant :many
SELECT id, tenant_email, canonical_id, display_name, source, master_contact_id, contact_type FROM contacts WHERE tenant_email = ?
`

type GetContactsByTenantRow struct {
	ID              int64          `json:"id"`
	TenantEmail     string         `json:"tenant_email"`
	CanonicalID     string         `json:"canonical_id"`
	DisplayName     string         `json:"display_name"`
	Source          sql.NullString `json:"source"`
	MasterContactID sql.NullInt64  `json:"master_contact_id"`
	ContactType     sql.NullString `json:"contact_type"`
}

func (q *Queries) GetContactsByTenant(ctx context.Context, tenantEmail string) ([]GetContactsByTenantRow, error) {
	rows, err := q.db.QueryContext(ctx, getContactsByTenant, tenantEmail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetContactsByTenantRow
	for rows.Next() {
		var i GetContactsByTenantRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantEmail,
			&i.CanonicalID,
			&i.DisplayName,
			&i.Source,
			&i.MasterContactID,
			&i.ContactType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getContactsWithMaster = `-- name: GetContactsWithMaster :many
SELECT id, master_contact_id FROM contacts WHERE master_contact_id IS NOT NULL
`

type GetContactsWithMasterRow struct {
	ID              int64         `json:"id"`
	MasterContactID sql.NullInt64 `json:"master_contact_id"`
}

func (q *Queries) GetContactsWithMaster(ctx context.Context) ([]GetContactsWithMasterRow, error) {
	rows, err := q.db.QueryContext(ctx, getContactsWithMaster)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetContactsWithMasterRow
	for rows.Next() {
		var i GetContactsWithMasterRow
		if err := rows.Scan(&i.ID, &i.MasterContactID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLinkedContacts = `-- name: GetLinkedContacts :many
SELECT id, tenant_email, canonical_id, display_name, source, master_contact_id, contact_type
FROM contacts
WHERE tenant_email = ? AND master_contact_id IS NOT NULL
`

type GetLinkedContactsRow struct {
	ID              int64          `json:"id"`
	TenantEmail     string         `json:"tenant_email"`
	CanonicalID     string         `json:"canonical_id"`
	DisplayName     string         `json:"display_name"`
	Source          sql.NullString `json:"source"`
	MasterContactID sql.NullInt64  `json:"master_contact_id"`
	ContactType     sql.NullString `json:"contact_type"`
}

func (q *Queries) GetLinkedContacts(ctx context.Context, tenantEmail string) ([]GetLinkedContactsRow, error) {
	rows, err := q.db.QueryContext(ctx, getLinkedContacts, tenantEmail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLinkedContactsRow
	for rows.Next() {
		var i GetLinkedContactsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantEmail,
			&i.CanonicalID,
			&i.DisplayName,
			&i.Source,
			&i.MasterContactID,
			&i.ContactType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMergeHistory = `-- name: InsertMergeHistory :exec
INSERT INTO identity_merge_history (source_contact_id, target_contact_id, reason)
VALUES (?, ?, ?)
`

type InsertMergeHistoryParams struct {
	SourceContactID int64  `json:"source_contact_id"`
	TargetContactID int64  `json:"target_contact_id"`
	Reason          string `json:"reason"`
}

func (q *Queries) InsertMergeHistory(ctx context.Context, arg InsertMergeHistoryParams) error {
	_, err := q.db.ExecContext(ctx, insertMergeHistory, arg.SourceContactID, arg.TargetContactID, arg.Reason)
	return err
}

const loadContactsAll = `-- name: LoadContactsAll :many
SELECT tenant_email, canonical_id, display_name, source, contact_type FROM contacts
`

type LoadContactsAllRow struct {
	TenantEmail string         `json:"tenant_email"`
	CanonicalID string         `json:"canonical_id"`
	DisplayName string         `json:"display_name"`
	Source      sql.NullString `json:"source"`
	ContactType sql.NullString `json:"contact_type"`
}

func (q *Queries) LoadContactsAll(ctx context.Context) ([]LoadContactsAllRow, error) {
	rows, err := q.db.QueryContext(ctx, loadContactsAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoadContactsAllRow
	for rows.Next() {
		var i LoadContactsAllRow
		if err := rows.Scan(
			&i.TenantEmail,
			&i.CanonicalID,
			&i.DisplayName,
			&i.Source,
			&i.ContactType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchContacts = `-- name: SearchContacts :many
SELECT id, tenant_email, canonical_id, display_name, source, master_contact_id, contact_type
FROM contacts
WHERE tenant_email = ?
AND (display_name LIKE '%' || ? || '%' 
     OR canonical_id LIKE '%' || ? || '%')
LIMIT 20
`

type SearchContactsParams struct {
	TenantEmail string         `json:"tenant_email"`
	Column2     sql.NullString `json:"column_2"`
	Column3     sql.NullString `json:"column_3"`
}

type SearchContactsRow struct {
	ID              int64          `json:"id"`
	TenantEmail     string         `json:"tenant_email"`
	CanonicalID     string         `json:"canonical_id"`
	DisplayName     string         `json:"display_name"`
	Source          sql.NullString `json:"source"`
	MasterContactID sql.NullInt64  `json:"master_contact_id"`
	ContactType     sql.NullString `json:"contact_type"`
}

func (q *Queries) SearchContacts(ctx context.Context, arg SearchContactsParams) ([]SearchContactsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchContacts, arg.TenantEmail, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchContactsRow
	for rows.Next() {
		var i SearchContactsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantEmail,
			&i.CanonicalID,
			&i.DisplayName,
			&i.Source,
			&i.MasterContactID,
			&i.ContactType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContactDetails = `-- name: UpdateContactDetails :exec
UPDATE contacts
SET
    display_name = COALESCE(?3, display_name),
    source = COALESCE(?4, source),
    master_contact_id = ?5,
    contact_type = COALESCE(?6, contact_type)
WHERE tenant_email = ?1 AND id = ?2
`

type UpdateContactDetailsParams struct {
	TenantEmail     string         `json:"tenant_email"`
	ID              int64          `json:"id"`
	DisplayName     sql.NullString `json:"display_name"`
	Source          sql.NullString `json:"source"`
	MasterContactID sql.NullInt64  `json:"master_contact_id"`
	ContactType     sql.NullString `json:"contact_type"`
}

func (q *Queries) UpdateContactDetails(ctx context.Context, arg UpdateContactDetailsParams) error {
	_, err := q.db.ExecContext(ctx, updateContactDetails,
		arg.TenantEmail,
		arg.ID,
		arg.DisplayName,
		arg.Source,
		arg.MasterContactID,
		arg.ContactType,
	)
	return err
}

const upsertContactMapping = `-- name: UpsertContactMapping :one
INSERT INTO contacts (tenant_email, canonical_id, display_name, source)
VALUES (?, ?, ?, ?)
ON CONFLICT(tenant_email, canonical_id) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    source = EXCLUDED.source
RETURNING id
`

type UpsertContactMappingParams struct {
	TenantEmail string         `json:"tenant_email"`
	CanonicalID string         `json:"canonical_id"`
	DisplayName string         `json:"display_name"`
	Source      sql.NullString `json:"source"`
}

func (q *Queries) UpsertContactMapping(ctx context.Context, arg UpsertContactMappingParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertContactMapping,
		arg.TenantEmail,
		arg.CanonicalID,
		arg.DisplayName,
		arg.Source,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
