// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contacts.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const appendSecondaryID = `-- name: AppendSecondaryID :exec
UPDATE contacts
SET secondary_ids = json_insert(COALESCE(secondary_ids, '[]'), '$[#]', ?1)
WHERE id = ?2
`

type AppendSecondaryIDParams struct {
	JsonInsert interface{} `json:"json_insert"`
	ID         int64       `json:"id"`
}

func (q *Queries) AppendSecondaryID(ctx context.Context, arg AppendSecondaryIDParams) error {
	_, err := q.db.ExecContext(ctx, appendSecondaryID, arg.JsonInsert, arg.ID)
	return err
}

const deleteContactMapping = `-- name: DeleteContactMapping :exec
DELETE FROM contacts
WHERE tenant_email = ? AND canonical_id = ?
`

type DeleteContactMappingParams struct {
	TenantEmail string `json:"tenant_email"`
	CanonicalID string `json:"canonical_id"`
}

func (q *Queries) DeleteContactMapping(ctx context.Context, arg DeleteContactMappingParams) error {
	_, err := q.db.ExecContext(ctx, deleteContactMapping, arg.TenantEmail, arg.CanonicalID)
	return err
}

const flattenContactChildren = `-- name: FlattenContactChildren :exec
UPDATE contacts SET master_contact_id = ?1 WHERE master_contact_id = ?2 AND tenant_email = ?3
`

type FlattenContactChildrenParams struct {
	MasterContactID   sql.NullInt64 `json:"master_contact_id"`
	MasterContactID_2 sql.NullInt64 `json:"master_contact_id_2"`
	TenantEmail       string        `json:"tenant_email"`
}

func (q *Queries) FlattenContactChildren(ctx context.Context, arg FlattenContactChildrenParams) error {
	_, err := q.db.ExecContext(ctx, flattenContactChildren, arg.MasterContactID, arg.MasterContactID_2, arg.TenantEmail)
	return err
}

const getContactByID = `-- name: GetContactByID :one
SELECT id, tenant_email, canonical_id, display_name, source, master_contact_id, contact_type, secondary_ids FROM contacts WHERE tenant_email = ? AND id = ?
`

type GetContactByIDParams struct {
	TenantEmail string `json:"tenant_email"`
	ID          int64  `json:"id"`
}

type GetContactByIDRow struct {
	ID              int64          `json:"id"`
	TenantEmail     string         `json:"tenant_email"`
	CanonicalID     string         `json:"canonical_id"`
	DisplayName     string         `json:"display_name"`
	Source          sql.NullString `json:"source"`
	MasterContactID sql.NullInt64  `json:"master_contact_id"`
	ContactType     sql.NullString `json:"contact_type"`
	SecondaryIds    sql.NullString `json:"secondary_ids"`
}

func (q *Queries) GetContactByID(ctx context.Context, arg GetContactByIDParams) (GetContactByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getContactByID, arg.TenantEmail, arg.ID)
	var i GetContactByIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantEmail,
		&i.CanonicalID,
		&i.DisplayName,
		&i.Source,
		&i.MasterContactID,
		&i.ContactType,
		&i.SecondaryIds,
	)
	return i, err
}

const getContactTypeByID = `-- name: GetContactTypeByID :one
SELECT contact_type FROM contacts WHERE id = ?1 AND tenant_email = ?2
`

type GetContactTypeByIDParams struct {
	ID          int64  `json:"id"`
	TenantEmail string `json:"tenant_email"`
}

func (q *Queries) GetContactTypeByID(ctx context.Context, arg GetContactTypeByIDParams) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getContactTypeByID, arg.ID, arg.TenantEmail)
	var contact_type sql.NullString
	err := row.Scan(&contact_type)
	return contact_type, err
}

const getContactsByIDs = `-- name: GetContactsByIDs :many
SELECT id, tenant_email, canonical_id, display_name, source, master_contact_id, contact_type, secondary_ids
FROM contacts WHERE id IN (/*SLICE:ids*/?)
`

type GetContactsByIDsRow struct {
	ID              int64          `json:"id"`
	TenantEmail     string         `json:"tenant_email"`
	CanonicalID     string         `json:"canonical_id"`
	DisplayName     string         `json:"display_name"`
	Source          sql.NullString `json:"source"`
	MasterContactID sql.NullInt64  `json:"master_contact_id"`
	ContactType     sql.NullString `json:"contact_type"`
	SecondaryIds    sql.NullString `json:"secondary_ids"`
}

func (q *Queries) GetContactsByIDs(ctx context.Context, ids []int64) ([]GetContactsByIDsRow, error) {
	query := getContactsByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetContactsByIDsRow
	for rows.Next() {
		var i GetContactsByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantEmail,
			&i.CanonicalID,
			&i.DisplayName,
			&i.Source,
			&i.MasterContactID,
			&i.ContactType,
			&i.SecondaryIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getContactsByTenant = `-- name: GetContactsByTenant :many
SELECT id, tenant_email, canonical_id, display_name, source, master_contact_id, contact_type, secondary_ids FROM contacts WHERE tenant_email = ?
`

type GetContactsByTenantRow struct {
	ID              int64          `json:"id"`
	TenantEmail     string         `json:"tenant_email"`
	CanonicalID     string         `json:"canonical_id"`
	DisplayName     string         `json:"display_name"`
	Source          sql.NullString `json:"source"`
	MasterContactID sql.NullInt64  `json:"master_contact_id"`
	ContactType     sql.NullString `json:"contact_type"`
	SecondaryIds    sql.NullString `json:"secondary_ids"`
}

func (q *Queries) GetContactsByTenant(ctx context.Context, tenantEmail string) ([]GetContactsByTenantRow, error) {
	rows, err := q.db.QueryContext(ctx, getContactsByTenant, tenantEmail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetContactsByTenantRow
	for rows.Next() {
		var i GetContactsByTenantRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantEmail,
			&i.CanonicalID,
			&i.DisplayName,
			&i.Source,
			&i.MasterContactID,
			&i.ContactType,
			&i.SecondaryIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getContactsByValues = `-- name: GetContactsByValues :many
SELECT id, canonical_id, display_name, secondary_ids FROM contacts
WHERE LOWER(canonical_id) IN (/*SLICE:values*/?)
   OR LOWER(display_name) IN (/*SLICE:values*/?)
   OR EXISTS (SELECT 1 FROM json_each(secondary_ids) WHERE LOWER(value) IN (/*SLICE:values*/?))
`

type GetContactsByValuesRow struct {
	ID           int64          `json:"id"`
	CanonicalID  string         `json:"canonical_id"`
	DisplayName  string         `json:"display_name"`
	SecondaryIds sql.NullString `json:"secondary_ids"`
}

func (q *Queries) GetContactsByValues(ctx context.Context) ([]GetContactsByValuesRow, error) {
	rows, err := q.db.QueryContext(ctx, getContactsByValues)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetContactsByValuesRow
	for rows.Next() {
		var i GetContactsByValuesRow
		if err := rows.Scan(
			&i.ID,
			&i.CanonicalID,
			&i.DisplayName,
			&i.SecondaryIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getContactsWithMaster = `-- name: GetContactsWithMaster :many
SELECT id, master_contact_id FROM contacts WHERE master_contact_id IS NOT NULL
`

type GetContactsWithMasterRow struct {
	ID              int64         `json:"id"`
	MasterContactID sql.NullInt64 `json:"master_contact_id"`
}

func (q *Queries) GetContactsWithMaster(ctx context.Context) ([]GetContactsWithMasterRow, error) {
	rows, err := q.db.QueryContext(ctx, getContactsWithMaster)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetContactsWithMasterRow
	for rows.Next() {
		var i GetContactsWithMasterRow
		if err := rows.Scan(&i.ID, &i.MasterContactID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDisplayNameByID = `-- name: GetDisplayNameByID :one
SELECT display_name FROM contacts WHERE id = ?
`

func (q *Queries) GetDisplayNameByID(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getDisplayNameByID, id)
	var display_name string
	err := row.Scan(&display_name)
	return display_name, err
}

const getLinkedContacts = `-- name: GetLinkedContacts :many
SELECT id, tenant_email, canonical_id, display_name, source, master_contact_id, contact_type
FROM contacts
WHERE tenant_email = ? AND master_contact_id IS NOT NULL
`

type GetLinkedContactsRow struct {
	ID              int64          `json:"id"`
	TenantEmail     string         `json:"tenant_email"`
	CanonicalID     string         `json:"canonical_id"`
	DisplayName     string         `json:"display_name"`
	Source          sql.NullString `json:"source"`
	MasterContactID sql.NullInt64  `json:"master_contact_id"`
	ContactType     sql.NullString `json:"contact_type"`
}

func (q *Queries) GetLinkedContacts(ctx context.Context, tenantEmail string) ([]GetLinkedContactsRow, error) {
	rows, err := q.db.QueryContext(ctx, getLinkedContacts, tenantEmail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLinkedContactsRow
	for rows.Next() {
		var i GetLinkedContactsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantEmail,
			&i.CanonicalID,
			&i.DisplayName,
			&i.Source,
			&i.MasterContactID,
			&i.ContactType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMasterAndTypeByID = `-- name: GetMasterAndTypeByID :one
SELECT master_contact_id, contact_type FROM contacts WHERE id = ?1 AND tenant_email = ?2
`

type GetMasterAndTypeByIDParams struct {
	ID          int64  `json:"id"`
	TenantEmail string `json:"tenant_email"`
}

type GetMasterAndTypeByIDRow struct {
	MasterContactID sql.NullInt64  `json:"master_contact_id"`
	ContactType     sql.NullString `json:"contact_type"`
}

func (q *Queries) GetMasterAndTypeByID(ctx context.Context, arg GetMasterAndTypeByIDParams) (GetMasterAndTypeByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getMasterAndTypeByID, arg.ID, arg.TenantEmail)
	var i GetMasterAndTypeByIDRow
	err := row.Scan(&i.MasterContactID, &i.ContactType)
	return i, err
}

const getResolutionsByIdentifiers = `-- name: GetResolutionsByIdentifiers :many
SELECT raw_identifier, contact_id FROM contact_resolution
WHERE tenant_email = ? AND raw_identifier IN (/*SLICE:identifiers*/?)
`

type GetResolutionsByIdentifiersParams struct {
	TenantEmail string   `json:"tenant_email"`
	Identifiers []string `json:"identifiers"`
}

type GetResolutionsByIdentifiersRow struct {
	RawIdentifier string `json:"raw_identifier"`
	ContactID     int64  `json:"contact_id"`
}

func (q *Queries) GetResolutionsByIdentifiers(ctx context.Context, arg GetResolutionsByIdentifiersParams) ([]GetResolutionsByIdentifiersRow, error) {
	query := getResolutionsByIdentifiers
	var queryParams []interface{}
	queryParams = append(queryParams, arg.TenantEmail)
	if len(arg.Identifiers) > 0 {
		for _, v := range arg.Identifiers {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:identifiers*/?", strings.Repeat(",?", len(arg.Identifiers))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:identifiers*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetResolutionsByIdentifiersRow
	for rows.Next() {
		var i GetResolutionsByIdentifiersRow
		if err := rows.Scan(&i.RawIdentifier, &i.ContactID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTenantEmailByContactID = `-- name: GetTenantEmailByContactID :one
SELECT tenant_email FROM contacts WHERE id = ?
`

func (q *Queries) GetTenantEmailByContactID(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getTenantEmailByContactID, id)
	var tenant_email string
	err := row.Scan(&tenant_email)
	return tenant_email, err
}

const insertMergeHistory = `-- name: InsertMergeHistory :exec
INSERT INTO identity_merge_history (source_contact_id, target_contact_id, reason)
VALUES (?, ?, ?)
`

type InsertMergeHistoryParams struct {
	SourceContactID int64  `json:"source_contact_id"`
	TargetContactID int64  `json:"target_contact_id"`
	Reason          string `json:"reason"`
}

func (q *Queries) InsertMergeHistory(ctx context.Context, arg InsertMergeHistoryParams) error {
	_, err := q.db.ExecContext(ctx, insertMergeHistory, arg.SourceContactID, arg.TargetContactID, arg.Reason)
	return err
}

const loadContactsAll = `-- name: LoadContactsAll :many
SELECT tenant_email, canonical_id, display_name, source, contact_type FROM contacts
`

type LoadContactsAllRow struct {
	TenantEmail string         `json:"tenant_email"`
	CanonicalID string         `json:"canonical_id"`
	DisplayName string         `json:"display_name"`
	Source      sql.NullString `json:"source"`
	ContactType sql.NullString `json:"contact_type"`
}

func (q *Queries) LoadContactsAll(ctx context.Context) ([]LoadContactsAllRow, error) {
	rows, err := q.db.QueryContext(ctx, loadContactsAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoadContactsAllRow
	for rows.Next() {
		var i LoadContactsAllRow
		if err := rows.Scan(
			&i.TenantEmail,
			&i.CanonicalID,
			&i.DisplayName,
			&i.Source,
			&i.ContactType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchContacts = `-- name: SearchContacts :many
SELECT id, tenant_email, canonical_id, display_name, source, master_contact_id, contact_type
FROM contacts
WHERE tenant_email = ?
AND (display_name LIKE '%' || ? || '%' 
     OR canonical_id LIKE '%' || ? || '%')
LIMIT 20
`

type SearchContactsParams struct {
	TenantEmail string         `json:"tenant_email"`
	Column2     sql.NullString `json:"column_2"`
	Column3     sql.NullString `json:"column_3"`
}

type SearchContactsRow struct {
	ID              int64          `json:"id"`
	TenantEmail     string         `json:"tenant_email"`
	CanonicalID     string         `json:"canonical_id"`
	DisplayName     string         `json:"display_name"`
	Source          sql.NullString `json:"source"`
	MasterContactID sql.NullInt64  `json:"master_contact_id"`
	ContactType     sql.NullString `json:"contact_type"`
}

func (q *Queries) SearchContacts(ctx context.Context, arg SearchContactsParams) ([]SearchContactsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchContacts, arg.TenantEmail, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchContactsRow
	for rows.Next() {
		var i SearchContactsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantEmail,
			&i.CanonicalID,
			&i.DisplayName,
			&i.Source,
			&i.MasterContactID,
			&i.ContactType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContactDetails = `-- name: UpdateContactDetails :exec
UPDATE contacts
SET
    display_name = COALESCE(?3, display_name),
    source = COALESCE(?4, source),
    master_contact_id = ?5,
    contact_type = COALESCE(?6, contact_type)
WHERE tenant_email = ?1 AND id = ?2
`

type UpdateContactDetailsParams struct {
	TenantEmail     string         `json:"tenant_email"`
	ID              int64          `json:"id"`
	DisplayName     sql.NullString `json:"display_name"`
	Source          sql.NullString `json:"source"`
	MasterContactID sql.NullInt64  `json:"master_contact_id"`
	ContactType     sql.NullString `json:"contact_type"`
}

func (q *Queries) UpdateContactDetails(ctx context.Context, arg UpdateContactDetailsParams) error {
	_, err := q.db.ExecContext(ctx, updateContactDetails,
		arg.TenantEmail,
		arg.ID,
		arg.DisplayName,
		arg.Source,
		arg.MasterContactID,
		arg.ContactType,
	)
	return err
}

const updateDisplayNameIfEmpty = `-- name: UpdateDisplayNameIfEmpty :exec
UPDATE contacts SET display_name = ?1 WHERE id = ?2 AND tenant_email = ?3 AND (display_name IS NULL OR display_name = '')
`

type UpdateDisplayNameIfEmptyParams struct {
	DisplayName string `json:"display_name"`
	ID          int64  `json:"id"`
	TenantEmail string `json:"tenant_email"`
}

func (q *Queries) UpdateDisplayNameIfEmpty(ctx context.Context, arg UpdateDisplayNameIfEmptyParams) error {
	_, err := q.db.ExecContext(ctx, updateDisplayNameIfEmpty, arg.DisplayName, arg.ID, arg.TenantEmail)
	return err
}

const updateResolutionContactID = `-- name: UpdateResolutionContactID :exec
UPDATE contact_resolution SET contact_id = ?1 WHERE tenant_email = ?2 AND contact_id = ?3
`

type UpdateResolutionContactIDParams struct {
	ContactID   int64  `json:"contact_id"`
	TenantEmail string `json:"tenant_email"`
	ContactID_2 int64  `json:"contact_id_2"`
}

func (q *Queries) UpdateResolutionContactID(ctx context.Context, arg UpdateResolutionContactIDParams) error {
	_, err := q.db.ExecContext(ctx, updateResolutionContactID, arg.ContactID, arg.TenantEmail, arg.ContactID_2)
	return err
}

const upsertContactMapping = `-- name: UpsertContactMapping :one
INSERT INTO contacts (tenant_email, canonical_id, display_name, source)
VALUES (?, ?, ?, ?)
ON CONFLICT(tenant_email, canonical_id) DO UPDATE SET
    display_name = IIF(EXCLUDED.display_name != '' AND EXCLUDED.display_name != contacts.canonical_id, EXCLUDED.display_name, contacts.display_name),
    source = EXCLUDED.source
RETURNING id
`

type UpsertContactMappingParams struct {
	TenantEmail string         `json:"tenant_email"`
	CanonicalID string         `json:"canonical_id"`
	DisplayName string         `json:"display_name"`
	Source      sql.NullString `json:"source"`
}

func (q *Queries) UpsertContactMapping(ctx context.Context, arg UpsertContactMappingParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertContactMapping,
		arg.TenantEmail,
		arg.CanonicalID,
		arg.DisplayName,
		arg.Source,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertContactResolution = `-- name: UpsertContactResolution :exec
INSERT INTO contact_resolution (tenant_email, raw_identifier, contact_id)
VALUES (?, ?, ?)
ON CONFLICT(tenant_email, raw_identifier) DO UPDATE SET contact_id = excluded.contact_id
`

type UpsertContactResolutionParams struct {
	TenantEmail   string `json:"tenant_email"`
	RawIdentifier string `json:"raw_identifier"`
	ContactID     int64  `json:"contact_id"`
}

func (q *Queries) UpsertContactResolution(ctx context.Context, arg UpsertContactResolutionParams) error {
	_, err := q.db.ExecContext(ctx, upsertContactResolution, arg.TenantEmail, arg.RawIdentifier, arg.ContactID)
	return err
}
