// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: decisions.sql

package db

import (
	"context"
	"database/sql"
)

const countExtractionDecisions = `-- name: CountExtractionDecisions :many
SELECT stage, verdict, source, COUNT(*) AS total
FROM extraction_decisions
WHERE user_email = ? AND created_at >= ?
GROUP BY stage, verdict, source
ORDER BY total DESC
`

type CountExtractionDecisionsParams struct {
	UserEmail string       `json:"user_email"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type CountExtractionDecisionsRow struct {
	Stage   string `json:"stage"`
	Verdict string `json:"verdict"`
	Source  string `json:"source"`
	Total   int64  `json:"total"`
}

// Drop counts per stage/verdict/source, to compare against task creation over the same window.
func (q *Queries) CountExtractionDecisions(ctx context.Context, arg CountExtractionDecisionsParams) ([]CountExtractionDecisionsRow, error) {
	rows, err := q.db.QueryContext(ctx, countExtractionDecisions, arg.UserEmail, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountExtractionDecisionsRow
	for rows.Next() {
		var i CountExtractionDecisionsRow
		if err := rows.Scan(
			&i.Stage,
			&i.Verdict,
			&i.Source,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExtractionDecisions = `-- name: ListExtractionDecisions :many
SELECT id, user_email, stage, verdict, source, room, source_ts, category, text_head, created_at
FROM extraction_decisions
WHERE user_email = ?
  AND (?4 IS NULL OR stage = ?4)
  AND created_at >= ?
ORDER BY created_at DESC
LIMIT ?
`

type ListExtractionDecisionsParams struct {
	UserEmail string       `json:"user_email"`
	Stage     interface{}  `json:"stage"`
	CreatedAt sql.NullTime `json:"created_at"`
	Limit     int64        `json:"limit"`
}

// Newest first, for sampling what the pipeline threw away.
func (q *Queries) ListExtractionDecisions(ctx context.Context, arg ListExtractionDecisionsParams) ([]ExtractionDecision, error) {
	rows, err := q.db.QueryContext(ctx, listExtractionDecisions,
		arg.UserEmail,
		arg.Stage,
		arg.CreatedAt,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExtractionDecision
	for rows.Next() {
		var i ExtractionDecision
		if err := rows.Scan(
			&i.ID,
			&i.UserEmail,
			&i.Stage,
			&i.Verdict,
			&i.Source,
			&i.Room,
			&i.SourceTs,
			&i.Category,
			&i.TextHead,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordExtractionDecision = `-- name: RecordExtractionDecision :exec
INSERT INTO extraction_decisions (user_email, stage, verdict, source, room, source_ts, category, text_head)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type RecordExtractionDecisionParams struct {
	UserEmail string `json:"user_email"`
	Stage     string `json:"stage"`
	Verdict   string `json:"verdict"`
	Source    string `json:"source"`
	Room      string `json:"room"`
	SourceTs  string `json:"source_ts"`
	Category  string `json:"category"`
	TextHead  string `json:"text_head"`
}

func (q *Queries) RecordExtractionDecision(ctx context.Context, arg RecordExtractionDecisionParams) error {
	_, err := q.db.ExecContext(ctx, recordExtractionDecision,
		arg.UserEmail,
		arg.Stage,
		arg.Verdict,
		arg.Source,
		arg.Room,
		arg.SourceTs,
		arg.Category,
		arg.TextHead,
	)
	return err
}
