// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: embeddings.sql

package db

import (
	"context"
	"database/sql"
)

const countMissingEmbeddingsForUser = `-- name: CountMissingEmbeddingsForUser :one
SELECT COUNT(*)
FROM messages m
LEFT JOIN message_embeddings e ON e.message_id = m.id
WHERE m.lifecycle != 'active'
  AND m.user_email = ?1
  AND IFNULL(m.task, '') != ''
  AND (e.message_id IS NULL OR e.model != ?2)
`

type CountMissingEmbeddingsForUserParams struct {
	UserEmail sql.NullString `json:"user_email"`
	Model     string         `json:"model"`
}

func (q *Queries) CountMissingEmbeddingsForUser(ctx context.Context, arg CountMissingEmbeddingsForUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMissingEmbeddingsForUser, arg.UserEmail, arg.Model)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteEmbeddingsByModel = `-- name: DeleteEmbeddingsByModel :exec
DELETE FROM message_embeddings WHERE model = ?1
`

func (q *Queries) DeleteEmbeddingsByModel(ctx context.Context, model string) error {
	_, err := q.db.ExecContext(ctx, deleteEmbeddingsByModel, model)
	return err
}

const getMessageEmbedding = `-- name: GetMessageEmbedding :one
SELECT message_id, model, dim, vec, text_hash, created_at
FROM message_embeddings
WHERE message_id = ?1
`

func (q *Queries) GetMessageEmbedding(ctx context.Context, messageID int64) (MessageEmbedding, error) {
	row := q.db.QueryRowContext(ctx, getMessageEmbedding, messageID)
	var i MessageEmbedding
	err := row.Scan(
		&i.MessageID,
		&i.Model,
		&i.Dim,
		&i.Vec,
		&i.TextHash,
		&i.CreatedAt,
	)
	return i, err
}

const listArchiveEmbeddingsPage = `-- name: ListArchiveEmbeddingsPage :many
SELECT e.message_id, e.vec
FROM message_embeddings e
JOIN messages m ON m.id = e.message_id
WHERE m.lifecycle != 'active'
  AND m.user_email = ?1
  AND e.model = ?2
ORDER BY e.message_id
LIMIT ?3 OFFSET ?4
`

type ListArchiveEmbeddingsPageParams struct {
	UserEmail sql.NullString `json:"user_email"`
	Model     string         `json:"model"`
	Limit     int64          `json:"limit"`
	Offset    int64          `json:"offset"`
}

type ListArchiveEmbeddingsPageRow struct {
	MessageID int64  `json:"message_id"`
	Vec       []byte `json:"vec"`
}

func (q *Queries) ListArchiveEmbeddingsPage(ctx context.Context, arg ListArchiveEmbeddingsPageParams) ([]ListArchiveEmbeddingsPageRow, error) {
	rows, err := q.db.QueryContext(ctx, listArchiveEmbeddingsPage,
		arg.UserEmail,
		arg.Model,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListArchiveEmbeddingsPageRow
	for rows.Next() {
		var i ListArchiveEmbeddingsPageRow
		if err := rows.Scan(&i.MessageID, &i.Vec); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMissingEmbeddingsForUser = `-- name: ListMissingEmbeddingsForUser :many
SELECT m.id, COALESCE(m.task, '') AS task, COALESCE(m.original_text, '') AS original_text
FROM messages m
LEFT JOIN message_embeddings e ON e.message_id = m.id
WHERE m.lifecycle != 'active'
  AND m.user_email = ?1
  AND IFNULL(m.task, '') != ''
  AND (e.message_id IS NULL OR e.model != ?2)
ORDER BY m.completed_at DESC, m.id DESC
LIMIT ?3
`

type ListMissingEmbeddingsForUserParams struct {
	UserEmail sql.NullString `json:"user_email"`
	Model     string         `json:"model"`
	Limit     int64          `json:"limit"`
}

type ListMissingEmbeddingsForUserRow struct {
	ID           int64  `json:"id"`
	Task         string `json:"task"`
	OriginalText string `json:"original_text"`
}

func (q *Queries) ListMissingEmbeddingsForUser(ctx context.Context, arg ListMissingEmbeddingsForUserParams) ([]ListMissingEmbeddingsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listMissingEmbeddingsForUser, arg.UserEmail, arg.Model, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMissingEmbeddingsForUserRow
	for rows.Next() {
		var i ListMissingEmbeddingsForUserRow
		if err := rows.Scan(&i.ID, &i.Task, &i.OriginalText); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMessageEmbedding = `-- name: UpsertMessageEmbedding :exec
INSERT INTO message_embeddings (message_id, model, dim, vec, text_hash)
VALUES (?1, ?2, ?3, ?4, ?5)
ON CONFLICT(message_id) DO UPDATE SET
  model = excluded.model,
  dim = excluded.dim,
  vec = excluded.vec,
  text_hash = excluded.text_hash,
  created_at = CURRENT_TIMESTAMP
`

type UpsertMessageEmbeddingParams struct {
	MessageID int64  `json:"message_id"`
	Model     string `json:"model"`
	Dim       int64  `json:"dim"`
	Vec       []byte `json:"vec"`
	TextHash  string `json:"text_hash"`
}

func (q *Queries) UpsertMessageEmbedding(ctx context.Context, arg UpsertMessageEmbeddingParams) error {
	_, err := q.db.ExecContext(ctx, upsertMessageEmbedding,
		arg.MessageID,
		arg.Model,
		arg.Dim,
		arg.Vec,
		arg.TextHash,
	)
	return err
}
