// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: gamification.sql

package db

import (
	"context"
	"database/sql"
)

const getAchievements = `-- name: GetAchievements :many
SELECT id, name, COALESCE(description, '') as description, COALESCE(icon, '') as icon, 
       COALESCE(criteria_type, '') as criteria_type, COALESCE(criteria_value, 0) as criteria_value, 
       COALESCE(target_value, 0) as target_value, COALESCE(xp_reward, 0) as xp_reward 
FROM achievements
`

type GetAchievementsRow struct {
	ID            int64  `json:"id"`
	Name          string `json:"name"`
	Description   string `json:"description"`
	Icon          string `json:"icon"`
	CriteriaType  string `json:"criteria_type"`
	CriteriaValue int64  `json:"criteria_value"`
	TargetValue   int64  `json:"target_value"`
	XpReward      int64  `json:"xp_reward"`
}

func (q *Queries) GetAchievements(ctx context.Context) ([]GetAchievementsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAchievements)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAchievementsRow
	for rows.Next() {
		var i GetAchievementsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Icon,
			&i.CriteriaType,
			&i.CriteriaValue,
			&i.TargetValue,
			&i.XpReward,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserAchievements = `-- name: GetUserAchievements :many
SELECT 
    COALESCE(user_id, 0) as user_id, 
    COALESCE(achievement_id, 0) as achievement_id, 
    unlocked_at 
FROM user_achievements 
WHERE user_id = CAST(?1 AS INTEGER)
`

type GetUserAchievementsRow struct {
	UserID        int64        `json:"user_id"`
	AchievementID int64        `json:"achievement_id"`
	UnlockedAt    sql.NullTime `json:"unlocked_at"`
}

func (q *Queries) GetUserAchievements(ctx context.Context, dollar_1 int64) ([]GetUserAchievementsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserAchievements, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserAchievementsRow
	for rows.Next() {
		var i GetUserAchievementsRow
		if err := rows.Scan(&i.UserID, &i.AchievementID, &i.UnlockedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unlockAchievement = `-- name: UnlockAchievement :exec
INSERT INTO user_achievements (user_id, achievement_id, unlocked_at) 
VALUES (CAST(?1 AS INTEGER), CAST(?2 AS INTEGER), CURRENT_TIMESTAMP) 
ON CONFLICT (user_id, achievement_id) 
DO UPDATE SET unlocked_at = EXCLUDED.unlocked_at
`

type UnlockAchievementParams struct {
	Column1 int64 `json:"column_1"`
	Column2 int64 `json:"column_2"`
}

func (q *Queries) UnlockAchievement(ctx context.Context, arg UnlockAchievementParams) error {
	_, err := q.db.ExecContext(ctx, unlockAchievement, arg.Column1, arg.Column2)
	return err
}

const updateUserGamification = `-- name: UpdateUserGamification :exec
UPDATE users 
SET points = ?1, streak = ?2, level = ?3, xp = ?4, daily_goal = ?5, last_completed_at = ?6, streak_freezes = ?7 
WHERE email = ?8
`

type UpdateUserGamificationParams struct {
	Points          sql.NullInt64  `json:"points"`
	Streak          sql.NullInt64  `json:"streak"`
	Level           sql.NullInt64  `json:"level"`
	Xp              sql.NullInt64  `json:"xp"`
	DailyGoal       sql.NullInt64  `json:"daily_goal"`
	LastCompletedAt sql.NullTime   `json:"last_completed_at"`
	StreakFreezes   sql.NullInt64  `json:"streak_freezes"`
	Email           sql.NullString `json:"email"`
}

func (q *Queries) UpdateUserGamification(ctx context.Context, arg UpdateUserGamificationParams) error {
	_, err := q.db.ExecContext(ctx, updateUserGamification,
		arg.Points,
		arg.Streak,
		arg.Level,
		arg.Xp,
		arg.DailyGoal,
		arg.LastCompletedAt,
		arg.StreakFreezes,
		arg.Email,
	)
	return err
}
