// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: identity_resolution.sql

package db

import (
	"context"
	"database/sql"
)

const addContactAlias = `-- name: AddContactAlias :exec
INSERT OR IGNORE INTO contact_aliases (contact_id, identifier_type, identifier_value, source, trust_level)
VALUES (?, ?, ?, ?, ?)
`

type AddContactAliasParams struct {
	ContactID       int64         `json:"contact_id"`
	IdentifierType  string        `json:"identifier_type"`
	IdentifierValue string        `json:"identifier_value"`
	Source          string        `json:"source"`
	TrustLevel      sql.NullInt64 `json:"trust_level"`
}

func (q *Queries) AddContactAlias(ctx context.Context, arg AddContactAliasParams) error {
	_, err := q.db.ExecContext(ctx, addContactAlias,
		arg.ContactID,
		arg.IdentifierType,
		arg.IdentifierValue,
		arg.Source,
		arg.TrustLevel,
	)
	return err
}

const createIdentityMergeCandidatesTable = `-- name: CreateIdentityMergeCandidatesTable :exec
CREATE TABLE IF NOT EXISTS identity_merge_candidates (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    contact_id_a INTEGER NOT NULL,
    contact_id_b INTEGER NOT NULL,
    confidence REAL NOT NULL, -- 0.0 to 1.0
    reason TEXT,
    status TEXT DEFAULT 'pending', -- 'pending', 'approved', 'rejected'
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(contact_id_a, contact_id_b)
)
`

func (q *Queries) CreateIdentityMergeCandidatesTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createIdentityMergeCandidatesTable)
	return err
}

const createIdentityMergeHistoryTable = `-- name: CreateIdentityMergeHistoryTable :exec
CREATE TABLE IF NOT EXISTS identity_merge_history (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    source_contact_id INTEGER NOT NULL,
    target_contact_id INTEGER NOT NULL,
    reason TEXT NOT NULL,
    merged_at DATETIME DEFAULT CURRENT_TIMESTAMP
)
`

func (q *Queries) CreateIdentityMergeHistoryTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createIdentityMergeHistoryTable)
	return err
}

const findContactByAlias = `-- name: FindContactByAlias :one
SELECT contact_id
FROM contact_aliases
WHERE identifier_value = ? AND identifier_type = ?
`

type FindContactByAliasParams struct {
	IdentifierValue string `json:"identifier_value"`
	IdentifierType  string `json:"identifier_type"`
}

func (q *Queries) FindContactByAlias(ctx context.Context, arg FindContactByAliasParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, findContactByAlias, arg.IdentifierValue, arg.IdentifierType)
	var contact_id int64
	err := row.Scan(&contact_id)
	return contact_id, err
}

const getContactAliases = `-- name: GetContactAliases :many
SELECT id, contact_id, identifier_type, identifier_value, source, trust_level, created_at
FROM contact_aliases
WHERE contact_id = ?
`

func (q *Queries) GetContactAliases(ctx context.Context, contactID int64) ([]ContactAlias, error) {
	rows, err := q.db.QueryContext(ctx, getContactAliases, contactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContactAlias
	for rows.Next() {
		var i ContactAlias
		if err := rows.Scan(
			&i.ID,
			&i.ContactID,
			&i.IdentifierType,
			&i.IdentifierValue,
			&i.Source,
			&i.TrustLevel,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMergeCandidates = `-- name: GetMergeCandidates :many
SELECT id, contact_id_a, contact_id_b, confidence, reason, status, created_at
FROM identity_merge_candidates
WHERE status = 'pending'
`

func (q *Queries) GetMergeCandidates(ctx context.Context) ([]IdentityMergeCandidate, error) {
	rows, err := q.db.QueryContext(ctx, getMergeCandidates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IdentityMergeCandidate
	for rows.Next() {
		var i IdentityMergeCandidate
		if err := rows.Scan(
			&i.ID,
			&i.ContactIDA,
			&i.ContactIDB,
			&i.Confidence,
			&i.Reason,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMergeHistory = `-- name: InsertMergeHistory :exec
INSERT INTO identity_merge_history (source_contact_id, target_contact_id, reason)
VALUES (?, ?, ?)
`

type InsertMergeHistoryParams struct {
	SourceContactID int64  `json:"source_contact_id"`
	TargetContactID int64  `json:"target_contact_id"`
	Reason          string `json:"reason"`
}

func (q *Queries) InsertMergeHistory(ctx context.Context, arg InsertMergeHistoryParams) error {
	_, err := q.db.ExecContext(ctx, insertMergeHistory, arg.SourceContactID, arg.TargetContactID, arg.Reason)
	return err
}

const migrateContactsDropLegacyAliases = `-- name: MigrateContactsDropLegacyAliases :exec
ALTER TABLE contacts DROP COLUMN legacy_aliases_deprecated
`

func (q *Queries) MigrateContactsDropLegacyAliases(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, migrateContactsDropLegacyAliases)
	return err
}

const migrateContactsRenameLegacyAliases = `-- name: MigrateContactsRenameLegacyAliases :exec
ALTER TABLE contacts RENAME COLUMN aliases TO legacy_aliases_deprecated
`

func (q *Queries) MigrateContactsRenameLegacyAliases(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, migrateContactsRenameLegacyAliases)
	return err
}

const migrateLegacyAliases = `-- name: MigrateLegacyAliases :exec
INSERT OR IGNORE INTO contact_aliases (contact_id, identifier_type, identifier_value, source, trust_level)
SELECT contacts.id, 'name', trim(value), source, 1
FROM contacts, json_each('["' || replace(legacy_aliases_deprecated, ',', '","') || '"]')
WHERE legacy_aliases_deprecated != '' AND legacy_aliases_deprecated IS NOT NULL
`

func (q *Queries) MigrateLegacyAliases(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, migrateLegacyAliases)
	return err
}

const updateMergeCandidateStatus = `-- name: UpdateMergeCandidateStatus :exec
UPDATE identity_merge_candidates
SET status = ?
WHERE id = ?
`

type UpdateMergeCandidateStatusParams struct {
	Status sql.NullString `json:"status"`
	ID     int64          `json:"id"`
}

func (q *Queries) UpdateMergeCandidateStatus(ctx context.Context, arg UpdateMergeCandidateStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateMergeCandidateStatus, arg.Status, arg.ID)
	return err
}
