// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: learning.sql

package db

import (
	"context"
	"database/sql"
)

const countLearnedExamplesByOrigin = `-- name: CountLearnedExamplesByOrigin :one
SELECT COUNT(*) FROM learned_examples
WHERE user_email = ? AND origin = ?
`

type CountLearnedExamplesByOriginParams struct {
	UserEmail string `json:"user_email"`
	Origin    string `json:"origin"`
}

func (q *Queries) CountLearnedExamplesByOrigin(ctx context.Context, arg CountLearnedExamplesByOriginParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLearnedExamplesByOrigin, arg.UserEmail, arg.Origin)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteLearnedExample = `-- name: DeleteLearnedExample :exec
DELETE FROM learned_examples WHERE id = ? AND user_email = ?
`

type DeleteLearnedExampleParams struct {
	ID        int64  `json:"id"`
	UserEmail string `json:"user_email"`
}

func (q *Queries) DeleteLearnedExample(ctx context.Context, arg DeleteLearnedExampleParams) error {
	_, err := q.db.ExecContext(ctx, deleteLearnedExample, arg.ID, arg.UserEmail)
	return err
}

const getCorrectionObservation = `-- name: GetCorrectionObservation :one
SELECT id, user_email, kind, from_value, to_value, scope, evidence_count, seen_message_ids, status, created_at, updated_at
FROM correction_observations
WHERE user_email = ? AND kind = ? AND from_value = ? AND to_value = ? AND scope = ?
`

type GetCorrectionObservationParams struct {
	UserEmail string `json:"user_email"`
	Kind      string `json:"kind"`
	FromValue string `json:"from_value"`
	ToValue   string `json:"to_value"`
	Scope     string `json:"scope"`
}

func (q *Queries) GetCorrectionObservation(ctx context.Context, arg GetCorrectionObservationParams) (CorrectionObservation, error) {
	row := q.db.QueryRowContext(ctx, getCorrectionObservation,
		arg.UserEmail,
		arg.Kind,
		arg.FromValue,
		arg.ToValue,
		arg.Scope,
	)
	var i CorrectionObservation
	err := row.Scan(
		&i.ID,
		&i.UserEmail,
		&i.Kind,
		&i.FromValue,
		&i.ToValue,
		&i.Scope,
		&i.EvidenceCount,
		&i.SeenMessageIds,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCorrectionObservation = `-- name: InsertCorrectionObservation :exec
INSERT INTO correction_observations (user_email, kind, from_value, to_value, scope, evidence_count, seen_message_ids, status)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertCorrectionObservationParams struct {
	UserEmail      string `json:"user_email"`
	Kind           string `json:"kind"`
	FromValue      string `json:"from_value"`
	ToValue        string `json:"to_value"`
	Scope          string `json:"scope"`
	EvidenceCount  int64  `json:"evidence_count"`
	SeenMessageIds string `json:"seen_message_ids"`
	Status         string `json:"status"`
}

func (q *Queries) InsertCorrectionObservation(ctx context.Context, arg InsertCorrectionObservationParams) error {
	_, err := q.db.ExecContext(ctx, insertCorrectionObservation,
		arg.UserEmail,
		arg.Kind,
		arg.FromValue,
		arg.ToValue,
		arg.Scope,
		arg.EvidenceCount,
		arg.SeenMessageIds,
		arg.Status,
	)
	return err
}

const insertLearnedExample = `-- name: InsertLearnedExample :exec
INSERT INTO learned_examples (user_email, source, lang, input, expected, origin, message_id)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(user_email, message_id, origin) DO NOTHING
`

type InsertLearnedExampleParams struct {
	UserEmail string        `json:"user_email"`
	Source    string        `json:"source"`
	Lang      string        `json:"lang"`
	Input     string        `json:"input"`
	Expected  string        `json:"expected"`
	Origin    string        `json:"origin"`
	MessageID sql.NullInt64 `json:"message_id"`
}

func (q *Queries) InsertLearnedExample(ctx context.Context, arg InsertLearnedExampleParams) error {
	_, err := q.db.ExecContext(ctx, insertLearnedExample,
		arg.UserEmail,
		arg.Source,
		arg.Lang,
		arg.Input,
		arg.Expected,
		arg.Origin,
		arg.MessageID,
	)
	return err
}

const listActiveSuppressRules = `-- name: ListActiveSuppressRules :many
SELECT id, user_email, kind, from_value, to_value, scope, evidence_count, seen_message_ids, status, created_at, updated_at
FROM correction_observations
WHERE user_email = ? AND kind = 'suppress' AND status IN ('promoted', 'approved')
`

func (q *Queries) ListActiveSuppressRules(ctx context.Context, userEmail string) ([]CorrectionObservation, error) {
	rows, err := q.db.QueryContext(ctx, listActiveSuppressRules, userEmail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CorrectionObservation
	for rows.Next() {
		var i CorrectionObservation
		if err := rows.Scan(
			&i.ID,
			&i.UserEmail,
			&i.Kind,
			&i.FromValue,
			&i.ToValue,
			&i.Scope,
			&i.EvidenceCount,
			&i.SeenMessageIds,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCorrectionObservationsByStatus = `-- name: ListCorrectionObservationsByStatus :many
SELECT id, user_email, kind, from_value, to_value, scope, evidence_count, seen_message_ids, status, created_at, updated_at
FROM correction_observations
WHERE user_email = ? AND status = ?
ORDER BY updated_at DESC
`

type ListCorrectionObservationsByStatusParams struct {
	UserEmail string `json:"user_email"`
	Status    string `json:"status"`
}

func (q *Queries) ListCorrectionObservationsByStatus(ctx context.Context, arg ListCorrectionObservationsByStatusParams) ([]CorrectionObservation, error) {
	rows, err := q.db.QueryContext(ctx, listCorrectionObservationsByStatus, arg.UserEmail, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CorrectionObservation
	for rows.Next() {
		var i CorrectionObservation
		if err := rows.Scan(
			&i.ID,
			&i.UserEmail,
			&i.Kind,
			&i.FromValue,
			&i.ToValue,
			&i.Scope,
			&i.EvidenceCount,
			&i.SeenMessageIds,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLearnedExamples = `-- name: ListLearnedExamples :many
SELECT id, user_email, source, lang, input, expected, origin, message_id, created_at
FROM learned_examples
WHERE user_email = ?
ORDER BY created_at DESC
LIMIT ?
`

type ListLearnedExamplesParams struct {
	UserEmail string `json:"user_email"`
	Limit     int64  `json:"limit"`
}

func (q *Queries) ListLearnedExamples(ctx context.Context, arg ListLearnedExamplesParams) ([]LearnedExample, error) {
	rows, err := q.db.QueryContext(ctx, listLearnedExamples, arg.UserEmail, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LearnedExample
	for rows.Next() {
		var i LearnedExample
		if err := rows.Scan(
			&i.ID,
			&i.UserEmail,
			&i.Source,
			&i.Lang,
			&i.Input,
			&i.Expected,
			&i.Origin,
			&i.MessageID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCorrectionObservationEvidence = `-- name: UpdateCorrectionObservationEvidence :exec
UPDATE correction_observations
SET evidence_count = ?, seen_message_ids = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateCorrectionObservationEvidenceParams struct {
	EvidenceCount  int64  `json:"evidence_count"`
	SeenMessageIds string `json:"seen_message_ids"`
	ID             int64  `json:"id"`
}

func (q *Queries) UpdateCorrectionObservationEvidence(ctx context.Context, arg UpdateCorrectionObservationEvidenceParams) error {
	_, err := q.db.ExecContext(ctx, updateCorrectionObservationEvidence, arg.EvidenceCount, arg.SeenMessageIds, arg.ID)
	return err
}

const updateCorrectionObservationStatus = `-- name: UpdateCorrectionObservationStatus :exec
UPDATE correction_observations
SET status = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND user_email = ?
`

type UpdateCorrectionObservationStatusParams struct {
	Status    string `json:"status"`
	ID        int64  `json:"id"`
	UserEmail string `json:"user_email"`
}

func (q *Queries) UpdateCorrectionObservationStatus(ctx context.Context, arg UpdateCorrectionObservationStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateCorrectionObservationStatus, arg.Status, arg.ID, arg.UserEmail)
	return err
}
