// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: line.sql

package db

import (
	"context"
)

const getUnprocessedLineMessages = `-- name: GetUnprocessedLineMessages :many
SELECT id, line_message_id, chat_type, chat_id, sender_id, sender_name,
       text, reply_to_id, mentioned_ids, ts, processed, created_at
FROM line_inbox
WHERE processed = 0
ORDER BY ts ASC
LIMIT 200
`

func (q *Queries) GetUnprocessedLineMessages(ctx context.Context) ([]LineInbox, error) {
	rows, err := q.db.QueryContext(ctx, getUnprocessedLineMessages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LineInbox
	for rows.Next() {
		var i LineInbox
		if err := rows.Scan(
			&i.ID,
			&i.LineMessageID,
			&i.ChatType,
			&i.ChatID,
			&i.SenderID,
			&i.SenderName,
			&i.Text,
			&i.ReplyToID,
			&i.MentionedIds,
			&i.Ts,
			&i.Processed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertLineInbox = `-- name: InsertLineInbox :exec
INSERT OR IGNORE INTO line_inbox (
    line_message_id, chat_type, chat_id, sender_id, sender_name,
    text, reply_to_id, mentioned_ids, ts
) VALUES (
    ?1, ?2, ?3, ?4, ?5,
    ?6, ?7, ?8, ?9
)
`

type InsertLineInboxParams struct {
	LineMessageID string `json:"line_message_id"`
	ChatType      string `json:"chat_type"`
	ChatID        string `json:"chat_id"`
	SenderID      string `json:"sender_id"`
	SenderName    string `json:"sender_name"`
	Text          string `json:"text"`
	ReplyToID     string `json:"reply_to_id"`
	MentionedIds  string `json:"mentioned_ids"`
	Ts            int64  `json:"ts"`
}

func (q *Queries) InsertLineInbox(ctx context.Context, arg InsertLineInboxParams) error {
	_, err := q.db.ExecContext(ctx, insertLineInbox,
		arg.LineMessageID,
		arg.ChatType,
		arg.ChatID,
		arg.SenderID,
		arg.SenderName,
		arg.Text,
		arg.ReplyToID,
		arg.MentionedIds,
		arg.Ts,
	)
	return err
}

const markLineInboxProcessed = `-- name: MarkLineInboxProcessed :exec
UPDATE line_inbox SET processed = 1 WHERE id = ?1
`

func (q *Queries) MarkLineInboxProcessed(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markLineInboxProcessed, id)
	return err
}
