// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const archiveOldTasks = `-- name: ArchiveOldTasks :execrows
UPDATE messages SET is_deleted = 1 WHERE is_deleted = 0 AND done = 1 AND completed_at < datetime('now', ?)
`

func (q *Queries) ArchiveOldTasks(ctx context.Context, datetime interface{}) (int64, error) {
	result, err := q.db.ExecContext(ctx, archiveOldTasks, datetime)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (user_email, source, room, task, requester, assignee, assigned_at, link, source_ts, original_text, category, deadline, thread_id, assignee_reason, replied_to_id, is_context_query, constraints, metadata, source_channels, consolidated_context, subtasks) 
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(user_email, source_ts) DO NOTHING
RETURNING id
`

type CreateMessageParams struct {
	UserEmail           sql.NullString `json:"user_email"`
	Source              sql.NullString `json:"source"`
	Room                sql.NullString `json:"room"`
	Task                sql.NullString `json:"task"`
	Requester           sql.NullString `json:"requester"`
	Assignee            sql.NullString `json:"assignee"`
	AssignedAt          sql.NullTime   `json:"assigned_at"`
	Link                sql.NullString `json:"link"`
	SourceTs            sql.NullString `json:"source_ts"`
	OriginalText        sql.NullString `json:"original_text"`
	Category            sql.NullString `json:"category"`
	Deadline            sql.NullString `json:"deadline"`
	ThreadID            sql.NullString `json:"thread_id"`
	AssigneeReason      sql.NullString `json:"assignee_reason"`
	RepliedToID         sql.NullString `json:"replied_to_id"`
	IsContextQuery      sql.NullInt64  `json:"is_context_query"`
	Constraints         sql.NullString `json:"constraints"`
	Metadata            sql.NullString `json:"metadata"`
	SourceChannels      sql.NullString `json:"source_channels"`
	ConsolidatedContext sql.NullString `json:"consolidated_context"`
	Subtasks            sql.NullString `json:"subtasks"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createMessage,
		arg.UserEmail,
		arg.Source,
		arg.Room,
		arg.Task,
		arg.Requester,
		arg.Assignee,
		arg.AssignedAt,
		arg.Link,
		arg.SourceTs,
		arg.OriginalText,
		arg.Category,
		arg.Deadline,
		arg.ThreadID,
		arg.AssigneeReason,
		arg.RepliedToID,
		arg.IsContextQuery,
		arg.Constraints,
		arg.Metadata,
		arg.SourceChannels,
		arg.ConsolidatedContext,
		arg.Subtasks,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteMessages = `-- name: DeleteMessages :exec
UPDATE messages SET is_deleted = 1 WHERE user_email = ? AND id IN (/*SLICE:ids*/?)
`

type DeleteMessagesParams struct {
	UserEmail sql.NullString `json:"user_email"`
	Ids       []int64        `json:"ids"`
}

func (q *Queries) DeleteMessages(ctx context.Context, arg DeleteMessagesParams) error {
	query := deleteMessages
	var queryParams []interface{}
	queryParams = append(queryParams, arg.UserEmail)
	if len(arg.Ids) > 0 {
		for _, v := range arg.Ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(arg.Ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const getActiveTasksForContext = `-- name: GetActiveTasksForContext :many
SELECT id, task, original_text, requester, assignee, source, room, assigned_at, done, completed_at, category
FROM v_messages
WHERE user_email = ? AND source = ? AND room = ? AND is_deleted = 0
AND IFNULL(task, '') != ''
AND (done = 0 OR (done = 1 AND completed_at > datetime('now', '-30 days')))
ORDER BY assigned_at DESC
LIMIT 50
`

type GetActiveTasksForContextParams struct {
	UserEmail string `json:"user_email"`
	Source    string `json:"source"`
	Room      string `json:"room"`
}

type GetActiveTasksForContextRow struct {
	ID           int64        `json:"id"`
	Task         string       `json:"task"`
	OriginalText string       `json:"original_text"`
	Requester    string       `json:"requester"`
	Assignee     string       `json:"assignee"`
	Source       string       `json:"source"`
	Room         string       `json:"room"`
	AssignedAt   sql.NullTime `json:"assigned_at"`
	Done         bool         `json:"done"`
	CompletedAt  sql.NullTime `json:"completed_at"`
	Category     string       `json:"category"`
}

func (q *Queries) GetActiveTasksForContext(ctx context.Context, arg GetActiveTasksForContextParams) ([]GetActiveTasksForContextRow, error) {
	rows, err := q.db.QueryContext(ctx, getActiveTasksForContext, arg.UserEmail, arg.Source, arg.Room)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveTasksForContextRow
	for rows.Next() {
		var i GetActiveTasksForContextRow
		if err := rows.Scan(
			&i.ID,
			&i.Task,
			&i.OriginalText,
			&i.Requester,
			&i.Assignee,
			&i.Source,
			&i.Room,
			&i.AssignedAt,
			&i.Done,
			&i.CompletedAt,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIncompleteByThreadID = `-- name: GetIncompleteByThreadID :many
SELECT id, COALESCE(user_email, '') as user_email, COALESCE(source, '') as source, COALESCE(room, '') as room, COALESCE(task, '') as task, COALESCE(requester, '') as requester, COALESCE(assignee, '') as assignee, assigned_at, COALESCE(link, '') as link, COALESCE(source_ts, '') as source_ts, COALESCE(original_text, '') as original_text, done, is_deleted, created_at, completed_at, COALESCE(category, '') as category, COALESCE(deadline, '') as deadline, COALESCE(thread_id, '') as thread_id, COALESCE(assignee_reason, '') as assignee_reason, COALESCE(replied_to_id, '') as replied_to_id, is_context_query, COALESCE(constraints, '') as constraints, COALESCE(metadata, '') as metadata, COALESCE(source_channels, '') as source_channels, COALESCE(consolidated_context, '') as consolidated_context, COALESCE(subtasks, '[]') as subtasks, COALESCE(requester_canonical, '') as requester_canonical, COALESCE(assignee_canonical, '') as assignee_canonical, COALESCE(requester_type, '') as requester_type, COALESCE(assignee_type, '') as assignee_type
FROM v_messages WHERE user_email = ? AND thread_id = ? AND done = 0 AND is_deleted = 0 AND IFNULL(task, '') != ''
`

type GetIncompleteByThreadIDParams struct {
	UserEmail string `json:"user_email"`
	ThreadID  string `json:"thread_id"`
}

type GetIncompleteByThreadIDRow struct {
	ID                  int64        `json:"id"`
	UserEmail           string       `json:"user_email"`
	Source              string       `json:"source"`
	Room                string       `json:"room"`
	Task                string       `json:"task"`
	Requester           string       `json:"requester"`
	Assignee            string       `json:"assignee"`
	AssignedAt          sql.NullTime `json:"assigned_at"`
	Link                string       `json:"link"`
	SourceTs            string       `json:"source_ts"`
	OriginalText        string       `json:"original_text"`
	Done                bool         `json:"done"`
	IsDeleted           bool         `json:"is_deleted"`
	CreatedAt           sql.NullTime `json:"created_at"`
	CompletedAt         sql.NullTime `json:"completed_at"`
	Category            string       `json:"category"`
	Deadline            string       `json:"deadline"`
	ThreadID            string       `json:"thread_id"`
	AssigneeReason      string       `json:"assignee_reason"`
	RepliedToID         string       `json:"replied_to_id"`
	IsContextQuery      int64        `json:"is_context_query"`
	Constraints         string       `json:"constraints"`
	Metadata            string       `json:"metadata"`
	SourceChannels      string       `json:"source_channels"`
	ConsolidatedContext string       `json:"consolidated_context"`
	Subtasks            string       `json:"subtasks"`
	RequesterCanonical  string       `json:"requester_canonical"`
	AssigneeCanonical   string       `json:"assignee_canonical"`
	RequesterType       string       `json:"requester_type"`
	AssigneeType        string       `json:"assignee_type"`
}

func (q *Queries) GetIncompleteByThreadID(ctx context.Context, arg GetIncompleteByThreadIDParams) ([]GetIncompleteByThreadIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getIncompleteByThreadID, arg.UserEmail, arg.ThreadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetIncompleteByThreadIDRow
	for rows.Next() {
		var i GetIncompleteByThreadIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserEmail,
			&i.Source,
			&i.Room,
			&i.Task,
			&i.Requester,
			&i.Assignee,
			&i.AssignedAt,
			&i.Link,
			&i.SourceTs,
			&i.OriginalText,
			&i.Done,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.Category,
			&i.Deadline,
			&i.ThreadID,
			&i.AssigneeReason,
			&i.RepliedToID,
			&i.IsContextQuery,
			&i.Constraints,
			&i.Metadata,
			&i.SourceChannels,
			&i.ConsolidatedContext,
			&i.Subtasks,
			&i.RequesterCanonical,
			&i.AssigneeCanonical,
			&i.RequesterType,
			&i.AssigneeType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT id, COALESCE(user_email, '') as user_email, COALESCE(source, '') as source, COALESCE(room, '') as room, COALESCE(task, '') as task, COALESCE(requester, '') as requester, COALESCE(assignee, '') as assignee, assigned_at, COALESCE(link, '') as link, COALESCE(source_ts, '') as source_ts, COALESCE(original_text, '') as original_text, done, is_deleted, created_at, completed_at, COALESCE(category, '') as category, COALESCE(deadline, '') as deadline, COALESCE(thread_id, '') as thread_id, COALESCE(assignee_reason, '') as assignee_reason, COALESCE(replied_to_id, '') as replied_to_id, is_context_query, COALESCE(constraints, '') as constraints, COALESCE(metadata, '') as metadata, COALESCE(source_channels, '') as source_channels, COALESCE(consolidated_context, '') as consolidated_context, COALESCE(subtasks, '[]') as subtasks, COALESCE(requester_canonical, '') as requester_canonical, COALESCE(assignee_canonical, '') as assignee_canonical, COALESCE(requester_type, '') as requester_type, COALESCE(assignee_type, '') as assignee_type
FROM v_messages WHERE id = ?
`

type GetMessageByIDRow struct {
	ID                  int64        `json:"id"`
	UserEmail           string       `json:"user_email"`
	Source              string       `json:"source"`
	Room                string       `json:"room"`
	Task                string       `json:"task"`
	Requester           string       `json:"requester"`
	Assignee            string       `json:"assignee"`
	AssignedAt          sql.NullTime `json:"assigned_at"`
	Link                string       `json:"link"`
	SourceTs            string       `json:"source_ts"`
	OriginalText        string       `json:"original_text"`
	Done                bool         `json:"done"`
	IsDeleted           bool         `json:"is_deleted"`
	CreatedAt           sql.NullTime `json:"created_at"`
	CompletedAt         sql.NullTime `json:"completed_at"`
	Category            string       `json:"category"`
	Deadline            string       `json:"deadline"`
	ThreadID            string       `json:"thread_id"`
	AssigneeReason      string       `json:"assignee_reason"`
	RepliedToID         string       `json:"replied_to_id"`
	IsContextQuery      int64        `json:"is_context_query"`
	Constraints         string       `json:"constraints"`
	Metadata            string       `json:"metadata"`
	SourceChannels      string       `json:"source_channels"`
	ConsolidatedContext string       `json:"consolidated_context"`
	Subtasks            string       `json:"subtasks"`
	RequesterCanonical  string       `json:"requester_canonical"`
	AssigneeCanonical   string       `json:"assignee_canonical"`
	RequesterType       string       `json:"requester_type"`
	AssigneeType        string       `json:"assignee_type"`
}

func (q *Queries) GetMessageByID(ctx context.Context, id int64) (GetMessageByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getMessageByID, id)
	var i GetMessageByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserEmail,
		&i.Source,
		&i.Room,
		&i.Task,
		&i.Requester,
		&i.Assignee,
		&i.AssignedAt,
		&i.Link,
		&i.SourceTs,
		&i.OriginalText,
		&i.Done,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.Category,
		&i.Deadline,
		&i.ThreadID,
		&i.AssigneeReason,
		&i.RepliedToID,
		&i.IsContextQuery,
		&i.Constraints,
		&i.Metadata,
		&i.SourceChannels,
		&i.ConsolidatedContext,
		&i.Subtasks,
		&i.RequesterCanonical,
		&i.AssigneeCanonical,
		&i.RequesterType,
		&i.AssigneeType,
	)
	return i, err
}

const getMessagesByEmail = `-- name: GetMessagesByEmail :many
SELECT id, COALESCE(user_email, '') as user_email, COALESCE(source, '') as source, COALESCE(room, '') as room, COALESCE(task, '') as task, COALESCE(requester, '') as requester, COALESCE(assignee, '') as assignee, assigned_at, COALESCE(link, '') as link, COALESCE(source_ts, '') as source_ts, COALESCE(original_text, '') as original_text, done, is_deleted, created_at, completed_at, COALESCE(category, '') as category, COALESCE(deadline, '') as deadline, COALESCE(thread_id, '') as thread_id, COALESCE(assignee_reason, '') as assignee_reason, COALESCE(replied_to_id, '') as replied_to_id, is_context_query, COALESCE(constraints, '') as constraints, COALESCE(metadata, '') as metadata, COALESCE(source_channels, '') as source_channels, COALESCE(consolidated_context, '') as consolidated_context, COALESCE(subtasks, '[]') as subtasks, COALESCE(requester_canonical, '') as requester_canonical, COALESCE(assignee_canonical, '') as assignee_canonical, COALESCE(requester_type, '') as requester_type, COALESCE(assignee_type, '') as assignee_type
FROM v_messages WHERE user_email = ?1 AND is_deleted = 0 AND IFNULL(task, '') != '' ORDER BY created_at DESC
`

type GetMessagesByEmailRow struct {
	ID                  int64        `json:"id"`
	UserEmail           string       `json:"user_email"`
	Source              string       `json:"source"`
	Room                string       `json:"room"`
	Task                string       `json:"task"`
	Requester           string       `json:"requester"`
	Assignee            string       `json:"assignee"`
	AssignedAt          sql.NullTime `json:"assigned_at"`
	Link                string       `json:"link"`
	SourceTs            string       `json:"source_ts"`
	OriginalText        string       `json:"original_text"`
	Done                bool         `json:"done"`
	IsDeleted           bool         `json:"is_deleted"`
	CreatedAt           sql.NullTime `json:"created_at"`
	CompletedAt         sql.NullTime `json:"completed_at"`
	Category            string       `json:"category"`
	Deadline            string       `json:"deadline"`
	ThreadID            string       `json:"thread_id"`
	AssigneeReason      string       `json:"assignee_reason"`
	RepliedToID         string       `json:"replied_to_id"`
	IsContextQuery      int64        `json:"is_context_query"`
	Constraints         string       `json:"constraints"`
	Metadata            string       `json:"metadata"`
	SourceChannels      string       `json:"source_channels"`
	ConsolidatedContext string       `json:"consolidated_context"`
	Subtasks            string       `json:"subtasks"`
	RequesterCanonical  string       `json:"requester_canonical"`
	AssigneeCanonical   string       `json:"assignee_canonical"`
	RequesterType       string       `json:"requester_type"`
	AssigneeType        string       `json:"assignee_type"`
}

func (q *Queries) GetMessagesByEmail(ctx context.Context, userEmail string) ([]GetMessagesByEmailRow, error) {
	rows, err := q.db.QueryContext(ctx, getMessagesByEmail, userEmail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMessagesByEmailRow
	for rows.Next() {
		var i GetMessagesByEmailRow
		if err := rows.Scan(
			&i.ID,
			&i.UserEmail,
			&i.Source,
			&i.Room,
			&i.Task,
			&i.Requester,
			&i.Assignee,
			&i.AssignedAt,
			&i.Link,
			&i.SourceTs,
			&i.OriginalText,
			&i.Done,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.Category,
			&i.Deadline,
			&i.ThreadID,
			&i.AssigneeReason,
			&i.RepliedToID,
			&i.IsContextQuery,
			&i.Constraints,
			&i.Metadata,
			&i.SourceChannels,
			&i.ConsolidatedContext,
			&i.Subtasks,
			&i.RequesterCanonical,
			&i.AssigneeCanonical,
			&i.RequesterType,
			&i.AssigneeType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessagesByIDs = `-- name: GetMessagesByIDs :many
SELECT id, COALESCE(user_email, '') as user_email, COALESCE(source, '') as source, COALESCE(room, '') as room, COALESCE(task, '') as task, COALESCE(requester, '') as requester, COALESCE(assignee, '') as assignee, assigned_at, COALESCE(link, '') as link, COALESCE(source_ts, '') as source_ts, COALESCE(original_text, '') as original_text, done, is_deleted, created_at, completed_at, COALESCE(category, '') as category, COALESCE(deadline, '') as deadline, COALESCE(thread_id, '') as thread_id, COALESCE(assignee_reason, '') as assignee_reason, COALESCE(replied_to_id, '') as replied_to_id, is_context_query, COALESCE(constraints, '') as constraints, COALESCE(metadata, '') as metadata, COALESCE(source_channels, '') as source_channels, COALESCE(consolidated_context, '') as consolidated_context, COALESCE(subtasks, '[]') as subtasks, COALESCE(requester_canonical, '') as requester_canonical, COALESCE(assignee_canonical, '') as assignee_canonical, COALESCE(requester_type, '') as requester_type, COALESCE(assignee_type, '') as assignee_type
FROM v_messages WHERE id IN (/*SLICE:ids*/?)
`

type GetMessagesByIDsRow struct {
	ID                  int64        `json:"id"`
	UserEmail           string       `json:"user_email"`
	Source              string       `json:"source"`
	Room                string       `json:"room"`
	Task                string       `json:"task"`
	Requester           string       `json:"requester"`
	Assignee            string       `json:"assignee"`
	AssignedAt          sql.NullTime `json:"assigned_at"`
	Link                string       `json:"link"`
	SourceTs            string       `json:"source_ts"`
	OriginalText        string       `json:"original_text"`
	Done                bool         `json:"done"`
	IsDeleted           bool         `json:"is_deleted"`
	CreatedAt           sql.NullTime `json:"created_at"`
	CompletedAt         sql.NullTime `json:"completed_at"`
	Category            string       `json:"category"`
	Deadline            string       `json:"deadline"`
	ThreadID            string       `json:"thread_id"`
	AssigneeReason      string       `json:"assignee_reason"`
	RepliedToID         string       `json:"replied_to_id"`
	IsContextQuery      int64        `json:"is_context_query"`
	Constraints         string       `json:"constraints"`
	Metadata            string       `json:"metadata"`
	SourceChannels      string       `json:"source_channels"`
	ConsolidatedContext string       `json:"consolidated_context"`
	Subtasks            string       `json:"subtasks"`
	RequesterCanonical  string       `json:"requester_canonical"`
	AssigneeCanonical   string       `json:"assignee_canonical"`
	RequesterType       string       `json:"requester_type"`
	AssigneeType        string       `json:"assignee_type"`
}

func (q *Queries) GetMessagesByIDs(ctx context.Context, ids []int64) ([]GetMessagesByIDsRow, error) {
	query := getMessagesByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMessagesByIDsRow
	for rows.Next() {
		var i GetMessagesByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserEmail,
			&i.Source,
			&i.Room,
			&i.Task,
			&i.Requester,
			&i.Assignee,
			&i.AssignedAt,
			&i.Link,
			&i.SourceTs,
			&i.OriginalText,
			&i.Done,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.Category,
			&i.Deadline,
			&i.ThreadID,
			&i.AssigneeReason,
			&i.RepliedToID,
			&i.IsContextQuery,
			&i.Constraints,
			&i.Metadata,
			&i.SourceChannels,
			&i.ConsolidatedContext,
			&i.Subtasks,
			&i.RequesterCanonical,
			&i.AssigneeCanonical,
			&i.RequesterType,
			&i.AssigneeType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessagesForMerge = `-- name: GetMessagesForMerge :many
SELECT id, COALESCE(task, '') as task, COALESCE(original_text, '') as original_text FROM messages WHERE id IN (/*SLICE:ids*/?) AND user_email = ?
`

type GetMessagesForMergeParams struct {
	Ids       []int64        `json:"ids"`
	UserEmail sql.NullString `json:"user_email"`
}

type GetMessagesForMergeRow struct {
	ID           int64  `json:"id"`
	Task         string `json:"task"`
	OriginalText string `json:"original_text"`
}

func (q *Queries) GetMessagesForMerge(ctx context.Context, arg GetMessagesForMergeParams) ([]GetMessagesForMergeRow, error) {
	query := getMessagesForMerge
	var queryParams []interface{}
	if len(arg.Ids) > 0 {
		for _, v := range arg.Ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(arg.Ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.UserEmail)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMessagesForMergeRow
	for rows.Next() {
		var i GetMessagesForMergeRow
		if err := rows.Scan(&i.ID, &i.Task, &i.OriginalText); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hardDeleteMessages = `-- name: HardDeleteMessages :exec
DELETE FROM messages WHERE user_email = ? AND id IN (/*SLICE:ids*/?)
`

type HardDeleteMessagesParams struct {
	UserEmail sql.NullString `json:"user_email"`
	Ids       []int64        `json:"ids"`
}

func (q *Queries) HardDeleteMessages(ctx context.Context, arg HardDeleteMessagesParams) error {
	query := hardDeleteMessages
	var queryParams []interface{}
	queryParams = append(queryParams, arg.UserEmail)
	if len(arg.Ids) > 0 {
		for _, v := range arg.Ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(arg.Ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const isMessageProcessed = `-- name: IsMessageProcessed :one
SELECT EXISTS(SELECT 1 FROM messages WHERE user_email = ?1 AND source_ts = ?2)
`

type IsMessageProcessedParams struct {
	UserEmail sql.NullString `json:"user_email"`
	SourceTs  sql.NullString `json:"source_ts"`
}

func (q *Queries) IsMessageProcessed(ctx context.Context, arg IsMessageProcessedParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, isMessageProcessed, arg.UserEmail, arg.SourceTs)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const refreshCacheActive = `-- name: RefreshCacheActive :many
SELECT id, COALESCE(user_email, '') as user_email, COALESCE(source, '') as source, COALESCE(room, '') as room, COALESCE(task, '') as task, COALESCE(requester, '') as requester, COALESCE(assignee, '') as assignee, assigned_at, COALESCE(link, '') as link, COALESCE(source_ts, '') as source_ts, COALESCE(original_text, '') as original_text, done, is_deleted, created_at, completed_at, COALESCE(category, '') as category, COALESCE(deadline, '') as deadline, COALESCE(thread_id, '') as thread_id, COALESCE(assignee_reason, '') as assignee_reason, COALESCE(replied_to_id, '') as replied_to_id, is_context_query, COALESCE(constraints, '') as constraints, COALESCE(metadata, '') as metadata, COALESCE(source_channels, '') as source_channels, COALESCE(consolidated_context, '') as consolidated_context, COALESCE(subtasks, '[]') as subtasks, COALESCE(requester_canonical, '') as requester_canonical, COALESCE(assignee_canonical, '') as assignee_canonical, COALESCE(requester_type, '') as requester_type, COALESCE(assignee_type, '') as assignee_type
FROM v_messages 
WHERE user_email = ?1 AND is_deleted = 0 AND done = 0
AND IFNULL(task, '') != ''
AND IFNULL(category, '') != 'merged'
ORDER BY created_at DESC 
LIMIT 200
`

type RefreshCacheActiveParams struct {
	UserEmail string `json:"user_email"`
}

type RefreshCacheActiveRow struct {
	ID                  int64        `json:"id"`
	UserEmail           string       `json:"user_email"`
	Source              string       `json:"source"`
	Room                string       `json:"room"`
	Task                string       `json:"task"`
	Requester           string       `json:"requester"`
	Assignee            string       `json:"assignee"`
	AssignedAt          sql.NullTime `json:"assigned_at"`
	Link                string       `json:"link"`
	SourceTs            string       `json:"source_ts"`
	OriginalText        string       `json:"original_text"`
	Done                bool         `json:"done"`
	IsDeleted           bool         `json:"is_deleted"`
	CreatedAt           sql.NullTime `json:"created_at"`
	CompletedAt         sql.NullTime `json:"completed_at"`
	Category            string       `json:"category"`
	Deadline            string       `json:"deadline"`
	ThreadID            string       `json:"thread_id"`
	AssigneeReason      string       `json:"assignee_reason"`
	RepliedToID         string       `json:"replied_to_id"`
	IsContextQuery      int64        `json:"is_context_query"`
	Constraints         string       `json:"constraints"`
	Metadata            string       `json:"metadata"`
	SourceChannels      string       `json:"source_channels"`
	ConsolidatedContext string       `json:"consolidated_context"`
	Subtasks            string       `json:"subtasks"`
	RequesterCanonical  string       `json:"requester_canonical"`
	AssigneeCanonical   string       `json:"assignee_canonical"`
	RequesterType       string       `json:"requester_type"`
	AssigneeType        string       `json:"assignee_type"`
}

func (q *Queries) RefreshCacheActive(ctx context.Context, userEmail string) ([]RefreshCacheActiveRow, error) {
	rows, err := q.db.QueryContext(ctx, refreshCacheActive, userEmail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RefreshCacheActiveRow
	for rows.Next() {
		var i RefreshCacheActiveRow
		if err := rows.Scan(
			&i.ID,
			&i.UserEmail,
			&i.Source,
			&i.Room,
			&i.Task,
			&i.Requester,
			&i.Assignee,
			&i.AssignedAt,
			&i.Link,
			&i.SourceTs,
			&i.OriginalText,
			&i.Done,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.Category,
			&i.Deadline,
			&i.ThreadID,
			&i.AssigneeReason,
			&i.RepliedToID,
			&i.IsContextQuery,
			&i.Constraints,
			&i.Metadata,
			&i.SourceChannels,
			&i.ConsolidatedContext,
			&i.Subtasks,
			&i.RequesterCanonical,
			&i.AssigneeCanonical,
			&i.RequesterType,
			&i.AssigneeType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refreshCacheArchive = `-- name: RefreshCacheArchive :many
SELECT id, COALESCE(user_email, '') as user_email, COALESCE(source, '') as source, COALESCE(room, '') as room, COALESCE(task, '') as task, COALESCE(requester, '') as requester, COALESCE(assignee, '') as assignee, assigned_at, COALESCE(link, '') as link, COALESCE(source_ts, '') as source_ts, COALESCE(original_text, '') as original_text, done, is_deleted, created_at, completed_at, COALESCE(category, '') as category, COALESCE(deadline, '') as deadline, COALESCE(thread_id, '') as thread_id, COALESCE(assignee_reason, '') as assignee_reason, COALESCE(replied_to_id, '') as replied_to_id, is_context_query, COALESCE(constraints, '') as constraints, COALESCE(metadata, '') as metadata, COALESCE(source_channels, '') as source_channels, COALESCE(consolidated_context, '') as consolidated_context, COALESCE(subtasks, '[]') as subtasks, COALESCE(requester_canonical, '') as requester_canonical, COALESCE(assignee_canonical, '') as assignee_canonical, COALESCE(requester_type, '') as requester_type, COALESCE(assignee_type, '') as assignee_type
FROM v_messages 
WHERE user_email = ?1 AND (is_deleted = 1 OR done = 1 OR category = 'merged')
AND IFNULL(task, '') != ''
ORDER BY CASE WHEN is_deleted = 1 THEN created_at ELSE completed_at END DESC
LIMIT 100
`

type RefreshCacheArchiveParams struct {
	UserEmail string `json:"user_email"`
}

type RefreshCacheArchiveRow struct {
	ID                  int64        `json:"id"`
	UserEmail           string       `json:"user_email"`
	Source              string       `json:"source"`
	Room                string       `json:"room"`
	Task                string       `json:"task"`
	Requester           string       `json:"requester"`
	Assignee            string       `json:"assignee"`
	AssignedAt          sql.NullTime `json:"assigned_at"`
	Link                string       `json:"link"`
	SourceTs            string       `json:"source_ts"`
	OriginalText        string       `json:"original_text"`
	Done                bool         `json:"done"`
	IsDeleted           bool         `json:"is_deleted"`
	CreatedAt           sql.NullTime `json:"created_at"`
	CompletedAt         sql.NullTime `json:"completed_at"`
	Category            string       `json:"category"`
	Deadline            string       `json:"deadline"`
	ThreadID            string       `json:"thread_id"`
	AssigneeReason      string       `json:"assignee_reason"`
	RepliedToID         string       `json:"replied_to_id"`
	IsContextQuery      int64        `json:"is_context_query"`
	Constraints         string       `json:"constraints"`
	Metadata            string       `json:"metadata"`
	SourceChannels      string       `json:"source_channels"`
	ConsolidatedContext string       `json:"consolidated_context"`
	Subtasks            string       `json:"subtasks"`
	RequesterCanonical  string       `json:"requester_canonical"`
	AssigneeCanonical   string       `json:"assignee_canonical"`
	RequesterType       string       `json:"requester_type"`
	AssigneeType        string       `json:"assignee_type"`
}

func (q *Queries) RefreshCacheArchive(ctx context.Context, userEmail string) ([]RefreshCacheArchiveRow, error) {
	rows, err := q.db.QueryContext(ctx, refreshCacheArchive, userEmail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RefreshCacheArchiveRow
	for rows.Next() {
		var i RefreshCacheArchiveRow
		if err := rows.Scan(
			&i.ID,
			&i.UserEmail,
			&i.Source,
			&i.Room,
			&i.Task,
			&i.Requester,
			&i.Assignee,
			&i.AssignedAt,
			&i.Link,
			&i.SourceTs,
			&i.OriginalText,
			&i.Done,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.Category,
			&i.Deadline,
			&i.ThreadID,
			&i.AssigneeReason,
			&i.RepliedToID,
			&i.IsContextQuery,
			&i.Constraints,
			&i.Metadata,
			&i.SourceChannels,
			&i.ConsolidatedContext,
			&i.Subtasks,
			&i.RequesterCanonical,
			&i.AssigneeCanonical,
			&i.RequesterType,
			&i.AssigneeType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreMessages = `-- name: RestoreMessages :exec
UPDATE messages SET is_deleted = 0, done = 0, completed_at = NULL WHERE user_email = ? AND id IN (/*SLICE:ids*/?)
`

type RestoreMessagesParams struct {
	UserEmail sql.NullString `json:"user_email"`
	Ids       []int64        `json:"ids"`
}

func (q *Queries) RestoreMessages(ctx context.Context, arg RestoreMessagesParams) error {
	query := restoreMessages
	var queryParams []interface{}
	queryParams = append(queryParams, arg.UserEmail)
	if len(arg.Ids) > 0 {
		for _, v := range arg.Ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(arg.Ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const saveMessagesBase = `-- name: SaveMessagesBase :many
INSERT INTO messages (user_email, source, room, task, requester, assignee, assigned_at, link, source_ts, original_text, category, deadline, thread_id, assignee_reason, replied_to_id, is_context_query, constraints, metadata, source_channels, consolidated_context, subtasks) 
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(user_email, source_ts) DO NOTHING
RETURNING id, source_ts, user_email
`

type SaveMessagesBaseParams struct {
	UserEmail           sql.NullString `json:"user_email"`
	Source              sql.NullString `json:"source"`
	Room                sql.NullString `json:"room"`
	Task                sql.NullString `json:"task"`
	Requester           sql.NullString `json:"requester"`
	Assignee            sql.NullString `json:"assignee"`
	AssignedAt          sql.NullTime   `json:"assigned_at"`
	Link                sql.NullString `json:"link"`
	SourceTs            sql.NullString `json:"source_ts"`
	OriginalText        sql.NullString `json:"original_text"`
	Category            sql.NullString `json:"category"`
	Deadline            sql.NullString `json:"deadline"`
	ThreadID            sql.NullString `json:"thread_id"`
	AssigneeReason      sql.NullString `json:"assignee_reason"`
	RepliedToID         sql.NullString `json:"replied_to_id"`
	IsContextQuery      sql.NullInt64  `json:"is_context_query"`
	Constraints         sql.NullString `json:"constraints"`
	Metadata            sql.NullString `json:"metadata"`
	SourceChannels      sql.NullString `json:"source_channels"`
	ConsolidatedContext sql.NullString `json:"consolidated_context"`
	Subtasks            sql.NullString `json:"subtasks"`
}

type SaveMessagesBaseRow struct {
	ID        int64          `json:"id"`
	SourceTs  sql.NullString `json:"source_ts"`
	UserEmail sql.NullString `json:"user_email"`
}

// Note: Batching with VALUES %s is not supported by sqlc directly.
// Using a single insert that can be called in a transaction.
func (q *Queries) SaveMessagesBase(ctx context.Context, arg SaveMessagesBaseParams) ([]SaveMessagesBaseRow, error) {
	rows, err := q.db.QueryContext(ctx, saveMessagesBase,
		arg.UserEmail,
		arg.Source,
		arg.Room,
		arg.Task,
		arg.Requester,
		arg.Assignee,
		arg.AssignedAt,
		arg.Link,
		arg.SourceTs,
		arg.OriginalText,
		arg.Category,
		arg.Deadline,
		arg.ThreadID,
		arg.AssigneeReason,
		arg.RepliedToID,
		arg.IsContextQuery,
		arg.Constraints,
		arg.Metadata,
		arg.SourceChannels,
		arg.ConsolidatedContext,
		arg.Subtasks,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SaveMessagesBaseRow
	for rows.Next() {
		var i SaveMessagesBaseRow
		if err := rows.Scan(&i.ID, &i.SourceTs, &i.UserEmail); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchArchivedMessages = `-- name: SearchArchivedMessages :many
SELECT id, COALESCE(user_email, '') as user_email, COALESCE(source, '') as source, COALESCE(room, '') as room, COALESCE(task, '') as task, COALESCE(requester, '') as requester, COALESCE(assignee, '') as assignee, assigned_at, COALESCE(link, '') as link, COALESCE(source_ts, '') as source_ts, COALESCE(original_text, '') as original_text, done, is_deleted, created_at, completed_at, COALESCE(category, '') as category, COALESCE(deadline, '') as deadline, COALESCE(thread_id, '') as thread_id, COALESCE(assignee_reason, '') as assignee_reason, COALESCE(replied_to_id, '') as replied_to_id, is_context_query, COALESCE(constraints, '') as constraints, COALESCE(metadata, '') as metadata, COALESCE(source_channels, '') as source_channels, COALESCE(consolidated_context, '') as consolidated_context, COALESCE(subtasks, '[]') as subtasks, COALESCE(requester_canonical, '') as requester_canonical, COALESCE(assignee_canonical, '') as assignee_canonical, COALESCE(requester_type, '') as requester_type, COALESCE(assignee_type, '') as assignee_type
FROM v_messages 
WHERE COALESCE(user_email, '') = CAST(?1 AS TEXT) AND (is_deleted = 1 OR category = 'merged' OR done = 1)
AND (task LIKE '%' || COALESCE(CAST(?2 AS TEXT), '') || '%' OR original_text LIKE '%' || COALESCE(CAST(?2 AS TEXT), '') || '%' OR requester LIKE '%' || COALESCE(CAST(?2 AS TEXT), '') || '%' OR assignee LIKE '%' || COALESCE(CAST(?2 AS TEXT), '') || '%')
AND (
    CAST(?3 AS TEXT) = 'all' OR CAST(?3 AS TEXT) = '' OR
    (CAST(?3 AS TEXT) = 'done' AND done = 1) OR
    (CAST(?3 AS TEXT) = 'canceled' AND done = 0 AND is_deleted = 1) OR
    (CAST(?3 AS TEXT) = 'merged' AND category = 'merged') OR
    (CAST(?3 AS TEXT) NOT IN ('done', 'canceled', 'merged', 'all', ''))
)
ORDER BY CASE WHEN is_deleted = 1 THEN created_at ELSE completed_at END DESC
LIMIT ?4 OFFSET ?5
`

type SearchArchivedMessagesParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
	Column3 string `json:"column_3"`
	Limit   int64  `json:"limit"`
	Offset  int64  `json:"offset"`
}

type SearchArchivedMessagesRow struct {
	ID                  int64        `json:"id"`
	UserEmail           string       `json:"user_email"`
	Source              string       `json:"source"`
	Room                string       `json:"room"`
	Task                string       `json:"task"`
	Requester           string       `json:"requester"`
	Assignee            string       `json:"assignee"`
	AssignedAt          sql.NullTime `json:"assigned_at"`
	Link                string       `json:"link"`
	SourceTs            string       `json:"source_ts"`
	OriginalText        string       `json:"original_text"`
	Done                bool         `json:"done"`
	IsDeleted           bool         `json:"is_deleted"`
	CreatedAt           sql.NullTime `json:"created_at"`
	CompletedAt         sql.NullTime `json:"completed_at"`
	Category            string       `json:"category"`
	Deadline            string       `json:"deadline"`
	ThreadID            string       `json:"thread_id"`
	AssigneeReason      string       `json:"assignee_reason"`
	RepliedToID         string       `json:"replied_to_id"`
	IsContextQuery      int64        `json:"is_context_query"`
	Constraints         string       `json:"constraints"`
	Metadata            string       `json:"metadata"`
	SourceChannels      string       `json:"source_channels"`
	ConsolidatedContext string       `json:"consolidated_context"`
	Subtasks            string       `json:"subtasks"`
	RequesterCanonical  string       `json:"requester_canonical"`
	AssigneeCanonical   string       `json:"assignee_canonical"`
	RequesterType       string       `json:"requester_type"`
	AssigneeType        string       `json:"assignee_type"`
}

func (q *Queries) SearchArchivedMessages(ctx context.Context, arg SearchArchivedMessagesParams) ([]SearchArchivedMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, searchArchivedMessages,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchArchivedMessagesRow
	for rows.Next() {
		var i SearchArchivedMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserEmail,
			&i.Source,
			&i.Room,
			&i.Task,
			&i.Requester,
			&i.Assignee,
			&i.AssignedAt,
			&i.Link,
			&i.SourceTs,
			&i.OriginalText,
			&i.Done,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.Category,
			&i.Deadline,
			&i.ThreadID,
			&i.AssigneeReason,
			&i.RepliedToID,
			&i.IsContextQuery,
			&i.Constraints,
			&i.Metadata,
			&i.SourceChannels,
			&i.ConsolidatedContext,
			&i.Subtasks,
			&i.RequesterCanonical,
			&i.AssigneeCanonical,
			&i.RequesterType,
			&i.AssigneeType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchArchivedMessagesCount = `-- name: SearchArchivedMessagesCount :one
SELECT COUNT(*) FROM messages 
WHERE COALESCE(user_email, '') = CAST(?1 AS TEXT) AND (is_deleted = 1 OR category = 'merged' OR done = 1)
AND (task LIKE '%' || COALESCE(CAST(?2 AS TEXT), '') || '%' OR original_text LIKE '%' || COALESCE(CAST(?2 AS TEXT), '') || '%' OR requester LIKE '%' || COALESCE(CAST(?2 AS TEXT), '') || '%' OR assignee LIKE '%' || COALESCE(CAST(?2 AS TEXT), '') || '%')
AND (
    CAST(?3 AS TEXT) = 'all' OR CAST(?3 AS TEXT) = '' OR
    (CAST(?3 AS TEXT) = 'done' AND done = 1) OR
    (CAST(?3 AS TEXT) = 'canceled' AND done = 0 AND is_deleted = 1) OR
    (CAST(?3 AS TEXT) = 'merged' AND category = 'merged') OR
    (CAST(?3 AS TEXT) NOT IN ('done', 'canceled', 'merged', 'all', ''))
)
`

type SearchArchivedMessagesCountParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
	Column3 string `json:"column_3"`
}

func (q *Queries) SearchArchivedMessagesCount(ctx context.Context, arg SearchArchivedMessagesCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, searchArchivedMessagesCount,
		arg.Column1,
		arg.Column2,
		arg.Column3,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateCategoryMerged = `-- name: UpdateCategoryMerged :exec
UPDATE messages SET category = 'merged' WHERE id IN (/*SLICE:ids*/?) AND user_email = ?
`

type UpdateCategoryMergedParams struct {
	Ids       []int64        `json:"ids"`
	UserEmail sql.NullString `json:"user_email"`
}

func (q *Queries) UpdateCategoryMerged(ctx context.Context, arg UpdateCategoryMergedParams) error {
	query := updateCategoryMerged
	var queryParams []interface{}
	if len(arg.Ids) > 0 {
		for _, v := range arg.Ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(arg.Ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.UserEmail)
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const updateMessageDetails = `-- name: UpdateMessageDetails :exec
UPDATE messages 
SET 
  task = COALESCE(?3, task),
  assignee = COALESCE(?4, assignee),
  requester = COALESCE(?5, requester),
  category = COALESCE(?6, category),
  done = COALESCE(?7, done),
  completed_at = COALESCE(?8, completed_at),
  source_channels = COALESCE(?9, source_channels)
WHERE id = ?1 AND user_email = ?2
`

type UpdateMessageDetailsParams struct {
	ID             int64          `json:"id"`
	UserEmail      sql.NullString `json:"user_email"`
	Task           sql.NullString `json:"task"`
	Assignee       sql.NullString `json:"assignee"`
	Requester      sql.NullString `json:"requester"`
	Category       sql.NullString `json:"category"`
	Done           sql.NullBool   `json:"done"`
	CompletedAt    sql.NullTime   `json:"completed_at"`
	SourceChannels sql.NullString `json:"source_channels"`
}

func (q *Queries) UpdateMessageDetails(ctx context.Context, arg UpdateMessageDetailsParams) error {
	_, err := q.db.ExecContext(ctx, updateMessageDetails,
		arg.ID,
		arg.UserEmail,
		arg.Task,
		arg.Assignee,
		arg.Requester,
		arg.Category,
		arg.Done,
		arg.CompletedAt,
		arg.SourceChannels,
	)
	return err
}

const updateTaskDescriptionAppend = `-- name: UpdateTaskDescriptionAppend :exec
UPDATE messages
SET task = task || char(10) || char(10) || '--- [Update: ' || ? || '] ---' || char(10) || ?
WHERE id = ? AND user_email = ? AND room = ?
`

type UpdateTaskDescriptionAppendParams struct {
	Task      sql.NullString `json:"task"`
	Task_2    sql.NullString `json:"task_2"`
	ID        int64          `json:"id"`
	UserEmail sql.NullString `json:"user_email"`
	Room      sql.NullString `json:"room"`
}

func (q *Queries) UpdateTaskDescriptionAppend(ctx context.Context, arg UpdateTaskDescriptionAppendParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskDescriptionAppend,
		arg.Task,
		arg.Task_2,
		arg.ID,
		arg.UserEmail,
		arg.Room,
	)
	return err
}

const updateTaskFullAppend = `-- name: UpdateTaskFullAppend :exec
UPDATE messages
SET task = task || char(10) || char(10) || '--- [Update: ' || ? || '] ---' || char(10) || ?,
    original_text = original_text || char(10) || char(10) || ?
WHERE id = ? AND user_email = ? AND room = ?
`

type UpdateTaskFullAppendParams struct {
	Task         sql.NullString `json:"task"`
	Task_2       sql.NullString `json:"task_2"`
	OriginalText sql.NullString `json:"original_text"`
	ID           int64          `json:"id"`
	UserEmail    sql.NullString `json:"user_email"`
	Room         sql.NullString `json:"room"`
}

func (q *Queries) UpdateTaskFullAppend(ctx context.Context, arg UpdateTaskFullAppendParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskFullAppend,
		arg.Task,
		arg.Task_2,
		arg.OriginalText,
		arg.ID,
		arg.UserEmail,
		arg.Room,
	)
	return err
}

const updateTaskMergeComplete = `-- name: UpdateTaskMergeComplete :exec
UPDATE messages
SET task = ?,
    original_text = original_text || char(10) || char(10) || ?
WHERE id = ? AND user_email = ? AND room = ?
`

type UpdateTaskMergeCompleteParams struct {
	Task         sql.NullString `json:"task"`
	OriginalText sql.NullString `json:"original_text"`
	ID           int64          `json:"id"`
	UserEmail    sql.NullString `json:"user_email"`
	Room         sql.NullString `json:"room"`
}

func (q *Queries) UpdateTaskMergeComplete(ctx context.Context, arg UpdateTaskMergeCompleteParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskMergeComplete,
		arg.Task,
		arg.OriginalText,
		arg.ID,
		arg.UserEmail,
		arg.Room,
	)
	return err
}
