// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type AiInferenceLog struct {
	ID           int64          `json:"id"`
	MessageID    sql.NullInt64  `json:"message_id"`
	Source       sql.NullString `json:"source"`
	OriginalText sql.NullString `json:"original_text"`
	RawResponse  sql.NullString `json:"raw_response"`
	CreatedAt    sql.NullTime   `json:"created_at"`
}

type Contact struct {
	ID              int64          `json:"id"`
	TenantEmail     string         `json:"tenant_email"`
	CanonicalID     string         `json:"canonical_id"`
	DisplayName     string         `json:"display_name"`
	Source          sql.NullString `json:"source"`
	MasterContactID sql.NullInt64  `json:"master_contact_id"`
	ContactType     sql.NullString `json:"contact_type"`
	CreatedAt       sql.NullTime   `json:"created_at"`
}

type ContactAlias struct {
	ID              int64         `json:"id"`
	ContactID       int64         `json:"contact_id"`
	IdentifierType  string        `json:"identifier_type"`
	IdentifierValue string        `json:"identifier_value"`
	Source          string        `json:"source"`
	TrustLevel      sql.NullInt64 `json:"trust_level"`
	CreatedAt       sql.NullTime  `json:"created_at"`
}

type GmailToken struct {
	UserEmail string       `json:"user_email"`
	TokenJson string       `json:"token_json"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type IdentityMergeCandidate struct {
	ID         int64          `json:"id"`
	ContactIDA int64          `json:"contact_id_a"`
	ContactIDB int64          `json:"contact_id_b"`
	Confidence float64        `json:"confidence"`
	Reason     sql.NullString `json:"reason"`
	Status     sql.NullString `json:"status"`
	CreatedAt  sql.NullTime   `json:"created_at"`
}

type IdentityMergeHistory struct {
	ID              int64        `json:"id"`
	SourceContactID int64        `json:"source_contact_id"`
	TargetContactID int64        `json:"target_contact_id"`
	Reason          string       `json:"reason"`
	MergedAt        sql.NullTime `json:"merged_at"`
}

type Message struct {
	ID                  int64          `json:"id"`
	UserEmail           sql.NullString `json:"user_email"`
	Source              sql.NullString `json:"source"`
	Room                sql.NullString `json:"room"`
	Task                sql.NullString `json:"task"`
	Requester           sql.NullString `json:"requester"`
	Assignee            sql.NullString `json:"assignee"`
	AssignedAt          sql.NullTime   `json:"assigned_at"`
	Link                sql.NullString `json:"link"`
	SourceTs            sql.NullString `json:"source_ts"`
	Pinned              sql.NullBool   `json:"pinned"`
	OriginalText        sql.NullString `json:"original_text"`
	Done                sql.NullBool   `json:"done"`
	IsDeleted           sql.NullBool   `json:"is_deleted"`
	CreatedAt           sql.NullTime   `json:"created_at"`
	CompletedAt         sql.NullTime   `json:"completed_at"`
	Category            sql.NullString `json:"category"`
	Deadline            sql.NullString `json:"deadline"`
	ThreadID            sql.NullString `json:"thread_id"`
	AssigneeReason      sql.NullString `json:"assignee_reason"`
	RepliedToID         sql.NullString `json:"replied_to_id"`
	IsContextQuery      sql.NullInt64  `json:"is_context_query"`
	Constraints         sql.NullString `json:"constraints"`
	Metadata            sql.NullString `json:"metadata"`
	SourceChannels      sql.NullString `json:"source_channels"`
	ConsolidatedContext sql.NullString `json:"consolidated_context"`
}

type PromptLog struct {
	ID        int64        `json:"id"`
	Name      string       `json:"name"`
	Version   string       `json:"version"`
	Model     string       `json:"model"`
	Status    string       `json:"status"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Report struct {
	ID            int64          `json:"id"`
	UserEmail     string         `json:"user_email"`
	StartDate     string         `json:"start_date"`
	EndDate       string         `json:"end_date"`
	Visualization string         `json:"visualization"`
	Status        sql.NullString `json:"status"`
	IsTruncated   sql.NullInt64  `json:"is_truncated"`
	CreatedAt     sql.NullTime   `json:"created_at"`
}

type ReportTranslation struct {
	ID                 int64          `json:"id"`
	ReportID           int64          `json:"report_id"`
	LanguageCode       string         `json:"language_code"`
	LanguageDeprecated sql.NullString `json:"language_deprecated"`
	Summary            string         `json:"summary"`
}

type ScanMetadatum struct {
	ID        int64          `json:"id"`
	UserEmail string         `json:"user_email"`
	Source    string         `json:"source"`
	TargetID  string         `json:"target_id"`
	LastTs    sql.NullString `json:"last_ts"`
}

type SlackThread struct {
	ChannelID      sql.NullString `json:"channel_id"`
	ThreadTs       sql.NullString `json:"thread_ts"`
	LastReplyTs    sql.NullString `json:"last_reply_ts"`
	LastActivityTs sql.NullString `json:"last_activity_ts"`
	Status         sql.NullString `json:"status"`
	UserEmail      sql.NullString `json:"user_email"`
}

type TaskTranslation struct {
	MessageID          sql.NullInt64  `json:"message_id"`
	LanguageCode       string         `json:"language_code"`
	LanguageDeprecated sql.NullString `json:"language_deprecated"`
	TranslatedText     string         `json:"translated_text"`
}

type TenantAlias struct {
	ID           int64  `json:"id"`
	UserEmail    string `json:"user_email"`
	OriginalName string `json:"original_name"`
	PrimaryName  string `json:"primary_name"`
}

type TokenUsage struct {
	ID               int64         `json:"id"`
	UserEmail        string        `json:"user_email"`
	Date             time.Time     `json:"date"`
	PromptTokens     sql.NullInt64 `json:"prompt_tokens"`
	CompletionTokens sql.NullInt64 `json:"completion_tokens"`
	TotalTokens      sql.NullInt64 `json:"total_tokens"`
	FilteredCount    sql.NullInt64 `json:"filtered_count"`
}

type User struct {
	ID        int64          `json:"id"`
	Email     sql.NullString `json:"email"`
	Name      sql.NullString `json:"name"`
	SlackID   sql.NullString `json:"slack_id"`
	WaJid     sql.NullString `json:"wa_jid"`
	Picture   sql.NullString `json:"picture"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type UserAlias struct {
	ID        int64  `json:"id"`
	UserID    int64  `json:"user_id"`
	AliasName string `json:"alias_name"`
}

type VContactsResolved struct {
	ID                   int64  `json:"id"`
	TenantEmail          string `json:"tenant_email"`
	OriginalCanonicalID  string `json:"original_canonical_id"`
	OriginalDisplayName  string `json:"original_display_name"`
	EffectiveCanonicalID string `json:"effective_canonical_id"`
	EffectiveDisplayName string `json:"effective_display_name"`
	ContactType          string `json:"contact_type"`
	IsMerged             int64  `json:"is_merged"`
	OriginalSource       string `json:"original_source"`
}

type VMessage struct {
	ID                  int64        `json:"id"`
	UserEmail           string       `json:"user_email"`
	Source              string       `json:"source"`
	Room                string       `json:"room"`
	Task                string       `json:"task"`
	Requester           string       `json:"requester"`
	Assignee            string       `json:"assignee"`
	AssignedAt          sql.NullTime `json:"assigned_at"`
	Link                string       `json:"link"`
	SourceTs            string       `json:"source_ts"`
	Pinned              bool         `json:"pinned"`
	OriginalText        string       `json:"original_text"`
	Done                bool         `json:"done"`
	IsDeleted           bool         `json:"is_deleted"`
	CreatedAt           sql.NullTime `json:"created_at"`
	CompletedAt         sql.NullTime `json:"completed_at"`
	Category            string       `json:"category"`
	Deadline            string       `json:"deadline"`
	ThreadID            string       `json:"thread_id"`
	AssigneeReason      string       `json:"assignee_reason"`
	RepliedToID         string       `json:"replied_to_id"`
	IsContextQuery      int64        `json:"is_context_query"`
	Constraints         string       `json:"constraints"`
	Metadata            string       `json:"metadata"`
	SourceChannels      string       `json:"source_channels"`
	ConsolidatedContext string       `json:"consolidated_context"`
	RequesterCanonical  string       `json:"requester_canonical"`
	AssigneeCanonical   string       `json:"assignee_canonical"`
	RequesterType       string       `json:"requester_type"`
	AssigneeType        string       `json:"assignee_type"`
}
