// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type AiInferenceLog struct {
	ID        int64          `json:"id"`
	MessageID sql.NullInt64  `json:"message_id"`
	Source    sql.NullString `json:"source"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type AppSetting struct {
	Key       string       `json:"key"`
	Value     string       `json:"value"`
	UpdatedAt sql.NullTime `json:"updated_at"`
	UpdatedBy string       `json:"updated_by"`
}

type Contact struct {
	ID              int64          `json:"id"`
	TenantEmail     string         `json:"tenant_email"`
	CanonicalID     string         `json:"canonical_id"`
	DisplayName     string         `json:"display_name"`
	Source          sql.NullString `json:"source"`
	MasterContactID sql.NullInt64  `json:"master_contact_id"`
	ContactType     sql.NullString `json:"contact_type"`
	SecondaryIds    sql.NullString `json:"secondary_ids"`
	CreatedAt       sql.NullTime   `json:"created_at"`
}

type ContactResolution struct {
	TenantEmail   string `json:"tenant_email"`
	RawIdentifier string `json:"raw_identifier"`
	ContactID     int64  `json:"contact_id"`
}

type GmailToken struct {
	UserEmail string       `json:"user_email"`
	TokenJson string       `json:"token_json"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type IdentityMergeCandidate struct {
	ID         int64          `json:"id"`
	ContactIDA int64          `json:"contact_id_a"`
	ContactIDB int64          `json:"contact_id_b"`
	Confidence float64        `json:"confidence"`
	Reason     sql.NullString `json:"reason"`
	Status     sql.NullString `json:"status"`
	CreatedAt  sql.NullTime   `json:"created_at"`
}

type IdentityMergeHistory struct {
	ID              int64        `json:"id"`
	SourceContactID int64        `json:"source_contact_id"`
	TargetContactID int64        `json:"target_contact_id"`
	Reason          string       `json:"reason"`
	MergedAt        sql.NullTime `json:"merged_at"`
}

type LineInbox struct {
	ID            int64        `json:"id"`
	LineMessageID string       `json:"line_message_id"`
	ChatType      string       `json:"chat_type"`
	ChatID        string       `json:"chat_id"`
	SenderID      string       `json:"sender_id"`
	SenderName    string       `json:"sender_name"`
	Text          string       `json:"text"`
	ReplyToID     string       `json:"reply_to_id"`
	MentionedIds  string       `json:"mentioned_ids"`
	Ts            int64        `json:"ts"`
	Processed     int64        `json:"processed"`
	CreatedAt     sql.NullTime `json:"created_at"`
}

type Message struct {
	ID                  int64          `json:"id"`
	UserEmail           sql.NullString `json:"user_email"`
	Source              sql.NullString `json:"source"`
	Room                sql.NullString `json:"room"`
	Task                sql.NullString `json:"task"`
	Requester           sql.NullString `json:"requester"`
	Assignee            sql.NullString `json:"assignee"`
	AssignedAt          sql.NullTime   `json:"assigned_at"`
	Link                sql.NullString `json:"link"`
	SourceTs            sql.NullString `json:"source_ts"`
	Pinned              sql.NullBool   `json:"pinned"`
	OriginalText        sql.NullString `json:"original_text"`
	Done                sql.NullBool   `json:"done"`
	IsDeleted           sql.NullBool   `json:"is_deleted"`
	CreatedAt           sql.NullTime   `json:"created_at"`
	UpdatedAt           sql.NullTime   `json:"updated_at"`
	CompletedAt         sql.NullTime   `json:"completed_at"`
	Category            sql.NullString `json:"category"`
	Deadline            sql.NullString `json:"deadline"`
	DeadlineDate        sql.NullTime   `json:"deadline_date"`
	DeadlineInferred    sql.NullInt64  `json:"deadline_inferred"`
	ThreadID            sql.NullString `json:"thread_id"`
	AssigneeReason      sql.NullString `json:"assignee_reason"`
	RepliedToID         sql.NullString `json:"replied_to_id"`
	IsContextQuery      sql.NullInt64  `json:"is_context_query"`
	Constraints         sql.NullString `json:"constraints"`
	Metadata            sql.NullString `json:"metadata"`
	SourceChannels      sql.NullString `json:"source_channels"`
	ConsolidatedContext sql.NullString `json:"consolidated_context"`
	Subtasks            sql.NullString `json:"subtasks"`
	IsArchived          sql.NullInt64  `json:"is_archived"`
	Lifecycle           sql.NullString `json:"lifecycle"`
}

type MessageEmbedding struct {
	MessageID int64        `json:"message_id"`
	Model     string       `json:"model"`
	Dim       int64        `json:"dim"`
	Vec       interface{}  `json:"vec"`
	TextHash  string       `json:"text_hash"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Report struct {
	ID            int64          `json:"id"`
	UserEmail     string         `json:"user_email"`
	StartDate     string         `json:"start_date"`
	EndDate       string         `json:"end_date"`
	Visualization string         `json:"visualization"`
	Status        sql.NullString `json:"status"`
	IsTruncated   sql.NullInt64  `json:"is_truncated"`
	CreatedAt     sql.NullTime   `json:"created_at"`
}

type ReportTranslation struct {
	ID                 int64          `json:"id"`
	ReportID           int64          `json:"report_id"`
	LanguageCode       string         `json:"language_code"`
	LanguageDeprecated sql.NullString `json:"language_deprecated"`
	Summary            string         `json:"summary"`
}

type ScanMetadatum struct {
	ID        int64          `json:"id"`
	UserEmail string         `json:"user_email"`
	Source    string         `json:"source"`
	TargetID  string         `json:"target_id"`
	LastTs    sql.NullString `json:"last_ts"`
}

type SlackThread struct {
	ChannelID      sql.NullString `json:"channel_id"`
	ThreadTs       sql.NullString `json:"thread_ts"`
	LastReplyTs    sql.NullString `json:"last_reply_ts"`
	LastActivityTs sql.NullString `json:"last_activity_ts"`
	Status         sql.NullString `json:"status"`
	UserEmail      sql.NullString `json:"user_email"`
}

type TaskGrant struct {
	ID            int64        `json:"id"`
	GrantorUserID int64        `json:"grantor_user_id"`
	GranteeUserID int64        `json:"grantee_user_id"`
	CreatedAt     sql.NullTime `json:"created_at"`
}

type TaskTranslation struct {
	MessageID          sql.NullInt64  `json:"message_id"`
	LanguageCode       string         `json:"language_code"`
	LanguageDeprecated sql.NullString `json:"language_deprecated"`
	TranslatedText     string         `json:"translated_text"`
}

type TelegramCredential struct {
	Email     string       `json:"email"`
	AppID     int64        `json:"app_id"`
	AppHash   string       `json:"app_hash"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type TelegramSession struct {
	Email       string       `json:"email"`
	SessionData []byte       `json:"session_data"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
}

type TenantAlias struct {
	ID           int64  `json:"id"`
	UserEmail    string `json:"user_email"`
	OriginalName string `json:"original_name"`
	PrimaryName  string `json:"primary_name"`
}

type TokenUsage struct {
	ID               int64         `json:"id"`
	UserEmail        string        `json:"user_email"`
	Date             time.Time     `json:"date"`
	Step             string        `json:"step"`
	Model            string        `json:"model"`
	Source           string        `json:"source"`
	ReportID         int64         `json:"report_id"`
	PromptTokens     sql.NullInt64 `json:"prompt_tokens"`
	CompletionTokens sql.NullInt64 `json:"completion_tokens"`
	ThinkingTokens   sql.NullInt64 `json:"thinking_tokens"`
	CachedTokens     sql.NullInt64 `json:"cached_tokens"`
	TotalTokens      sql.NullInt64 `json:"total_tokens"`
	CallCount        sql.NullInt64 `json:"call_count"`
	FilteredCount    sql.NullInt64 `json:"filtered_count"`
}

type User struct {
	ID        int64          `json:"id"`
	Email     sql.NullString `json:"email"`
	Name      sql.NullString `json:"name"`
	SlackID   sql.NullString `json:"slack_id"`
	WaJid     sql.NullString `json:"wa_jid"`
	TgUserID  sql.NullString `json:"tg_user_id"`
	Picture   sql.NullString `json:"picture"`
	IsAdmin   int64          `json:"is_admin"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type UserAlias struct {
	ID        int64  `json:"id"`
	UserID    int64  `json:"user_id"`
	AliasName string `json:"alias_name"`
}

type VContactsResolved struct {
	ID                   int64  `json:"id"`
	TenantEmail          string `json:"tenant_email"`
	OriginalCanonicalID  string `json:"original_canonical_id"`
	OriginalDisplayName  string `json:"original_display_name"`
	EffectiveCanonicalID string `json:"effective_canonical_id"`
	EffectiveDisplayName string `json:"effective_display_name"`
	ContactType          string `json:"contact_type"`
	IsMerged             int64  `json:"is_merged"`
	OriginalSource       string `json:"original_source"`
}

type VMessage struct {
	ID                  int64        `json:"id"`
	UserEmail           string       `json:"user_email"`
	Source              string       `json:"source"`
	Room                string       `json:"room"`
	Task                string       `json:"task"`
	Requester           string       `json:"requester"`
	Assignee            string       `json:"assignee"`
	AssignedAt          sql.NullTime `json:"assigned_at"`
	Link                string       `json:"link"`
	SourceTs            string       `json:"source_ts"`
	Pinned              bool         `json:"pinned"`
	OriginalText        string       `json:"original_text"`
	Done                bool         `json:"done"`
	IsDeleted           bool         `json:"is_deleted"`
	CreatedAt           sql.NullTime `json:"created_at"`
	UpdatedAt           sql.NullTime `json:"updated_at"`
	CompletedAt         sql.NullTime `json:"completed_at"`
	Category            string       `json:"category"`
	Deadline            string       `json:"deadline"`
	ThreadID            string       `json:"thread_id"`
	AssigneeReason      string       `json:"assignee_reason"`
	RepliedToID         string       `json:"replied_to_id"`
	IsContextQuery      int64        `json:"is_context_query"`
	Constraints         string       `json:"constraints"`
	Metadata            string       `json:"metadata"`
	SourceChannels      string       `json:"source_channels"`
	ConsolidatedContext string       `json:"consolidated_context"`
	Subtasks            string       `json:"subtasks"`
	Lifecycle           string       `json:"lifecycle"`
	RequesterCanonical  string       `json:"requester_canonical"`
	AssigneeCanonical   string       `json:"assignee_canonical"`
	RequesterType       string       `json:"requester_type"`
	AssigneeType        string       `json:"assignee_type"`
	DeadlineDate        sql.NullTime `json:"deadline_date"`
	DeadlineInferred    int64        `json:"deadline_inferred"`
}

type WaMessage struct {
	ID            int64  `json:"id"`
	MessageID     string `json:"message_id"`
	Email         string `json:"email"`
	ChatJid       string `json:"chat_jid"`
	ChatName      string `json:"chat_name"`
	Sender        string `json:"sender"`
	Direction     string `json:"direction"`
	Body          string `json:"body"`
	ReplyTo       string `json:"reply_to"`
	HasAttachment int64  `json:"has_attachment"`
	IsForwarded   int64  `json:"is_forwarded"`
	Mentions      string `json:"mentions"`
	Ts            int64  `json:"ts"`
	CreatedAt     string `json:"created_at"`
}
