// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: prompt_logs.sql

package db

import (
	"context"
)

const insertPromptLog = `-- name: InsertPromptLog :exec
INSERT INTO prompt_logs (name, version, model, status) VALUES (?, ?, ?, ?)
`

type InsertPromptLogParams struct {
	Name    string `json:"name"`
	Version string `json:"version"`
	Model   string `json:"model"`
	Status  string `json:"status"`
}

func (q *Queries) InsertPromptLog(ctx context.Context, arg InsertPromptLogParams) error {
	_, err := q.db.ExecContext(ctx, insertPromptLog,
		arg.Name,
		arg.Version,
		arg.Model,
		arg.Status,
	)
	return err
}
