// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	AddContactAlias(ctx context.Context, arg AddContactAliasParams) error
	ArchiveOldTasks(ctx context.Context, datetime interface{}) error
	CloseSlackThread(ctx context.Context, arg CloseSlackThreadParams) error
	CreateAIInferenceLogsTable(ctx context.Context) error
	CreateContactAliasesTable(ctx context.Context) error
	// Views
	CreateContactsResolvedView(ctx context.Context) error
	CreateContactsTable(ctx context.Context) error
	CreateGmailTokensTable(ctx context.Context) error
	CreateIdentityMergeCandidatesTable(ctx context.Context) error
	CreateIdentityMergeHistoryTable(ctx context.Context) error
	CreateMessage(ctx context.Context, arg CreateMessageParams) (int64, error)
	CreateMessagesTable(ctx context.Context) error
	CreateMessagesView(ctx context.Context) error
	CreatePromptLogsTable(ctx context.Context) error
	CreateReportTranslationsTable(ctx context.Context) error
	CreateReportsTable(ctx context.Context) error
	CreateScanMetadataTable(ctx context.Context) error
	CreateSlackThreadsTable(ctx context.Context) error
	CreateTaskTranslationsTable(ctx context.Context) error
	CreateTenantAliasesTable(ctx context.Context) error
	CreateTokenUsageTable(ctx context.Context) error
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	CreateUserAlias(ctx context.Context, arg CreateUserAliasParams) error
	CreateUserAliasesTable(ctx context.Context) error
	CreateUserReturningAll(ctx context.Context, arg CreateUserReturningAllParams) (CreateUserReturningAllRow, error)
	// Consolidated Schema for sqlc (SQLite)
	CreateUsersTable(ctx context.Context) error
	DeleteContactMapping(ctx context.Context, arg DeleteContactMappingParams) error
	DeleteGmailToken(ctx context.Context, userEmail string) error
	DeleteMessages(ctx context.Context, arg DeleteMessagesParams) error
	DeleteOldReports(ctx context.Context) error
	DeleteReport(ctx context.Context, arg DeleteReportParams) error
	DeleteScanMetadataSlackThread(ctx context.Context, arg DeleteScanMetadataSlackThreadParams) error
	DeleteTaskTranslations(ctx context.Context, messageID sql.NullInt64) error
	DeleteTenantAlias(ctx context.Context, arg DeleteTenantAliasParams) error
	DeleteUserAlias(ctx context.Context, arg DeleteUserAliasParams) error
	FlattenChildren(ctx context.Context, arg FlattenChildrenParams) error
	GetAbandonedTasks(ctx context.Context, arg GetAbandonedTasksParams) (int64, error)
	GetActiveSlackThreadsNew(ctx context.Context) ([]GetActiveSlackThreadsNewRow, error)
	GetActiveTasksForContext(ctx context.Context, arg GetActiveTasksForContextParams) ([]GetActiveTasksForContextRow, error)
	GetAliasesByValues(ctx context.Context, values []string) ([]GetAliasesByValuesRow, error)
	GetAllTenantAliases(ctx context.Context) ([]GetAllTenantAliasesRow, error)
	GetAllUserAliases(ctx context.Context) ([]GetAllUserAliasesRow, error)
	GetAllUsers(ctx context.Context) ([]GetAllUsersRow, error)
	GetCompletionHistory(ctx context.Context, arg GetCompletionHistoryParams) ([]GetCompletionHistoryRow, error)
	GetContactAliases(ctx context.Context, contactID int64) ([]GetContactAliasesRow, error)
	GetContactByID(ctx context.Context, arg GetContactByIDParams) (GetContactByIDRow, error)
	GetContactByIdentifier(ctx context.Context, arg GetContactByIdentifierParams) ([]GetContactByIdentifierRow, error)
	GetContactsByTenant(ctx context.Context, tenantEmail string) ([]GetContactsByTenantRow, error)
	GetContactsWithMaster(ctx context.Context) ([]GetContactsWithMasterRow, error)
	GetDailyCompletions(ctx context.Context, arg GetDailyCompletionsParams) ([]GetDailyCompletionsRow, error)
	GetDailyFilteredCount(ctx context.Context, arg GetDailyFilteredCountParams) (interface{}, error)
	GetDailyTokenUsage(ctx context.Context, arg GetDailyTokenUsageParams) (GetDailyTokenUsageRow, error)
	GetEarlyBirdCompleted(ctx context.Context, dollar_1 string) (int64, error)
	GetEmergencyCompleted(ctx context.Context, userEmail sql.NullString) (int64, error)
	GetGmailToken(ctx context.Context, userEmail string) (string, error)
	GetHourlyActivity(ctx context.Context, arg GetHourlyActivityParams) ([]GetHourlyActivityRow, error)
	GetIncompleteByThreadID(ctx context.Context, arg GetIncompleteByThreadIDParams) ([]GetIncompleteByThreadIDRow, error)
	GetLinkedContacts(ctx context.Context, tenantEmail string) ([]GetLinkedContactsRow, error)
	GetMaxDailyCompleted(ctx context.Context, dollar_1 string) (interface{}, error)
	GetMessageByID(ctx context.Context, id int64) (GetMessageByIDRow, error)
	GetMessagesByEmail(ctx context.Context, userEmail string) ([]GetMessagesByEmailRow, error)
	GetMessagesByIDs(ctx context.Context, ids []int64) ([]GetMessagesByIDsRow, error)
	GetMessagesForMerge(ctx context.Context, arg GetMessagesForMergeParams) ([]GetMessagesForMergeRow, error)
	GetMessagesForReport(ctx context.Context, arg GetMessagesForReportParams) ([]VMessage, error)
	GetMonthlyFilteredCount(ctx context.Context, arg GetMonthlyFilteredCountParams) (interface{}, error)
	GetMonthlyTokenUsage(ctx context.Context, arg GetMonthlyTokenUsageParams) (GetMonthlyTokenUsageRow, error)
	GetPendingMe(ctx context.Context, arg GetPendingMeParams) (int64, error)
	GetPendingOthers(ctx context.Context, arg GetPendingOthersParams) (int64, error)
	GetReport(ctx context.Context, arg GetReportParams) (GetReportRow, error)
	GetReportByDate(ctx context.Context, arg GetReportByDateParams) (GetReportByDateRow, error)
	GetReportByID(ctx context.Context, arg GetReportByIDParams) (GetReportByIDRow, error)
	GetReportList(ctx context.Context, userEmail string) ([]GetReportListRow, error)
	GetReportTranslations(ctx context.Context, reportID int64) ([]GetReportTranslationsRow, error)
	GetSourceDistributionActive(ctx context.Context, userEmail string) ([]GetSourceDistributionActiveRow, error)
	GetSourceDistributionTotal(ctx context.Context, userEmail string) ([]GetSourceDistributionTotalRow, error)
	GetTaskCountByContactType(ctx context.Context, userEmail string) ([]GetTaskCountByContactTypeRow, error)
	GetTaskTranslation(ctx context.Context, arg GetTaskTranslationParams) (string, error)
	GetTaskTranslationsBatch(ctx context.Context, arg GetTaskTranslationsBatchParams) ([]GetTaskTranslationsBatchRow, error)
	GetTotalCompleted(ctx context.Context, dollar_1 string) (int64, error)
	GetUserAliases(ctx context.Context, userID int64) ([]string, error)
	GetUserAliasesByEmail(ctx context.Context, email sql.NullString) ([]string, error)
	GetUserByEmail(ctx context.Context, email sql.NullString) (GetUserByEmailRow, error)
	GetUserByEmailSimple(ctx context.Context, email sql.NullString) (string, error)
	GetUserByID(ctx context.Context, dollar_1 int64) (GetUserByIDRow, error)
	HardDeleteMessages(ctx context.Context, arg HardDeleteMessagesParams) error
	InsertAIInferenceLog(ctx context.Context, arg InsertAIInferenceLogParams) error
	InsertMergeHistory(ctx context.Context, arg InsertMergeHistoryParams) error
	InsertPromptLog(ctx context.Context, arg InsertPromptLogParams) error
	InsertReport(ctx context.Context, arg InsertReportParams) (int64, error)
	InsertReportTranslation(ctx context.Context, arg InsertReportTranslationParams) error
	IsMessageProcessed(ctx context.Context, arg IsMessageProcessedParams) (int64, error)
	ListReports(ctx context.Context, userEmail string) ([]ListReportsRow, error)
	LoadContactsAll(ctx context.Context) ([]LoadContactsAllRow, error)
	LoadContactsAllScan(ctx context.Context) ([]LoadContactsAllScanRow, error)
	LoadGmailTokensAll(ctx context.Context) ([]LoadGmailTokensAllRow, error)
	LoadScanMetadataAll(ctx context.Context) ([]LoadScanMetadataAllRow, error)
	LoadTenantAliasesAll(ctx context.Context) ([]LoadTenantAliasesAllRow, error)
	LoadUserAliasesAll(ctx context.Context) ([]LoadUserAliasesAllRow, error)
	LoadUsersAll(ctx context.Context) ([]User, error)
	MarkMessageDone(ctx context.Context, arg MarkMessageDoneParams) error
	MigrateAchievementsAddTargetValue(ctx context.Context) error
	MigrateAchievementsAddXPReward(ctx context.Context) error
	MigrateContactsAddContactType(ctx context.Context) error
	MigrateDataNormalizeCategoryPromise(ctx context.Context) error
	MigrateDataNormalizeCategoryWaiting(ctx context.Context) error
	MigrateDataNormalizeIsDeleted(ctx context.Context) error
	MigrateDataNormalizeRoom(ctx context.Context) error
	MigrateLegacyAliases(ctx context.Context) error
	MigrateMessagesAddAssigneeReason(ctx context.Context) error
	MigrateMessagesAddCategory(ctx context.Context) error
	MigrateMessagesAddCompletedAt(ctx context.Context) error
	MigrateMessagesAddConsolidatedContext(ctx context.Context) error
	MigrateMessagesAddConstraints(ctx context.Context) error
	MigrateMessagesAddDeadline(ctx context.Context) error
	MigrateMessagesAddDone(ctx context.Context) error
	MigrateMessagesAddIsContextQuery(ctx context.Context) error
	MigrateMessagesAddIsDeleted(ctx context.Context) error
	MigrateMessagesAddMetadata(ctx context.Context) error
	MigrateMessagesAddOriginalText(ctx context.Context) error
	MigrateMessagesAddPinned(ctx context.Context) error
	MigrateMessagesAddRepliedToID(ctx context.Context) error
	MigrateMessagesAddRoom(ctx context.Context) error
	MigrateMessagesAddSourceChannels(ctx context.Context) error
	MigrateMessagesAddSubtasks(ctx context.Context) error
	MigrateMessagesAddThreadID(ctx context.Context) error
	MigrateMessagesAddUserEmail(ctx context.Context) error
	MigrateReportTranslationsAddLanguageCode(ctx context.Context) error
	MigrateReportTranslationsRenameLanguage(ctx context.Context) error
	MigrateReportsAddIsTruncated(ctx context.Context) error
	MigrateReportsAddStatus(ctx context.Context) error
	MigrateTaskTranslationsAddLanguageCode(ctx context.Context) error
	MigrateTaskTranslationsRenameLanguage(ctx context.Context) error
	MigrateTokenUsageAddFilteredCount(ctx context.Context) error
	RefreshCacheActive(ctx context.Context, arg RefreshCacheActiveParams) ([]RefreshCacheActiveRow, error)
	RefreshCacheArchive(ctx context.Context, arg RefreshCacheArchiveParams) ([]RefreshCacheArchiveRow, error)
	RestoreMessages(ctx context.Context, arg RestoreMessagesParams) error
	// Note: Batching with VALUES %s is not supported by sqlc directly.
	// Using a single insert that can be called in a transaction.
	SaveMessagesBase(ctx context.Context, arg SaveMessagesBaseParams) ([]SaveMessagesBaseRow, error)
	SearchArchivedMessages(ctx context.Context, arg SearchArchivedMessagesParams) ([]SearchArchivedMessagesRow, error)
	SearchArchivedMessagesCount(ctx context.Context, arg SearchArchivedMessagesCountParams) (int64, error)
	SearchContacts(ctx context.Context, arg SearchContactsParams) ([]SearchContactsRow, error)
	UnlinkContact(ctx context.Context, arg UnlinkContactParams) error
	UpdateCategoryMerged(ctx context.Context, arg UpdateCategoryMergedParams) error
	UpdateContactLink(ctx context.Context, arg UpdateContactLinkParams) error
	UpdateContactType(ctx context.Context, arg UpdateContactTypeParams) error
	UpdateMessageCategory(ctx context.Context, arg UpdateMessageCategoryParams) error
	UpdateMessageIdentity(ctx context.Context, arg UpdateMessageIdentityParams) error
	UpdateReportStatus(ctx context.Context, arg UpdateReportStatusParams) error
	UpdateTaskAssignee(ctx context.Context, arg UpdateTaskAssigneeParams) error
	UpdateTaskDescriptionAppend(ctx context.Context, arg UpdateTaskDescriptionAppendParams) error
	UpdateTaskFullAppend(ctx context.Context, arg UpdateTaskFullAppendParams) error
	UpdateTaskMergeComplete(ctx context.Context, arg UpdateTaskMergeCompleteParams) error
	UpdateTaskSourceChannels(ctx context.Context, arg UpdateTaskSourceChannelsParams) error
	UpdateTaskText(ctx context.Context, arg UpdateTaskTextParams) error
	UpdateUserNamePicture(ctx context.Context, arg UpdateUserNamePictureParams) error
	UpdateUserSlackID(ctx context.Context, arg UpdateUserSlackIDParams) error
	UpdateUserWAJID(ctx context.Context, arg UpdateUserWAJIDParams) error
	UpsertContactMapping(ctx context.Context, arg UpsertContactMappingParams) (int64, error)
	UpsertContactMappingSimple(ctx context.Context, arg UpsertContactMappingSimpleParams) (int64, error)
	UpsertGmailToken(ctx context.Context, arg UpsertGmailTokenParams) error
	UpsertScanMetadata(ctx context.Context, arg UpsertScanMetadataParams) error
	UpsertSlackThread(ctx context.Context, arg UpsertSlackThreadParams) error
	UpsertTaskTranslation(ctx context.Context, arg UpsertTaskTranslationParams) error
	UpsertTenantAlias(ctx context.Context, arg UpsertTenantAliasParams) error
	UpsertTokenUsage(ctx context.Context, arg UpsertTokenUsageParams) error
}

var _ Querier = (*Queries)(nil)
