// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	AppendOriginalText(ctx context.Context, arg AppendOriginalTextParams) error
	AppendSecondaryID(ctx context.Context, arg AppendSecondaryIDParams) error
	ArchiveOldTasks(ctx context.Context, datetime interface{}) (int64, error)
	CloseSlackThread(ctx context.Context, arg CloseSlackThreadParams) error
	// Why: parks a long-term-unprocessed task out of tracking; done/is_deleted guard keeps
	// terminal states untouched, so lifecycle flips active -> excluded only.
	ConfirmExclusion(ctx context.Context, arg ConfirmExclusionParams) (int64, error)
	CreateAIInferenceLogsTable(ctx context.Context) error
	CreateAppSettingsTable(ctx context.Context) error
	CreateContactResolutionTable(ctx context.Context) error
	// Views
	CreateContactsResolvedView(ctx context.Context) error
	CreateContactsTable(ctx context.Context) error
	CreateGmailTokensTable(ctx context.Context) error
	CreateGrant(ctx context.Context, arg CreateGrantParams) error
	CreateIdentityMergeCandidatesTable(ctx context.Context) error
	CreateIdentityMergeHistoryTable(ctx context.Context) error
	CreateLineInboxTable(ctx context.Context) error
	CreateMessage(ctx context.Context, arg CreateMessageParams) (int64, error)
	CreateMessageEmbeddingsTable(ctx context.Context) error
	CreateMessagesTable(ctx context.Context) error
	CreateMessagesView(ctx context.Context) error
	CreateReportTranslationsTable(ctx context.Context) error
	CreateReportsTable(ctx context.Context) error
	CreateScanMetadataTable(ctx context.Context) error
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateSessionsTable(ctx context.Context) error
	CreateSlackThreadsTable(ctx context.Context) error
	CreateTaskGrantsTable(ctx context.Context) error
	CreateTaskTranslationsTable(ctx context.Context) error
	CreateTelegramCredentialsTable(ctx context.Context) error
	CreateTelegramSessionsTable(ctx context.Context) error
	CreateTenantAliasesTable(ctx context.Context) error
	CreateTokenUsageTable(ctx context.Context) error
	CreateUserAlias(ctx context.Context, arg CreateUserAliasParams) error
	CreateUserAliasesTable(ctx context.Context) error
	// Consolidated Schema for sqlc (SQLite)
	// NOTE: CREATE INDEX statements are stripped by sqlc and must be defined in createIndexes() in migrations.go.
	CreateUsersTable(ctx context.Context) error
	CreateWAMessagesTable(ctx context.Context) error
	DeleteAppSetting(ctx context.Context, key string) error
	DeleteContactMapping(ctx context.Context, arg DeleteContactMappingParams) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteGmailToken(ctx context.Context, userEmail string) error
	DeleteGrant(ctx context.Context, arg DeleteGrantParams) error
	DeleteMessages(ctx context.Context, arg DeleteMessagesParams) error
	DeleteOldReports(ctx context.Context) error
	DeleteReport(ctx context.Context, arg DeleteReportParams) error
	DeleteScanMetadataSlackThread(ctx context.Context, arg DeleteScanMetadataSlackThreadParams) error
	DeleteSession(ctx context.Context, token string) error
	DeleteTaskTranslations(ctx context.Context, messageID sql.NullInt64) error
	DeleteTelegramCredentials(ctx context.Context, email string) error
	DeleteTelegramSession(ctx context.Context, email string) error
	DeleteTenantAlias(ctx context.Context, arg DeleteTenantAliasParams) error
	DeleteUserAlias(ctx context.Context, arg DeleteUserAliasParams) error
	FindMasterContactByDisplayName(ctx context.Context, arg FindMasterContactByDisplayNameParams) ([]FindMasterContactByDisplayNameRow, error)
	FlattenContactChildren(ctx context.Context, arg FlattenContactChildrenParams) error
	GetAbandonedTasks(ctx context.Context, arg GetAbandonedTasksParams) (int64, error)
	GetActiveSlackThreadsNew(ctx context.Context) ([]GetActiveSlackThreadsNewRow, error)
	GetActiveTasksForContext(ctx context.Context, arg GetActiveTasksForContextParams) ([]GetActiveTasksForContextRow, error)
	GetAllTenantAliases(ctx context.Context) ([]GetAllTenantAliasesRow, error)
	GetAllUserAliases(ctx context.Context) ([]GetAllUserAliasesRow, error)
	GetAllUsers(ctx context.Context) ([]User, error)
	GetAppSetting(ctx context.Context, key string) (AppSetting, error)
	GetCompletionHistory(ctx context.Context, arg GetCompletionHistoryParams) ([]GetCompletionHistoryRow, error)
	GetContactByID(ctx context.Context, arg GetContactByIDParams) (GetContactByIDRow, error)
	GetContactTypeByID(ctx context.Context, arg GetContactTypeByIDParams) (sql.NullString, error)
	GetContactsByIDs(ctx context.Context, ids []int64) ([]GetContactsByIDsRow, error)
	GetContactsByTenant(ctx context.Context, tenantEmail string) ([]GetContactsByTenantRow, error)
	GetContactsByValues(ctx context.Context) ([]GetContactsByValuesRow, error)
	GetContactsWithMaster(ctx context.Context) ([]GetContactsWithMasterRow, error)
	GetDailyCompletions(ctx context.Context, arg GetDailyCompletionsParams) ([]GetDailyCompletionsRow, error)
	GetDailyFilteredCount(ctx context.Context, arg GetDailyFilteredCountParams) (interface{}, error)
	GetDailyTokenUsage(ctx context.Context, arg GetDailyTokenUsageParams) (GetDailyTokenUsageRow, error)
	GetDisplayNameByID(ctx context.Context, id int64) (string, error)
	GetEarlyBirdCompleted(ctx context.Context, dollar_1 string) (int64, error)
	GetEmergencyCompleted(ctx context.Context, userEmail sql.NullString) (int64, error)
	GetGmailToken(ctx context.Context, userEmail string) (string, error)
	GetGrant(ctx context.Context, arg GetGrantParams) (TaskGrant, error)
	GetHourlyActivity(ctx context.Context, arg GetHourlyActivityParams) ([]GetHourlyActivityRow, error)
	GetIncompleteByThreadID(ctx context.Context, arg GetIncompleteByThreadIDParams) ([]GetIncompleteByThreadIDRow, error)
	GetLatestThreadAssignee(ctx context.Context, arg GetLatestThreadAssigneeParams) (string, error)
	GetLinkedContacts(ctx context.Context, tenantEmail string) ([]GetLinkedContactsRow, error)
	GetMasterAndTypeByID(ctx context.Context, arg GetMasterAndTypeByIDParams) (GetMasterAndTypeByIDRow, error)
	GetMaxDailyCompleted(ctx context.Context, dollar_1 string) (interface{}, error)
	GetMessageByID(ctx context.Context, id int64) (GetMessageByIDRow, error)
	GetMessagesByEmail(ctx context.Context, userEmail string) ([]GetMessagesByEmailRow, error)
	GetMessagesByIDs(ctx context.Context, ids []int64) ([]GetMessagesByIDsRow, error)
	GetMessagesForMerge(ctx context.Context, arg GetMessagesForMergeParams) ([]GetMessagesForMergeRow, error)
	// Why: (done=0, is_deleted=1) is user-cancel; (done=1, is_deleted=1) is the 30-day
	// auto-sweep of completed tasks (still valid evidence). category=merged rows were
	// absorbed into another task; counting them inflates activity and edge weights.
	GetMessagesForReport(ctx context.Context, arg GetMessagesForReportParams) ([]GetMessagesForReportRow, error)
	GetMonthlyFilteredCount(ctx context.Context, arg GetMonthlyFilteredCountParams) (interface{}, error)
	GetMonthlyTokenUsage(ctx context.Context, arg GetMonthlyTokenUsageParams) (GetMonthlyTokenUsageRow, error)
	GetPendingMe(ctx context.Context, arg GetPendingMeParams) (int64, error)
	GetPendingOthers(ctx context.Context, arg GetPendingOthersParams) (int64, error)
	GetRecentIncompleteGmail(ctx context.Context, userEmail string) ([]VMessage, error)
	GetReport(ctx context.Context, arg GetReportParams) (GetReportRow, error)
	GetReportByDate(ctx context.Context, arg GetReportByDateParams) (GetReportByDateRow, error)
	GetReportByID(ctx context.Context, arg GetReportByIDParams) (GetReportByIDRow, error)
	GetReportList(ctx context.Context, userEmail string) ([]GetReportListRow, error)
	// Cost dashboard: prompt/completion/thinking/calls aggregated for a single report. Sums across the
	// 3 report-bound steps (ReportSummary/ReportVizData/TranslateReport) plus any future buckets.
	GetReportTokenUsage(ctx context.Context, reportID int64) (GetReportTokenUsageRow, error)
	GetReportTranslations(ctx context.Context, reportID int64) ([]GetReportTranslationsRow, error)
	GetReportTranslationsByIDs(ctx context.Context, reportIds []int64) ([]GetReportTranslationsByIDsRow, error)
	GetResolutionsByIdentifiers(ctx context.Context, arg GetResolutionsByIdentifiersParams) ([]GetResolutionsByIdentifiersRow, error)
	GetRoomActorFrequency(ctx context.Context, arg GetRoomActorFrequencyParams) ([]GetRoomActorFrequencyRow, error)
	GetSession(ctx context.Context, token string) (Session, error)
	GetSourceDistributionActive(ctx context.Context, dollar_1 string) ([]GetSourceDistributionActiveRow, error)
	GetSourceDistributionTotal(ctx context.Context, dollar_1 string) ([]GetSourceDistributionTotalRow, error)
	GetTaskCountByContactType(ctx context.Context, userEmail string) ([]GetTaskCountByContactTypeRow, error)
	GetTaskTranslation(ctx context.Context, arg GetTaskTranslationParams) (string, error)
	GetTaskTranslationsBatch(ctx context.Context, arg GetTaskTranslationsBatchParams) ([]GetTaskTranslationsBatchRow, error)
	GetTelegramCredentials(ctx context.Context, email string) (GetTelegramCredentialsRow, error)
	GetTelegramSession(ctx context.Context, email string) ([]byte, error)
	GetTenantEmailByContactID(ctx context.Context, id int64) (string, error)
	GetTokenUsageByModel(ctx context.Context, arg GetTokenUsageByModelParams) ([]GetTokenUsageByModelRow, error)
	GetTokenUsageBySource(ctx context.Context, arg GetTokenUsageBySourceParams) ([]GetTokenUsageBySourceRow, error)
	// Dashboard: per-step breakdown over a date range (inclusive start, exclusive end).
	GetTokenUsageByStep(ctx context.Context, arg GetTokenUsageByStepParams) ([]GetTokenUsageByStepRow, error)
	GetTotalCompleted(ctx context.Context, dollar_1 string) (int64, error)
	GetUnprocessedLineMessages(ctx context.Context) ([]LineInbox, error)
	GetUserAliases(ctx context.Context, userID int64) ([]string, error)
	GetUserAliasesByEmail(ctx context.Context, email sql.NullString) ([]string, error)
	GetUserByEmail(ctx context.Context, email sql.NullString) (User, error)
	GetUserByEmailSimple(ctx context.Context, email sql.NullString) (string, error)
	GetUserByID(ctx context.Context, dollar_1 int64) (User, error)
	GetUserBySlackID(ctx context.Context, slackID sql.NullString) (User, error)
	HardDeleteMessages(ctx context.Context, arg HardDeleteMessagesParams) error
	HasAnyTaskInThread(ctx context.Context, arg HasAnyTaskInThreadParams) (int64, error)
	InsertAIInferenceLog(ctx context.Context, arg InsertAIInferenceLogParams) error
	InsertLineInbox(ctx context.Context, arg InsertLineInboxParams) error
	InsertMergeHistory(ctx context.Context, arg InsertMergeHistoryParams) error
	InsertReport(ctx context.Context, arg InsertReportParams) (int64, error)
	InsertReportTranslation(ctx context.Context, arg InsertReportTranslationParams) error
	InsertWAMessage(ctx context.Context, arg InsertWAMessageParams) error
	IsMessageProcessed(ctx context.Context, arg IsMessageProcessedParams) (int64, error)
	IsSourceTSProcessed(ctx context.Context, arg IsSourceTSProcessedParams) (int64, error)
	ListAdminUsers(ctx context.Context) ([]User, error)
	ListAppSettings(ctx context.Context) ([]AppSetting, error)
	ListGranteesOf(ctx context.Context, grantorUserID int64) ([]User, error)
	ListGrantorsFor(ctx context.Context, granteeUserID int64) ([]User, error)
	ListPendingMe(ctx context.Context, arg ListPendingMeParams) ([]ListPendingMeRow, error)
	ListPendingOthers(ctx context.Context, arg ListPendingOthersParams) ([]ListPendingOthersRow, error)
	ListReports(ctx context.Context, userEmail string) ([]ListReportsRow, error)
	ListWAMessages(ctx context.Context, arg ListWAMessagesParams) ([]WaMessage, error)
	LoadContactsAll(ctx context.Context) ([]LoadContactsAllRow, error)
	LoadGmailTokensAll(ctx context.Context) ([]LoadGmailTokensAllRow, error)
	LoadScanMetadataAll(ctx context.Context) ([]LoadScanMetadataAllRow, error)
	LoadUsersAll(ctx context.Context) ([]LoadUsersAllRow, error)
	MarkLineInboxProcessed(ctx context.Context, id int64) error
	MarkSourceTSProcessed(ctx context.Context, arg MarkSourceTSProcessedParams) error
	RefreshCacheActive(ctx context.Context, userEmail sql.NullString) ([]RefreshCacheActiveRow, error)
	RefreshCacheArchive(ctx context.Context, userEmail sql.NullString) ([]RefreshCacheArchiveRow, error)
	RestoreExcluded(ctx context.Context, arg RestoreExcludedParams) (int64, error)
	// Why: restore is user activity. Reset updated_at for a fresh long-term-unprocessed
	// runway and clear exclusion markers so the scan can re-evaluate from scratch.
	RestoreMessages(ctx context.Context, arg RestoreMessagesParams) error
	// Note: Batching with VALUES %s is not supported by sqlc directly.
	// Using a single insert that can be called in a transaction.
	SaveMessagesBase(ctx context.Context, arg SaveMessagesBaseParams) ([]SaveMessagesBaseRow, error)
	SearchArchivedMessages(ctx context.Context, arg SearchArchivedMessagesParams) ([]SearchArchivedMessagesRow, error)
	SearchArchivedMessagesCount(ctx context.Context, arg SearchArchivedMessagesCountParams) (int64, error)
	SearchContacts(ctx context.Context, arg SearchContactsParams) ([]SearchContactsRow, error)
	// Why: Feeds /api/commitments. Returns PROMISE/WAITING rows for the authed user.
	// View-type filtering (mine vs waiting) done in Go after the query.
	SelectCommitments(ctx context.Context, arg SelectCommitmentsParams) ([]SelectCommitmentsRow, error)
	SelectDueSoonMessages(ctx context.Context, arg SelectDueSoonMessagesParams) ([]SelectDueSoonMessagesRow, error)
	// Why: Feeds the periodic "still parked" digest across all users.
	SelectExcludedForDigest(ctx context.Context) ([]SelectExcludedForDigestRow, error)
	// Why: Global scan feeding exclusion-candidate proposals. Mirrors the COALESCE cutoff
	// of SelectStalledRequests but crosses all users like SelectUndatedCommitments.
	SelectExclusionCandidateScan(ctx context.Context, updatedAt sql.NullTime) ([]SelectExclusionCandidateScanRow, error)
	// Why: Detects TASK rows with no recent update for stalled-request surfacing.
	// Caller passes cutoff as RFC3339 string (e.g. datetime('now','-3 days')).
	// updated_at '1970-01-01T00:00:00Z' sentinel is treated as no-update; falls back to created_at.
	SelectStalledRequests(ctx context.Context, arg SelectStalledRequestsParams) ([]SelectStalledRequestsRow, error)
	// Why: Surfaces PROMISE/WAITING items with no deadline for aging nudge dispatch.
	SelectUndatedCommitments(ctx context.Context) ([]SelectUndatedCommitmentsRow, error)
	SetUserAdmin(ctx context.Context, arg SetUserAdminParams) error
	UpdateCategoryMerged(ctx context.Context, arg UpdateCategoryMergedParams) error
	UpdateContactDetails(ctx context.Context, arg UpdateContactDetailsParams) error
	UpdateDisplayNameIfEmpty(ctx context.Context, arg UpdateDisplayNameIfEmptyParams) error
	UpdateMessageDetails(ctx context.Context, arg UpdateMessageDetailsParams) error
	UpdateMessageMetadataByID(ctx context.Context, arg UpdateMessageMetadataByIDParams) error
	UpdateReportStatus(ctx context.Context, arg UpdateReportStatusParams) error
	UpdateResolutionContactID(ctx context.Context, arg UpdateResolutionContactIDParams) error
	UpdateSubtasks(ctx context.Context, arg UpdateSubtasksParams) error
	UpdateTaskAssigneeAndAssignedAt(ctx context.Context, arg UpdateTaskAssigneeAndAssignedAtParams) error
	UpdateTaskFullAppend(ctx context.Context, arg UpdateTaskFullAppendParams) error
	UpdateTaskMergeComplete(ctx context.Context, arg UpdateTaskMergeCompleteParams) error
	UpdateUserDetails(ctx context.Context, arg UpdateUserDetailsParams) error
	UpsertAliasContact(ctx context.Context, arg UpsertAliasContactParams) (int64, error)
	UpsertAppSetting(ctx context.Context, arg UpsertAppSettingParams) error
	UpsertContactMapping(ctx context.Context, arg UpsertContactMappingParams) (int64, error)
	UpsertContactResolution(ctx context.Context, arg UpsertContactResolutionParams) error
	UpsertGmailToken(ctx context.Context, arg UpsertGmailTokenParams) error
	UpsertScanMetadata(ctx context.Context, arg UpsertScanMetadataParams) error
	UpsertSlackThread(ctx context.Context, arg UpsertSlackThreadParams) error
	UpsertTaskTranslation(ctx context.Context, arg UpsertTaskTranslationParams) error
	UpsertTelegramCredentials(ctx context.Context, arg UpsertTelegramCredentialsParams) error
	UpsertTelegramSession(ctx context.Context, arg UpsertTelegramSessionParams) error
	UpsertTenantAlias(ctx context.Context, arg UpsertTenantAliasParams) error
	UpsertTokenUsage(ctx context.Context, arg UpsertTokenUsageParams) error
	UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
