// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reports.sql

package db

import (
	"context"
	"database/sql"
)

const deleteOldReports = `-- name: DeleteOldReports :exec
DELETE FROM reports WHERE created_at < datetime('now', '-30 days')
`

func (q *Queries) DeleteOldReports(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteOldReports)
	return err
}

const deleteReport = `-- name: DeleteReport :exec
DELETE FROM reports WHERE id = ? AND user_email = ?
`

type DeleteReportParams struct {
	ID        int64  `json:"id"`
	UserEmail string `json:"user_email"`
}

func (q *Queries) DeleteReport(ctx context.Context, arg DeleteReportParams) error {
	_, err := q.db.ExecContext(ctx, deleteReport, arg.ID, arg.UserEmail)
	return err
}

const getMessagesForReport = `-- name: GetMessagesForReport :many
SELECT 
    m.id, m.user_email, m.source, m.room, 
    m.task, 
    m.requester, m.assignee, m.assigned_at, m.link, m.source_ts, m.pinned, m.original_text, m.done, m.is_deleted, m.created_at, m.completed_at, m.category, m.deadline, m.thread_id,
    m.assignee_reason, m.replied_to_id, m.is_context_query, m.constraints, m.metadata, m.source_channels, m.consolidated_context, m.subtasks, m.requester_canonical, m.assignee_canonical, m.requester_type, m.assignee_type
FROM v_messages m
WHERE m.user_email = ? 
  AND (m.created_at >= ? OR m.assigned_at >= ?)
  AND (?4 IS NULL OR m.source = ?4)
  AND (?5 IS NULL OR m.done = ?5)
ORDER BY m.created_at DESC
`

type GetMessagesForReportParams struct {
	UserEmail  string       `json:"user_email"`
	CreatedAt  sql.NullTime `json:"created_at"`
	AssignedAt sql.NullTime `json:"assigned_at"`
	Source     interface{}  `json:"source"`
	Done       interface{}  `json:"done"`
}

func (q *Queries) GetMessagesForReport(ctx context.Context, arg GetMessagesForReportParams) ([]VMessage, error) {
	rows, err := q.db.QueryContext(ctx, getMessagesForReport,
		arg.UserEmail,
		arg.CreatedAt,
		arg.AssignedAt,
		arg.Source,
		arg.Done,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VMessage
	for rows.Next() {
		var i VMessage
		if err := rows.Scan(
			&i.ID,
			&i.UserEmail,
			&i.Source,
			&i.Room,
			&i.Task,
			&i.Requester,
			&i.Assignee,
			&i.AssignedAt,
			&i.Link,
			&i.SourceTs,
			&i.Pinned,
			&i.OriginalText,
			&i.Done,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.Category,
			&i.Deadline,
			&i.ThreadID,
			&i.AssigneeReason,
			&i.RepliedToID,
			&i.IsContextQuery,
			&i.Constraints,
			&i.Metadata,
			&i.SourceChannels,
			&i.ConsolidatedContext,
			&i.Subtasks,
			&i.RequesterCanonical,
			&i.AssigneeCanonical,
			&i.RequesterType,
			&i.AssigneeType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReport = `-- name: GetReport :one
SELECT r.id, r.user_email, r.start_date, r.end_date, r.visualization, r.status, r.is_truncated, r.created_at, COALESCE(rt.summary, '') as summary
FROM reports r
LEFT JOIN report_translations rt ON r.id = rt.report_id AND rt.language_code = 'en'
WHERE r.user_email = ? AND r.start_date = ? AND r.end_date = ?
`

type GetReportParams struct {
	UserEmail string `json:"user_email"`
	StartDate string `json:"start_date"`
	EndDate   string `json:"end_date"`
}

type GetReportRow struct {
	ID            int64          `json:"id"`
	UserEmail     string         `json:"user_email"`
	StartDate     string         `json:"start_date"`
	EndDate       string         `json:"end_date"`
	Visualization string         `json:"visualization"`
	Status        sql.NullString `json:"status"`
	IsTruncated   sql.NullInt64  `json:"is_truncated"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	Summary       string         `json:"summary"`
}

func (q *Queries) GetReport(ctx context.Context, arg GetReportParams) (GetReportRow, error) {
	row := q.db.QueryRowContext(ctx, getReport, arg.UserEmail, arg.StartDate, arg.EndDate)
	var i GetReportRow
	err := row.Scan(
		&i.ID,
		&i.UserEmail,
		&i.StartDate,
		&i.EndDate,
		&i.Visualization,
		&i.Status,
		&i.IsTruncated,
		&i.CreatedAt,
		&i.Summary,
	)
	return i, err
}

const getReportByDate = `-- name: GetReportByDate :one
SELECT r.id, r.user_email, r.start_date, r.end_date, r.visualization, r.status, r.is_truncated, r.created_at, COALESCE(rt.summary, '') as summary
FROM reports r
LEFT JOIN report_translations rt ON r.id = rt.report_id AND rt.language_code = 'en'
WHERE r.user_email = ? AND r.start_date = ? AND r.end_date = ?
`

type GetReportByDateParams struct {
	UserEmail string `json:"user_email"`
	StartDate string `json:"start_date"`
	EndDate   string `json:"end_date"`
}

type GetReportByDateRow struct {
	ID            int64          `json:"id"`
	UserEmail     string         `json:"user_email"`
	StartDate     string         `json:"start_date"`
	EndDate       string         `json:"end_date"`
	Visualization string         `json:"visualization"`
	Status        sql.NullString `json:"status"`
	IsTruncated   sql.NullInt64  `json:"is_truncated"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	Summary       string         `json:"summary"`
}

func (q *Queries) GetReportByDate(ctx context.Context, arg GetReportByDateParams) (GetReportByDateRow, error) {
	row := q.db.QueryRowContext(ctx, getReportByDate, arg.UserEmail, arg.StartDate, arg.EndDate)
	var i GetReportByDateRow
	err := row.Scan(
		&i.ID,
		&i.UserEmail,
		&i.StartDate,
		&i.EndDate,
		&i.Visualization,
		&i.Status,
		&i.IsTruncated,
		&i.CreatedAt,
		&i.Summary,
	)
	return i, err
}

const getReportByID = `-- name: GetReportByID :one
SELECT r.id, r.user_email, r.start_date, r.end_date, r.visualization, r.status, r.is_truncated, r.created_at, COALESCE(rt.summary, '') as summary
FROM reports r
LEFT JOIN report_translations rt ON r.id = rt.report_id AND rt.language_code = 'en'
WHERE r.id = ? AND r.user_email = ?
`

type GetReportByIDParams struct {
	ID        int64  `json:"id"`
	UserEmail string `json:"user_email"`
}

type GetReportByIDRow struct {
	ID            int64          `json:"id"`
	UserEmail     string         `json:"user_email"`
	StartDate     string         `json:"start_date"`
	EndDate       string         `json:"end_date"`
	Visualization string         `json:"visualization"`
	Status        sql.NullString `json:"status"`
	IsTruncated   sql.NullInt64  `json:"is_truncated"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	Summary       string         `json:"summary"`
}

func (q *Queries) GetReportByID(ctx context.Context, arg GetReportByIDParams) (GetReportByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getReportByID, arg.ID, arg.UserEmail)
	var i GetReportByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserEmail,
		&i.StartDate,
		&i.EndDate,
		&i.Visualization,
		&i.Status,
		&i.IsTruncated,
		&i.CreatedAt,
		&i.Summary,
	)
	return i, err
}

const getReportList = `-- name: GetReportList :many
SELECT id, start_date, end_date, created_at, status
FROM reports
WHERE user_email = ? AND status != 'failed'
ORDER BY created_at DESC
`

type GetReportListRow struct {
	ID        int64          `json:"id"`
	StartDate string         `json:"start_date"`
	EndDate   string         `json:"end_date"`
	CreatedAt sql.NullTime   `json:"created_at"`
	Status    sql.NullString `json:"status"`
}

func (q *Queries) GetReportList(ctx context.Context, userEmail string) ([]GetReportListRow, error) {
	rows, err := q.db.QueryContext(ctx, getReportList, userEmail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReportListRow
	for rows.Next() {
		var i GetReportListRow
		if err := rows.Scan(
			&i.ID,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReportTranslations = `-- name: GetReportTranslations :many
SELECT language_code, summary
FROM report_translations
WHERE report_id = ?
`

type GetReportTranslationsRow struct {
	LanguageCode string `json:"language_code"`
	Summary      string `json:"summary"`
}

func (q *Queries) GetReportTranslations(ctx context.Context, reportID int64) ([]GetReportTranslationsRow, error) {
	rows, err := q.db.QueryContext(ctx, getReportTranslations, reportID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReportTranslationsRow
	for rows.Next() {
		var i GetReportTranslationsRow
		if err := rows.Scan(&i.LanguageCode, &i.Summary); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertReport = `-- name: InsertReport :one
INSERT INTO reports (user_email, start_date, end_date, visualization, status, is_truncated, created_at)
VALUES (?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
RETURNING id
`

type InsertReportParams struct {
	UserEmail     string         `json:"user_email"`
	StartDate     string         `json:"start_date"`
	EndDate       string         `json:"end_date"`
	Visualization string         `json:"visualization"`
	Status        sql.NullString `json:"status"`
	IsTruncated   sql.NullInt64  `json:"is_truncated"`
}

func (q *Queries) InsertReport(ctx context.Context, arg InsertReportParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertReport,
		arg.UserEmail,
		arg.StartDate,
		arg.EndDate,
		arg.Visualization,
		arg.Status,
		arg.IsTruncated,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertReportTranslation = `-- name: InsertReportTranslation :exec
INSERT INTO report_translations (report_id, language_code, summary)
VALUES (?, ?, ?)
ON CONFLICT(report_id, language_code) DO UPDATE SET summary = EXCLUDED.summary
`

type InsertReportTranslationParams struct {
	ReportID     int64  `json:"report_id"`
	LanguageCode string `json:"language_code"`
	Summary      string `json:"summary"`
}

func (q *Queries) InsertReportTranslation(ctx context.Context, arg InsertReportTranslationParams) error {
	_, err := q.db.ExecContext(ctx, insertReportTranslation, arg.ReportID, arg.LanguageCode, arg.Summary)
	return err
}

const listReports = `-- name: ListReports :many
SELECT r.id, r.start_date, r.end_date, r.created_at, r.status, r.is_truncated, COALESCE(rt.summary, '') as summary
FROM reports r
LEFT JOIN report_translations rt ON r.id = rt.report_id AND rt.language_code = 'en'
WHERE r.user_email = ? AND r.status = 'completed'
ORDER BY r.created_at DESC
`

type ListReportsRow struct {
	ID          int64          `json:"id"`
	StartDate   string         `json:"start_date"`
	EndDate     string         `json:"end_date"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	Status      sql.NullString `json:"status"`
	IsTruncated sql.NullInt64  `json:"is_truncated"`
	Summary     string         `json:"summary"`
}

func (q *Queries) ListReports(ctx context.Context, userEmail string) ([]ListReportsRow, error) {
	rows, err := q.db.QueryContext(ctx, listReports, userEmail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReportsRow
	for rows.Next() {
		var i ListReportsRow
		if err := rows.Scan(
			&i.ID,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.Status,
			&i.IsTruncated,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReportStatus = `-- name: UpdateReportStatus :exec
UPDATE reports SET status = ?, visualization = ?, is_truncated = ? WHERE id = ? AND user_email = ?
`

type UpdateReportStatusParams struct {
	Status        sql.NullString `json:"status"`
	Visualization string         `json:"visualization"`
	IsTruncated   sql.NullInt64  `json:"is_truncated"`
	ID            int64          `json:"id"`
	UserEmail     string         `json:"user_email"`
}

func (q *Queries) UpdateReportStatus(ctx context.Context, arg UpdateReportStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateReportStatus,
		arg.Status,
		arg.Visualization,
		arg.IsTruncated,
		arg.ID,
		arg.UserEmail,
	)
	return err
}
