// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scan.sql

package db

import (
	"context"
	"database/sql"
)

const deleteScanMetadataSlackThread = `-- name: DeleteScanMetadataSlackThread :exec
DELETE FROM scan_metadata 
WHERE user_email = ? AND source = 'slack_thread' AND target_id = ?
`

type DeleteScanMetadataSlackThreadParams struct {
	UserEmail string `json:"user_email"`
	TargetID  string `json:"target_id"`
}

func (q *Queries) DeleteScanMetadataSlackThread(ctx context.Context, arg DeleteScanMetadataSlackThreadParams) error {
	_, err := q.db.ExecContext(ctx, deleteScanMetadataSlackThread, arg.UserEmail, arg.TargetID)
	return err
}

const loadContactsAllScan = `-- name: LoadContactsAllScan :many
SELECT tenant_email, canonical_id, display_name FROM contacts
`

type LoadContactsAllScanRow struct {
	TenantEmail string `json:"tenant_email"`
	CanonicalID string `json:"canonical_id"`
	DisplayName string `json:"display_name"`
}

func (q *Queries) LoadContactsAllScan(ctx context.Context) ([]LoadContactsAllScanRow, error) {
	rows, err := q.db.QueryContext(ctx, loadContactsAllScan)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoadContactsAllScanRow
	for rows.Next() {
		var i LoadContactsAllScanRow
		if err := rows.Scan(&i.TenantEmail, &i.CanonicalID, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadGmailTokensAll = `-- name: LoadGmailTokensAll :many
SELECT user_email, token_json FROM gmail_tokens
`

type LoadGmailTokensAllRow struct {
	UserEmail string `json:"user_email"`
	TokenJson string `json:"token_json"`
}

func (q *Queries) LoadGmailTokensAll(ctx context.Context) ([]LoadGmailTokensAllRow, error) {
	rows, err := q.db.QueryContext(ctx, loadGmailTokensAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoadGmailTokensAllRow
	for rows.Next() {
		var i LoadGmailTokensAllRow
		if err := rows.Scan(&i.UserEmail, &i.TokenJson); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadScanMetadataAll = `-- name: LoadScanMetadataAll :many
SELECT user_email, source, target_id, last_ts FROM scan_metadata
`

type LoadScanMetadataAllRow struct {
	UserEmail string         `json:"user_email"`
	Source    string         `json:"source"`
	TargetID  string         `json:"target_id"`
	LastTs    sql.NullString `json:"last_ts"`
}

func (q *Queries) LoadScanMetadataAll(ctx context.Context) ([]LoadScanMetadataAllRow, error) {
	rows, err := q.db.QueryContext(ctx, loadScanMetadataAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoadScanMetadataAllRow
	for rows.Next() {
		var i LoadScanMetadataAllRow
		if err := rows.Scan(
			&i.UserEmail,
			&i.Source,
			&i.TargetID,
			&i.LastTs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadTenantAliasesAll = `-- name: LoadTenantAliasesAll :many
SELECT user_email, original_name, primary_name FROM tenant_aliases
`

type LoadTenantAliasesAllRow struct {
	UserEmail    string `json:"user_email"`
	OriginalName string `json:"original_name"`
	PrimaryName  string `json:"primary_name"`
}

func (q *Queries) LoadTenantAliasesAll(ctx context.Context) ([]LoadTenantAliasesAllRow, error) {
	rows, err := q.db.QueryContext(ctx, loadTenantAliasesAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoadTenantAliasesAllRow
	for rows.Next() {
		var i LoadTenantAliasesAllRow
		if err := rows.Scan(&i.UserEmail, &i.OriginalName, &i.PrimaryName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadUserAliasesAll = `-- name: LoadUserAliasesAll :many
SELECT user_id, alias_name FROM user_aliases
`

type LoadUserAliasesAllRow struct {
	UserID    int64  `json:"user_id"`
	AliasName string `json:"alias_name"`
}

func (q *Queries) LoadUserAliasesAll(ctx context.Context) ([]LoadUserAliasesAllRow, error) {
	rows, err := q.db.QueryContext(ctx, loadUserAliasesAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoadUserAliasesAllRow
	for rows.Next() {
		var i LoadUserAliasesAllRow
		if err := rows.Scan(&i.UserID, &i.AliasName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadUsersAll = `-- name: LoadUsersAll :many
SELECT id, email, name, slack_id, wa_jid, picture, created_at 
FROM users
`

func (q *Queries) LoadUsersAll(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, loadUsersAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.SlackID,
			&i.WaJid,
			&i.Picture,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertScanMetadata = `-- name: UpsertScanMetadata :exec
INSERT INTO scan_metadata (user_email, source, target_id, last_ts)
VALUES (?, ?, ?, ?)
ON CONFLICT (user_email, source, target_id)
DO UPDATE SET last_ts = EXCLUDED.last_ts
`

type UpsertScanMetadataParams struct {
	UserEmail string         `json:"user_email"`
	Source    string         `json:"source"`
	TargetID  string         `json:"target_id"`
	LastTs    sql.NullString `json:"last_ts"`
}

func (q *Queries) UpsertScanMetadata(ctx context.Context, arg UpsertScanMetadataParams) error {
	_, err := q.db.ExecContext(ctx, upsertScanMetadata,
		arg.UserEmail,
		arg.Source,
		arg.TargetID,
		arg.LastTs,
	)
	return err
}
