// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scan.sql

package db

import (
	"context"
	"database/sql"
)

const deleteScanMetadataSlackThread = `-- name: DeleteScanMetadataSlackThread :exec
DELETE FROM scan_metadata 
WHERE user_email = ? AND source = 'slack_thread' AND target_id = ?
`

type DeleteScanMetadataSlackThreadParams struct {
	UserEmail string `json:"user_email"`
	TargetID  string `json:"target_id"`
}

func (q *Queries) DeleteScanMetadataSlackThread(ctx context.Context, arg DeleteScanMetadataSlackThreadParams) error {
	_, err := q.db.ExecContext(ctx, deleteScanMetadataSlackThread, arg.UserEmail, arg.TargetID)
	return err
}

const isSourceTSProcessed = `-- name: IsSourceTSProcessed :one
SELECT EXISTS(
    SELECT 1 FROM scan_metadata 
    WHERE user_email = ? AND source = 'processed_msg' AND target_id = ?
)
`

type IsSourceTSProcessedParams struct {
	UserEmail string `json:"user_email"`
	TargetID  string `json:"target_id"`
}

func (q *Queries) IsSourceTSProcessed(ctx context.Context, arg IsSourceTSProcessedParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, isSourceTSProcessed, arg.UserEmail, arg.TargetID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const loadGmailTokensAll = `-- name: LoadGmailTokensAll :many
SELECT user_email, token_json FROM gmail_tokens
`

type LoadGmailTokensAllRow struct {
	UserEmail string `json:"user_email"`
	TokenJson string `json:"token_json"`
}

func (q *Queries) LoadGmailTokensAll(ctx context.Context) ([]LoadGmailTokensAllRow, error) {
	rows, err := q.db.QueryContext(ctx, loadGmailTokensAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoadGmailTokensAllRow
	for rows.Next() {
		var i LoadGmailTokensAllRow
		if err := rows.Scan(&i.UserEmail, &i.TokenJson); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadScanMetadataAll = `-- name: LoadScanMetadataAll :many
SELECT user_email, source, target_id, last_ts FROM scan_metadata
`

type LoadScanMetadataAllRow struct {
	UserEmail string         `json:"user_email"`
	Source    string         `json:"source"`
	TargetID  string         `json:"target_id"`
	LastTs    sql.NullString `json:"last_ts"`
}

func (q *Queries) LoadScanMetadataAll(ctx context.Context) ([]LoadScanMetadataAllRow, error) {
	rows, err := q.db.QueryContext(ctx, loadScanMetadataAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoadScanMetadataAllRow
	for rows.Next() {
		var i LoadScanMetadataAllRow
		if err := rows.Scan(
			&i.UserEmail,
			&i.Source,
			&i.TargetID,
			&i.LastTs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadUsersAll = `-- name: LoadUsersAll :many
SELECT id, email, name, slack_id, wa_jid, tg_user_id, picture, created_at
FROM users
`

type LoadUsersAllRow struct {
	ID        int64          `json:"id"`
	Email     sql.NullString `json:"email"`
	Name      sql.NullString `json:"name"`
	SlackID   sql.NullString `json:"slack_id"`
	WaJid     sql.NullString `json:"wa_jid"`
	TgUserID  sql.NullString `json:"tg_user_id"`
	Picture   sql.NullString `json:"picture"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

func (q *Queries) LoadUsersAll(ctx context.Context) ([]LoadUsersAllRow, error) {
	rows, err := q.db.QueryContext(ctx, loadUsersAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoadUsersAllRow
	for rows.Next() {
		var i LoadUsersAllRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.SlackID,
			&i.WaJid,
			&i.TgUserID,
			&i.Picture,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSourceTSProcessed = `-- name: MarkSourceTSProcessed :exec
INSERT INTO scan_metadata (user_email, source, target_id, last_ts)
VALUES (?, 'processed_msg', ?, datetime('now'))
ON CONFLICT (user_email, source, target_id) DO NOTHING
`

type MarkSourceTSProcessedParams struct {
	UserEmail string `json:"user_email"`
	TargetID  string `json:"target_id"`
}

func (q *Queries) MarkSourceTSProcessed(ctx context.Context, arg MarkSourceTSProcessedParams) error {
	_, err := q.db.ExecContext(ctx, markSourceTSProcessed, arg.UserEmail, arg.TargetID)
	return err
}

const upsertScanMetadata = `-- name: UpsertScanMetadata :exec
INSERT INTO scan_metadata (user_email, source, target_id, last_ts)
VALUES (?, ?, ?, ?)
ON CONFLICT (user_email, source, target_id)
DO UPDATE SET last_ts = EXCLUDED.last_ts
`

type UpsertScanMetadataParams struct {
	UserEmail string         `json:"user_email"`
	Source    string         `json:"source"`
	TargetID  string         `json:"target_id"`
	LastTs    sql.NullString `json:"last_ts"`
}

func (q *Queries) UpsertScanMetadata(ctx context.Context, arg UpsertScanMetadataParams) error {
	_, err := q.db.ExecContext(ctx, upsertScanMetadata,
		arg.UserEmail,
		arg.Source,
		arg.TargetID,
		arg.LastTs,
	)
	return err
}
