// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: schema.sql

package db

import (
	"context"
)

const createAIInferenceLogsTable = `-- name: CreateAIInferenceLogsTable :exec
CREATE TABLE IF NOT EXISTS ai_inference_logs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    message_id INTEGER REFERENCES messages(id),
    source TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
)
`

func (q *Queries) CreateAIInferenceLogsTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createAIInferenceLogsTable)
	return err
}

const createAppSettingsTable = `-- name: CreateAppSettingsTable :exec
CREATE TABLE IF NOT EXISTS app_settings (
    key        TEXT PRIMARY KEY,
    value      TEXT NOT NULL DEFAULT '',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_by TEXT NOT NULL DEFAULT ''
)
`

func (q *Queries) CreateAppSettingsTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createAppSettingsTable)
	return err
}

const createContactResolutionTable = `-- name: CreateContactResolutionTable :exec
CREATE TABLE IF NOT EXISTS contact_resolution (
    tenant_email TEXT NOT NULL,
    raw_identifier TEXT NOT NULL,
    contact_id   INTEGER NOT NULL REFERENCES contacts(id) ON DELETE CASCADE,
    PRIMARY KEY (tenant_email, raw_identifier)
)
`

func (q *Queries) CreateContactResolutionTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createContactResolutionTable)
	return err
}

const createContactsResolvedView = `-- name: CreateContactsResolvedView :exec
CREATE VIEW IF NOT EXISTS v_contacts_resolved AS
SELECT
    c.id,
    c.tenant_email,
    c.canonical_id AS original_canonical_id,
    c.display_name AS original_display_name,
    COALESCE(m.canonical_id, c.canonical_id) AS effective_canonical_id,
    COALESCE(m.display_name, c.display_name) AS effective_display_name,
    COALESCE(m.contact_type, c.contact_type, 'none') AS contact_type,
    CASE WHEN c.master_contact_id IS NOT NULL THEN 1 ELSE 0 END AS is_merged,
    COALESCE(c.source, 'all') AS original_source
FROM contacts c
LEFT JOIN contacts m ON c.master_contact_id = m.id AND c.tenant_email = m.tenant_email
`

// Views
func (q *Queries) CreateContactsResolvedView(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createContactsResolvedView)
	return err
}

const createContactsTable = `-- name: CreateContactsTable :exec
CREATE TABLE IF NOT EXISTS contacts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    tenant_email VARCHAR(255) NOT NULL,
    canonical_id VARCHAR(255) NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    source VARCHAR(50) DEFAULT 'all',
    master_contact_id INTEGER REFERENCES contacts(id),
    contact_type TEXT DEFAULT 'none',
    secondary_ids TEXT DEFAULT '[]',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(tenant_email, canonical_id)
)
`

func (q *Queries) CreateContactsTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createContactsTable)
	return err
}

const createGmailTokensTable = `-- name: CreateGmailTokensTable :exec
CREATE TABLE IF NOT EXISTS gmail_tokens (
    user_email TEXT PRIMARY KEY,
    token_json TEXT NOT NULL,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
)
`

func (q *Queries) CreateGmailTokensTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createGmailTokensTable)
	return err
}

const createIdentityMergeCandidatesTable = `-- name: CreateIdentityMergeCandidatesTable :exec
CREATE TABLE IF NOT EXISTS identity_merge_candidates (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    contact_id_a INTEGER NOT NULL REFERENCES contacts(id),
    contact_id_b INTEGER NOT NULL REFERENCES contacts(id),
    confidence REAL NOT NULL,
    reason TEXT,
    status TEXT DEFAULT 'pending',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(contact_id_a, contact_id_b)
)
`

func (q *Queries) CreateIdentityMergeCandidatesTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createIdentityMergeCandidatesTable)
	return err
}

const createIdentityMergeHistoryTable = `-- name: CreateIdentityMergeHistoryTable :exec
CREATE TABLE IF NOT EXISTS identity_merge_history (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    source_contact_id INTEGER NOT NULL REFERENCES contacts(id),
    target_contact_id INTEGER NOT NULL REFERENCES contacts(id),
    reason TEXT NOT NULL,
    merged_at DATETIME DEFAULT CURRENT_TIMESTAMP
)
`

func (q *Queries) CreateIdentityMergeHistoryTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createIdentityMergeHistoryTable)
	return err
}

const createLineInboxTable = `-- name: CreateLineInboxTable :exec
CREATE TABLE IF NOT EXISTS line_inbox (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    line_message_id TEXT    NOT NULL UNIQUE,
    chat_type       TEXT    NOT NULL DEFAULT 'user',
    chat_id         TEXT    NOT NULL DEFAULT '',
    sender_id       TEXT    NOT NULL DEFAULT '',
    sender_name     TEXT    NOT NULL DEFAULT '',
    text            TEXT    NOT NULL DEFAULT '',
    reply_to_id     TEXT    NOT NULL DEFAULT '',
    mentioned_ids   TEXT    NOT NULL DEFAULT '[]',
    ts              INTEGER NOT NULL DEFAULT 0,
    processed       INTEGER NOT NULL DEFAULT 0,
    created_at      DATETIME DEFAULT CURRENT_TIMESTAMP
)
`

func (q *Queries) CreateLineInboxTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createLineInboxTable)
	return err
}

const createMessageEmbeddingsTable = `-- name: CreateMessageEmbeddingsTable :exec
CREATE TABLE IF NOT EXISTS message_embeddings (
    message_id INTEGER PRIMARY KEY REFERENCES messages(id) ON DELETE CASCADE,
    model      TEXT NOT NULL,
    dim        INTEGER NOT NULL,
    vec        F32_BLOB(768) NOT NULL,
    text_hash  TEXT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
)
`

func (q *Queries) CreateMessageEmbeddingsTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createMessageEmbeddingsTable)
	return err
}

const createMessagesTable = `-- name: CreateMessagesTable :exec
CREATE TABLE IF NOT EXISTS messages (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_email TEXT,
    source TEXT,
    room TEXT,
    task TEXT,
    requester TEXT,
    assignee TEXT,
    assigned_at DATETIME,
    link TEXT,
    source_ts TEXT,
    pinned BOOLEAN DEFAULT FALSE,
    original_text TEXT,
    done BOOLEAN DEFAULT 0,
    is_deleted BOOLEAN DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    completed_at DATETIME,
    category TEXT DEFAULT 'todo',
    deadline TEXT,
    deadline_date DATE,
    deadline_inferred INTEGER DEFAULT 0,
    thread_id TEXT,
    assignee_reason TEXT,
    replied_to_id TEXT,
    is_context_query INTEGER DEFAULT 0,
    constraints TEXT DEFAULT '[]',
    metadata TEXT DEFAULT '{}',
    source_channels TEXT DEFAULT '[]',
    consolidated_context TEXT DEFAULT '[]',
    subtasks TEXT DEFAULT '[]',
    excluded_at DATETIME,
    is_archived INTEGER GENERATED ALWAYS AS (
        CASE WHEN is_deleted = 1 OR category = 'merged' OR done = 1 THEN 1 ELSE 0 END
    ) VIRTUAL,
    -- Why: collapses (done, is_deleted, category, excluded_at) into one explicit lifecycle
    -- label so callers filter by intent instead of re-deriving the boolean combo.
    -- Order matters: merged > canceled > swept > done > excluded > active.
    lifecycle TEXT GENERATED ALWAYS AS (
        CASE
            WHEN category = 'merged'             THEN 'merged'
            WHEN done = 0 AND is_deleted = 1     THEN 'canceled'
            WHEN done = 1 AND is_deleted = 1     THEN 'swept'
            WHEN done = 1                        THEN 'done'
            WHEN excluded_at IS NOT NULL         THEN 'excluded'
            ELSE 'active'
        END
    ) VIRTUAL,
    UNIQUE(user_email, source_ts)
)
`

func (q *Queries) CreateMessagesTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createMessagesTable)
	return err
}

const createMessagesView = `-- name: CreateMessagesView :exec
CREATE VIEW IF NOT EXISTS v_messages AS
SELECT
    m.id,
    COALESCE(m.user_email, '') as user_email,
    COALESCE(m.source, '') as source,
    COALESCE(m.room, '') as room,
    COALESCE(m.task, '') as task,
    COALESCE(cr_req.effective_display_name, m.requester, '') as requester,
    COALESCE(cr_asg.effective_display_name, m.assignee, '') as assignee,
    m.assigned_at,
    COALESCE(m.link, '') as link,
    COALESCE(m.source_ts, '') as source_ts,
    COALESCE(m.pinned, 0) as pinned,
    COALESCE(m.original_text, '') as original_text,
    COALESCE(m.done, 0) as done,
    COALESCE(m.is_deleted, 0) as is_deleted,
    m.created_at,
    m.updated_at,
    m.completed_at,
    COALESCE(m.category, 'todo') as category,
    COALESCE(m.deadline, '') as deadline,
    COALESCE(m.thread_id, '') as thread_id,
    COALESCE(m.assignee_reason, '') as assignee_reason,
    COALESCE(m.replied_to_id, '') as replied_to_id,
    COALESCE(m.is_context_query, 0) as is_context_query,
    COALESCE(m.constraints, '[]') as constraints,
    COALESCE(m.metadata, '{}') as metadata,
    COALESCE(m.source_channels, '[]') as source_channels,
    COALESCE(m.consolidated_context, '[]') as consolidated_context,
    COALESCE(m.subtasks, '[]') as subtasks,
    m.excluded_at,
    COALESCE(m.lifecycle, 'active') as lifecycle,
    COALESCE(cr_req.effective_canonical_id, m.requester, '') as requester_canonical,
    COALESCE(cr_asg.effective_canonical_id, m.assignee, '') as assignee_canonical,
    COALESCE(cr_req.contact_type, 'none') as requester_type,
    COALESCE(cr_asg.contact_type, 'none') as assignee_type,
    m.deadline_date,
    COALESCE(m.deadline_inferred, 0) as deadline_inferred
FROM messages m
LEFT JOIN v_contacts_resolved cr_req ON m.user_email = cr_req.tenant_email AND m.requester = cr_req.original_canonical_id
LEFT JOIN v_contacts_resolved cr_asg ON m.user_email = cr_asg.tenant_email AND m.assignee = cr_asg.original_canonical_id
`

func (q *Queries) CreateMessagesView(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createMessagesView)
	return err
}

const createReportTranslationsTable = `-- name: CreateReportTranslationsTable :exec
CREATE TABLE IF NOT EXISTS report_translations (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    report_id INTEGER NOT NULL REFERENCES reports(id) ON DELETE CASCADE,
    language_code TEXT NOT NULL,
    language_deprecated TEXT,
    summary TEXT NOT NULL,
    UNIQUE(report_id, language_code)
)
`

func (q *Queries) CreateReportTranslationsTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createReportTranslationsTable)
	return err
}

const createReportsTable = `-- name: CreateReportsTable :exec
CREATE TABLE IF NOT EXISTS reports (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_email TEXT NOT NULL,
    start_date TEXT NOT NULL,
    end_date TEXT NOT NULL,
    visualization TEXT NOT NULL,
    status TEXT DEFAULT 'completed',
    is_truncated INTEGER DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
)
`

func (q *Queries) CreateReportsTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createReportsTable)
	return err
}

const createScanMetadataTable = `-- name: CreateScanMetadataTable :exec
CREATE TABLE IF NOT EXISTS scan_metadata (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_email TEXT NOT NULL,
    source TEXT NOT NULL,
    target_id TEXT NOT NULL,
    last_ts TEXT,
    UNIQUE(user_email, source, target_id)
)
`

func (q *Queries) CreateScanMetadataTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createScanMetadataTable)
	return err
}

const createSessionsTable = `-- name: CreateSessionsTable :exec
CREATE TABLE IF NOT EXISTS sessions (
    token      TEXT PRIMARY KEY,
    email      TEXT NOT NULL,
    expires_at DATETIME NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
)
`

func (q *Queries) CreateSessionsTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createSessionsTable)
	return err
}

const createSlackThreadsTable = `-- name: CreateSlackThreadsTable :exec
CREATE TABLE IF NOT EXISTS slack_threads (
    channel_id TEXT,
    thread_ts TEXT,
    last_reply_ts TEXT,
    last_activity_ts TEXT,
    status TEXT DEFAULT 'active',
    user_email TEXT,
    PRIMARY KEY (channel_id, thread_ts, user_email)
)
`

func (q *Queries) CreateSlackThreadsTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createSlackThreadsTable)
	return err
}

const createTaskGrantsTable = `-- name: CreateTaskGrantsTable :exec
CREATE TABLE IF NOT EXISTS task_grants (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    grantor_user_id INTEGER NOT NULL REFERENCES users(id),
    grantee_user_id INTEGER NOT NULL REFERENCES users(id),
    created_at      DATETIME DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(grantor_user_id, grantee_user_id)
)
`

func (q *Queries) CreateTaskGrantsTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createTaskGrantsTable)
	return err
}

const createTaskTranslationsTable = `-- name: CreateTaskTranslationsTable :exec
CREATE TABLE IF NOT EXISTS task_translations (
    message_id INTEGER REFERENCES messages(id) ON DELETE CASCADE,
    language_code TEXT NOT NULL,
    language_deprecated TEXT,
    translated_text TEXT NOT NULL,
    PRIMARY KEY (message_id, language_code)
)
`

func (q *Queries) CreateTaskTranslationsTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createTaskTranslationsTable)
	return err
}

const createTelegramCredentialsTable = `-- name: CreateTelegramCredentialsTable :exec
CREATE TABLE IF NOT EXISTS telegram_credentials (
    email      TEXT PRIMARY KEY,
    app_id     INTEGER NOT NULL,
    app_hash   TEXT NOT NULL,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
)
`

func (q *Queries) CreateTelegramCredentialsTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createTelegramCredentialsTable)
	return err
}

const createTelegramSessionsTable = `-- name: CreateTelegramSessionsTable :exec
CREATE TABLE IF NOT EXISTS telegram_sessions (
    email        TEXT PRIMARY KEY,
    session_data BLOB NOT NULL,
    updated_at   DATETIME DEFAULT CURRENT_TIMESTAMP
)
`

func (q *Queries) CreateTelegramSessionsTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createTelegramSessionsTable)
	return err
}

const createTenantAliasesTable = `-- name: CreateTenantAliasesTable :exec
CREATE TABLE IF NOT EXISTS tenant_aliases (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_email TEXT NOT NULL,
    original_name TEXT NOT NULL,
    primary_name TEXT NOT NULL,
    UNIQUE(user_email, original_name)
)
`

func (q *Queries) CreateTenantAliasesTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createTenantAliasesTable)
	return err
}

const createTokenUsageTable = `-- name: CreateTokenUsageTable :exec
CREATE TABLE IF NOT EXISTS token_usage (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_email VARCHAR(255) NOT NULL,
    date DATE NOT NULL DEFAULT (date('now')),
    step TEXT NOT NULL DEFAULT '',
    model TEXT NOT NULL DEFAULT '',
    source TEXT NOT NULL DEFAULT '',
    report_id INTEGER NOT NULL DEFAULT 0,
    prompt_tokens INT DEFAULT 0,
    completion_tokens INT DEFAULT 0,
    thinking_tokens INT DEFAULT 0,
    cached_tokens INT DEFAULT 0,
    total_tokens INT DEFAULT 0,
    call_count INT DEFAULT 0,
    filtered_count INT DEFAULT 0,
    UNIQUE(user_email, date, step, model, source, report_id)
)
`

func (q *Queries) CreateTokenUsageTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createTokenUsageTable)
	return err
}

const createUserAliasesTable = `-- name: CreateUserAliasesTable :exec
CREATE TABLE IF NOT EXISTS user_aliases (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL REFERENCES users(id),
    alias_name TEXT NOT NULL,
    UNIQUE(user_id, alias_name)
)
`

func (q *Queries) CreateUserAliasesTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createUserAliasesTable)
	return err
}

const createUsersTable = `-- name: CreateUsersTable :exec

CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    email TEXT UNIQUE,
    name TEXT,
    slack_id TEXT,
    wa_jid TEXT,
    tg_user_id TEXT DEFAULT '',
    picture TEXT,
    is_admin INTEGER NOT NULL DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
)
`

// Consolidated Schema for sqlc (SQLite)
// NOTE: CREATE INDEX statements are stripped by sqlc and must be defined in createIndexes() in migrations.go.
func (q *Queries) CreateUsersTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createUsersTable)
	return err
}

const createWAMessagesTable = `-- name: CreateWAMessagesTable :exec
CREATE TABLE IF NOT EXISTS wa_messages (
    id             INTEGER PRIMARY KEY AUTOINCREMENT,
    message_id     TEXT    NOT NULL,
    email          TEXT    NOT NULL DEFAULT '',
    chat_jid       TEXT    NOT NULL DEFAULT '',
    chat_name      TEXT    NOT NULL DEFAULT '',
    sender         TEXT    NOT NULL DEFAULT '',
    direction      TEXT    NOT NULL DEFAULT 'incoming',
    body           TEXT    NOT NULL DEFAULT '',
    reply_to       TEXT    NOT NULL DEFAULT '',
    has_attachment INTEGER NOT NULL DEFAULT 0,
    is_forwarded   INTEGER NOT NULL DEFAULT 0,
    mentions       TEXT    NOT NULL DEFAULT '[]',
    ts             INTEGER NOT NULL DEFAULT 0,
    created_at     TEXT    NOT NULL DEFAULT (datetime('now'))
)
`

func (q *Queries) CreateWAMessagesTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createWAMessagesTable)
	return err
}
