// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: slack_threads.sql

package db

import (
	"context"
	"database/sql"
)

const closeSlackThread = `-- name: CloseSlackThread :exec
UPDATE slack_threads
SET status = 'resolved'
WHERE channel_id = ? AND thread_ts = ? AND user_email = ?
`

type CloseSlackThreadParams struct {
	ChannelID sql.NullString `json:"channel_id"`
	ThreadTs  sql.NullString `json:"thread_ts"`
	UserEmail sql.NullString `json:"user_email"`
}

func (q *Queries) CloseSlackThread(ctx context.Context, arg CloseSlackThreadParams) error {
	_, err := q.db.ExecContext(ctx, closeSlackThread, arg.ChannelID, arg.ThreadTs, arg.UserEmail)
	return err
}

const getActiveSlackThreadsNew = `-- name: GetActiveSlackThreadsNew :many
SELECT channel_id, thread_ts, last_reply_ts, last_activity_ts, user_email
FROM slack_threads
WHERE status = 'active'
`

type GetActiveSlackThreadsNewRow struct {
	ChannelID      sql.NullString `json:"channel_id"`
	ThreadTs       sql.NullString `json:"thread_ts"`
	LastReplyTs    sql.NullString `json:"last_reply_ts"`
	LastActivityTs sql.NullString `json:"last_activity_ts"`
	UserEmail      sql.NullString `json:"user_email"`
}

func (q *Queries) GetActiveSlackThreadsNew(ctx context.Context) ([]GetActiveSlackThreadsNewRow, error) {
	rows, err := q.db.QueryContext(ctx, getActiveSlackThreadsNew)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveSlackThreadsNewRow
	for rows.Next() {
		var i GetActiveSlackThreadsNewRow
		if err := rows.Scan(
			&i.ChannelID,
			&i.ThreadTs,
			&i.LastReplyTs,
			&i.LastActivityTs,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSlackThread = `-- name: UpsertSlackThread :exec
INSERT INTO slack_threads (channel_id, thread_ts, last_reply_ts, last_activity_ts, status, user_email)
VALUES (?, ?, ?, ?, 'active', ?)
ON CONFLICT(channel_id, thread_ts, user_email) DO UPDATE SET
    last_reply_ts = excluded.last_reply_ts,
    last_activity_ts = excluded.last_activity_ts,
    status = excluded.status
`

type UpsertSlackThreadParams struct {
	ChannelID      sql.NullString `json:"channel_id"`
	ThreadTs       sql.NullString `json:"thread_ts"`
	LastReplyTs    sql.NullString `json:"last_reply_ts"`
	LastActivityTs sql.NullString `json:"last_activity_ts"`
	UserEmail      sql.NullString `json:"user_email"`
}

func (q *Queries) UpsertSlackThread(ctx context.Context, arg UpsertSlackThreadParams) error {
	_, err := q.db.ExecContext(ctx, upsertSlackThread,
		arg.ChannelID,
		arg.ThreadTs,
		arg.LastReplyTs,
		arg.LastActivityTs,
		arg.UserEmail,
	)
	return err
}
