// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: slack_user_tokens.sql

package db

import (
	"context"
)

const deleteSlackUserToken = `-- name: DeleteSlackUserToken :exec
DELETE FROM slack_user_tokens WHERE user_email = ?
`

func (q *Queries) DeleteSlackUserToken(ctx context.Context, userEmail string) error {
	_, err := q.db.ExecContext(ctx, deleteSlackUserToken, userEmail)
	return err
}

const getSlackUserToken = `-- name: GetSlackUserToken :one
SELECT token_enc, slack_user_id, scopes FROM slack_user_tokens WHERE user_email = ?
`

type GetSlackUserTokenRow struct {
	TokenEnc    string `json:"token_enc"`
	SlackUserID string `json:"slack_user_id"`
	Scopes      string `json:"scopes"`
}

func (q *Queries) GetSlackUserToken(ctx context.Context, userEmail string) (GetSlackUserTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getSlackUserToken, userEmail)
	var i GetSlackUserTokenRow
	err := row.Scan(&i.TokenEnc, &i.SlackUserID, &i.Scopes)
	return i, err
}

const loadSlackUserTokensAll = `-- name: LoadSlackUserTokensAll :many
SELECT user_email, token_enc, slack_user_id, scopes FROM slack_user_tokens
`

type LoadSlackUserTokensAllRow struct {
	UserEmail   string `json:"user_email"`
	TokenEnc    string `json:"token_enc"`
	SlackUserID string `json:"slack_user_id"`
	Scopes      string `json:"scopes"`
}

func (q *Queries) LoadSlackUserTokensAll(ctx context.Context) ([]LoadSlackUserTokensAllRow, error) {
	rows, err := q.db.QueryContext(ctx, loadSlackUserTokensAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoadSlackUserTokensAllRow
	for rows.Next() {
		var i LoadSlackUserTokensAllRow
		if err := rows.Scan(
			&i.UserEmail,
			&i.TokenEnc,
			&i.SlackUserID,
			&i.Scopes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSlackUserToken = `-- name: UpsertSlackUserToken :exec
INSERT INTO slack_user_tokens (user_email, token_enc, slack_user_id, scopes, updated_at)
VALUES (?, ?, ?, ?, DATETIME('now'))
ON CONFLICT (user_email)
DO UPDATE SET token_enc = EXCLUDED.token_enc, slack_user_id = EXCLUDED.slack_user_id,
    scopes = EXCLUDED.scopes, updated_at = DATETIME('now')
`

type UpsertSlackUserTokenParams struct {
	UserEmail   string `json:"user_email"`
	TokenEnc    string `json:"token_enc"`
	SlackUserID string `json:"slack_user_id"`
	Scopes      string `json:"scopes"`
}

func (q *Queries) UpsertSlackUserToken(ctx context.Context, arg UpsertSlackUserTokenParams) error {
	_, err := q.db.ExecContext(ctx, upsertSlackUserToken,
		arg.UserEmail,
		arg.TokenEnc,
		arg.SlackUserID,
		arg.Scopes,
	)
	return err
}
