// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stats.sql

package db

import (
	"context"
	"database/sql"
)

const getAbandonedTasks = `-- name: GetAbandonedTasks :one
SELECT COUNT(*) FROM v_messages 
WHERE user_email = ? AND done = 0 AND is_deleted = 0 
AND created_at < ? AND (assignee != ? AND assignee != 'me')
AND IFNULL(task, '') != ''
`

type GetAbandonedTasksParams struct {
	UserEmail string       `json:"user_email"`
	CreatedAt sql.NullTime `json:"created_at"`
	Assignee  string       `json:"assignee"`
}

func (q *Queries) GetAbandonedTasks(ctx context.Context, arg GetAbandonedTasksParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getAbandonedTasks, arg.UserEmail, arg.CreatedAt, arg.Assignee)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCompletionHistory = `-- name: GetCompletionHistory :many
SELECT strftime('%Y-%m-%d', completed_at, ?) as c_date, source, COUNT(*) 
FROM messages 
WHERE user_email = ? AND done = 1 
AND completed_at >= datetime('now', ?, '-365 days')
GROUP BY 1, 2 ORDER BY 1 ASC
`

type GetCompletionHistoryParams struct {
	Strftime  interface{}    `json:"strftime"`
	UserEmail sql.NullString `json:"user_email"`
	Datetime  interface{}    `json:"datetime"`
}

type GetCompletionHistoryRow struct {
	CDate  interface{}    `json:"c_date"`
	Source sql.NullString `json:"source"`
	Count  int64          `json:"count"`
}

func (q *Queries) GetCompletionHistory(ctx context.Context, arg GetCompletionHistoryParams) ([]GetCompletionHistoryRow, error) {
	rows, err := q.db.QueryContext(ctx, getCompletionHistory, arg.Strftime, arg.UserEmail, arg.Datetime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCompletionHistoryRow
	for rows.Next() {
		var i GetCompletionHistoryRow
		if err := rows.Scan(&i.CDate, &i.Source, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDailyCompletions = `-- name: GetDailyCompletions :many
SELECT strftime('%Y-%m-%d', completed_at, ?) as d, COUNT(*) as c
FROM messages 
WHERE user_email = ? AND done = 1 
AND completed_at > datetime('now', ?, '-30 days')
GROUP BY 1 ORDER BY 1
`

type GetDailyCompletionsParams struct {
	Strftime  interface{}    `json:"strftime"`
	UserEmail sql.NullString `json:"user_email"`
	Datetime  interface{}    `json:"datetime"`
}

type GetDailyCompletionsRow struct {
	D interface{} `json:"d"`
	C int64       `json:"c"`
}

func (q *Queries) GetDailyCompletions(ctx context.Context, arg GetDailyCompletionsParams) ([]GetDailyCompletionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getDailyCompletions, arg.Strftime, arg.UserEmail, arg.Datetime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDailyCompletionsRow
	for rows.Next() {
		var i GetDailyCompletionsRow
		if err := rows.Scan(&i.D, &i.C); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDailyGoal = `-- name: GetDailyGoal :one
SELECT daily_goal FROM v_users WHERE email = ?1
`

func (q *Queries) GetDailyGoal(ctx context.Context, email sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, getDailyGoal, email)
	var daily_goal int64
	err := row.Scan(&daily_goal)
	return daily_goal, err
}

const getEarlyBirdCompleted = `-- name: GetEarlyBirdCompleted :one
SELECT COUNT(*) FROM messages
WHERE user_email = CAST(?1 AS TEXT) AND done = 1
AND strftime('%H', completed_at, 'localtime') < '09'
`

func (q *Queries) GetEarlyBirdCompleted(ctx context.Context, dollar_1 string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getEarlyBirdCompleted, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getEmergencyCompleted = `-- name: GetEmergencyCompleted :one
SELECT COUNT(*) FROM messages
WHERE user_email = ? AND done = 1
AND category = 'emergency'
`

func (q *Queries) GetEmergencyCompleted(ctx context.Context, userEmail sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, getEmergencyCompleted, userEmail)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getHourlyActivity = `-- name: GetHourlyActivity :many
SELECT strftime('%H', completed_at, ?) as hr, COUNT(*) as c
FROM messages 
WHERE user_email = ? AND done = 1 AND completed_at IS NOT NULL
GROUP BY 1 ORDER BY 1
`

type GetHourlyActivityParams struct {
	Strftime  interface{}    `json:"strftime"`
	UserEmail sql.NullString `json:"user_email"`
}

type GetHourlyActivityRow struct {
	Hr interface{} `json:"hr"`
	C  int64       `json:"c"`
}

func (q *Queries) GetHourlyActivity(ctx context.Context, arg GetHourlyActivityParams) ([]GetHourlyActivityRow, error) {
	rows, err := q.db.QueryContext(ctx, getHourlyActivity, arg.Strftime, arg.UserEmail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHourlyActivityRow
	for rows.Next() {
		var i GetHourlyActivityRow
		if err := rows.Scan(&i.Hr, &i.C); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMaxDailyCompleted = `-- name: GetMaxDailyCompleted :one
SELECT COALESCE(MAX(c), 0) FROM (
  SELECT COUNT(*) as c FROM messages 
  WHERE user_email = CAST(?1 AS TEXT) AND done = 1
  GROUP BY strftime('%Y-%m-%d', completed_at, 'localtime')
)
`

func (q *Queries) GetMaxDailyCompleted(ctx context.Context, dollar_1 string) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getMaxDailyCompleted, dollar_1)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const getPendingMe = `-- name: GetPendingMe :one
SELECT COUNT(*) FROM v_messages 
WHERE user_email = CAST(?1 AS TEXT) AND done = 0 AND is_deleted = 0 
AND (assignee = CAST(?2 AS TEXT) OR assignee = 'me') 
AND IFNULL(task, '') != ''
`

type GetPendingMeParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
}

func (q *Queries) GetPendingMe(ctx context.Context, arg GetPendingMeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getPendingMe, arg.Column1, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPendingOthers = `-- name: GetPendingOthers :one
SELECT COUNT(*) FROM v_messages 
WHERE user_email = ? AND done = 0 AND is_deleted = 0 
AND (assignee != ? AND assignee != 'me') 
AND IFNULL(task, '') != ''
`

type GetPendingOthersParams struct {
	UserEmail string `json:"user_email"`
	Assignee  string `json:"assignee"`
}

func (q *Queries) GetPendingOthers(ctx context.Context, arg GetPendingOthersParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getPendingOthers, arg.UserEmail, arg.Assignee)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getSourceDistributionActive = `-- name: GetSourceDistributionActive :many
SELECT source, COUNT(*) FROM v_messages 
WHERE user_email = ? AND is_deleted = 0 AND IFNULL(task, '') != ''
GROUP BY source
`

type GetSourceDistributionActiveRow struct {
	Source string `json:"source"`
	Count  int64  `json:"count"`
}

func (q *Queries) GetSourceDistributionActive(ctx context.Context, userEmail string) ([]GetSourceDistributionActiveRow, error) {
	rows, err := q.db.QueryContext(ctx, getSourceDistributionActive, userEmail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSourceDistributionActiveRow
	for rows.Next() {
		var i GetSourceDistributionActiveRow
		if err := rows.Scan(&i.Source, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSourceDistributionTotal = `-- name: GetSourceDistributionTotal :many
SELECT source, COUNT(*) FROM v_messages 
WHERE user_email = ? AND IFNULL(task, '') != ''
GROUP BY source
`

type GetSourceDistributionTotalRow struct {
	Source string `json:"source"`
	Count  int64  `json:"count"`
}

func (q *Queries) GetSourceDistributionTotal(ctx context.Context, userEmail string) ([]GetSourceDistributionTotalRow, error) {
	rows, err := q.db.QueryContext(ctx, getSourceDistributionTotal, userEmail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSourceDistributionTotalRow
	for rows.Next() {
		var i GetSourceDistributionTotalRow
		if err := rows.Scan(&i.Source, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskCountByContactType = `-- name: GetTaskCountByContactType :many
SELECT requester_type AS contact_type, COUNT(*) AS count
FROM v_messages 
WHERE user_email = ? AND is_deleted = 0 
GROUP BY requester_type
`

type GetTaskCountByContactTypeRow struct {
	ContactType string `json:"contact_type"`
	Count       int64  `json:"count"`
}

func (q *Queries) GetTaskCountByContactType(ctx context.Context, userEmail string) ([]GetTaskCountByContactTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, getTaskCountByContactType, userEmail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTaskCountByContactTypeRow
	for rows.Next() {
		var i GetTaskCountByContactTypeRow
		if err := rows.Scan(&i.ContactType, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalCompleted = `-- name: GetTotalCompleted :one
SELECT COUNT(*) FROM v_messages WHERE user_email = CAST(?1 AS TEXT) AND done = 1
`

func (q *Queries) GetTotalCompleted(ctx context.Context, dollar_1 string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTotalCompleted, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}
