// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task_grants.sql

package db

import (
	"context"
)

const createGrant = `-- name: CreateGrant :exec
INSERT OR IGNORE INTO task_grants (grantor_user_id, grantee_user_id)
VALUES (?1, ?2)
`

type CreateGrantParams struct {
	GrantorUserID int64 `json:"grantor_user_id"`
	GranteeUserID int64 `json:"grantee_user_id"`
}

func (q *Queries) CreateGrant(ctx context.Context, arg CreateGrantParams) error {
	_, err := q.db.ExecContext(ctx, createGrant, arg.GrantorUserID, arg.GranteeUserID)
	return err
}

const deleteGrant = `-- name: DeleteGrant :exec
DELETE FROM task_grants
WHERE grantor_user_id = ?1 AND grantee_user_id = ?2
`

type DeleteGrantParams struct {
	GrantorUserID int64 `json:"grantor_user_id"`
	GranteeUserID int64 `json:"grantee_user_id"`
}

func (q *Queries) DeleteGrant(ctx context.Context, arg DeleteGrantParams) error {
	_, err := q.db.ExecContext(ctx, deleteGrant, arg.GrantorUserID, arg.GranteeUserID)
	return err
}

const getGrant = `-- name: GetGrant :one
SELECT id, grantor_user_id, grantee_user_id, created_at FROM task_grants
WHERE grantor_user_id = ?1 AND grantee_user_id = ?2
`

type GetGrantParams struct {
	GrantorUserID int64 `json:"grantor_user_id"`
	GranteeUserID int64 `json:"grantee_user_id"`
}

func (q *Queries) GetGrant(ctx context.Context, arg GetGrantParams) (TaskGrant, error) {
	row := q.db.QueryRowContext(ctx, getGrant, arg.GrantorUserID, arg.GranteeUserID)
	var i TaskGrant
	err := row.Scan(
		&i.ID,
		&i.GrantorUserID,
		&i.GranteeUserID,
		&i.CreatedAt,
	)
	return i, err
}

const listGranteesOf = `-- name: ListGranteesOf :many
SELECT u.id, u.email, u.name, u.slack_id, u.wa_jid, u.tg_user_id, u.picture, u.is_admin, u.created_at
FROM users u
JOIN task_grants tg ON u.id = tg.grantee_user_id
WHERE tg.grantor_user_id = ?1
`

func (q *Queries) ListGranteesOf(ctx context.Context, grantorUserID int64) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listGranteesOf, grantorUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.SlackID,
			&i.WaJid,
			&i.TgUserID,
			&i.Picture,
			&i.IsAdmin,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGrantorsFor = `-- name: ListGrantorsFor :many
SELECT u.id, u.email, u.name, u.slack_id, u.wa_jid, u.tg_user_id, u.picture, u.is_admin, u.created_at
FROM users u
JOIN task_grants tg ON u.id = tg.grantor_user_id
WHERE tg.grantee_user_id = ?1
`

func (q *Queries) ListGrantorsFor(ctx context.Context, granteeUserID int64) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listGrantorsFor, granteeUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.SlackID,
			&i.WaJid,
			&i.TgUserID,
			&i.Picture,
			&i.IsAdmin,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
