// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: telegram.sql

package db

import (
	"context"
)

const deleteTelegramSession = `-- name: DeleteTelegramSession :exec
DELETE FROM telegram_sessions WHERE email = ?1
`

func (q *Queries) DeleteTelegramSession(ctx context.Context, email string) error {
	_, err := q.db.ExecContext(ctx, deleteTelegramSession, email)
	return err
}

const getTelegramSession = `-- name: GetTelegramSession :one
SELECT session_data FROM telegram_sessions WHERE email = ?1
`

func (q *Queries) GetTelegramSession(ctx context.Context, email string) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getTelegramSession, email)
	var session_data []byte
	err := row.Scan(&session_data)
	return session_data, err
}

const upsertTelegramSession = `-- name: UpsertTelegramSession :exec
INSERT INTO telegram_sessions (email, session_data, updated_at)
VALUES (?1, ?2, CURRENT_TIMESTAMP)
ON CONFLICT(email) DO UPDATE SET session_data = ?2, updated_at = CURRENT_TIMESTAMP
`

type UpsertTelegramSessionParams struct {
	Email       string `json:"email"`
	SessionData []byte `json:"session_data"`
}

func (q *Queries) UpsertTelegramSession(ctx context.Context, arg UpsertTelegramSessionParams) error {
	_, err := q.db.ExecContext(ctx, upsertTelegramSession, arg.Email, arg.SessionData)
	return err
}
