// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tokens.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const deleteGmailToken = `-- name: DeleteGmailToken :exec
DELETE FROM gmail_tokens WHERE user_email = ?
`

func (q *Queries) DeleteGmailToken(ctx context.Context, userEmail string) error {
	_, err := q.db.ExecContext(ctx, deleteGmailToken, userEmail)
	return err
}

const getDailyTokenUsage = `-- name: GetDailyTokenUsage :one
SELECT COALESCE(SUM(prompt_tokens), 0), COALESCE(SUM(completion_tokens), 0), COALESCE(SUM(filtered_count), 0)
FROM token_usage
WHERE user_email = ? AND date = ?
`

type GetDailyTokenUsageParams struct {
	UserEmail string    `json:"user_email"`
	Date      time.Time `json:"date"`
}

type GetDailyTokenUsageRow struct {
	Coalesce   interface{} `json:"coalesce"`
	Coalesce_2 interface{} `json:"coalesce_2"`
	Coalesce_3 interface{} `json:"coalesce_3"`
}

func (q *Queries) GetDailyTokenUsage(ctx context.Context, arg GetDailyTokenUsageParams) (GetDailyTokenUsageRow, error) {
	row := q.db.QueryRowContext(ctx, getDailyTokenUsage, arg.UserEmail, arg.Date)
	var i GetDailyTokenUsageRow
	err := row.Scan(&i.Coalesce, &i.Coalesce_2, &i.Coalesce_3)
	return i, err
}

const getGmailToken = `-- name: GetGmailToken :one
SELECT token_json FROM gmail_tokens WHERE user_email = ?
`

func (q *Queries) GetGmailToken(ctx context.Context, userEmail string) (string, error) {
	row := q.db.QueryRowContext(ctx, getGmailToken, userEmail)
	var token_json string
	err := row.Scan(&token_json)
	return token_json, err
}

const getMonthlyTokenUsage = `-- name: GetMonthlyTokenUsage :one
SELECT COALESCE(SUM(prompt_tokens), 0), COALESCE(SUM(completion_tokens), 0), COALESCE(SUM(filtered_count), 0)
FROM token_usage
WHERE user_email = ? AND date >= ? AND date < ?
`

type GetMonthlyTokenUsageParams struct {
	UserEmail string    `json:"user_email"`
	Date      time.Time `json:"date"`
	Date_2    time.Time `json:"date_2"`
}

type GetMonthlyTokenUsageRow struct {
	Coalesce   interface{} `json:"coalesce"`
	Coalesce_2 interface{} `json:"coalesce_2"`
	Coalesce_3 interface{} `json:"coalesce_3"`
}

func (q *Queries) GetMonthlyTokenUsage(ctx context.Context, arg GetMonthlyTokenUsageParams) (GetMonthlyTokenUsageRow, error) {
	row := q.db.QueryRowContext(ctx, getMonthlyTokenUsage, arg.UserEmail, arg.Date, arg.Date_2)
	var i GetMonthlyTokenUsageRow
	err := row.Scan(&i.Coalesce, &i.Coalesce_2, &i.Coalesce_3)
	return i, err
}

const getReportTokenUsage = `-- name: GetReportTokenUsage :one
SELECT COALESCE(SUM(prompt_tokens), 0)     AS prompt_tokens,
       COALESCE(SUM(completion_tokens), 0) AS completion_tokens,
       COALESCE(SUM(call_count), 0)        AS call_count
FROM token_usage
WHERE report_id = ?
`

type GetReportTokenUsageRow struct {
	PromptTokens     interface{} `json:"prompt_tokens"`
	CompletionTokens interface{} `json:"completion_tokens"`
	CallCount        interface{} `json:"call_count"`
}

// Cost dashboard: prompt/completion/calls aggregated for a single report. Sums across the
// 3 report-bound steps (ReportSummary/ReportVizData/TranslateReport) plus any future buckets.
func (q *Queries) GetReportTokenUsage(ctx context.Context, reportID int64) (GetReportTokenUsageRow, error) {
	row := q.db.QueryRowContext(ctx, getReportTokenUsage, reportID)
	var i GetReportTokenUsageRow
	err := row.Scan(&i.PromptTokens, &i.CompletionTokens, &i.CallCount)
	return i, err
}

const getTokenUsageByModel = `-- name: GetTokenUsageByModel :many
SELECT model,
       COALESCE(SUM(prompt_tokens), 0)     AS prompt_tokens,
       COALESCE(SUM(completion_tokens), 0) AS completion_tokens,
       COALESCE(SUM(call_count), 0)        AS call_count
FROM token_usage
WHERE user_email = ? AND date >= ? AND date < ?
GROUP BY model
ORDER BY prompt_tokens DESC
`

type GetTokenUsageByModelParams struct {
	UserEmail string    `json:"user_email"`
	Date      time.Time `json:"date"`
	Date_2    time.Time `json:"date_2"`
}

type GetTokenUsageByModelRow struct {
	Model            string      `json:"model"`
	PromptTokens     interface{} `json:"prompt_tokens"`
	CompletionTokens interface{} `json:"completion_tokens"`
	CallCount        interface{} `json:"call_count"`
}

func (q *Queries) GetTokenUsageByModel(ctx context.Context, arg GetTokenUsageByModelParams) ([]GetTokenUsageByModelRow, error) {
	rows, err := q.db.QueryContext(ctx, getTokenUsageByModel, arg.UserEmail, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTokenUsageByModelRow
	for rows.Next() {
		var i GetTokenUsageByModelRow
		if err := rows.Scan(
			&i.Model,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.CallCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTokenUsageBySource = `-- name: GetTokenUsageBySource :many
SELECT source,
       COALESCE(SUM(prompt_tokens), 0)     AS prompt_tokens,
       COALESCE(SUM(completion_tokens), 0) AS completion_tokens,
       COALESCE(SUM(call_count), 0)        AS call_count
FROM token_usage
WHERE user_email = ? AND date >= ? AND date < ?
GROUP BY source
ORDER BY prompt_tokens DESC
`

type GetTokenUsageBySourceParams struct {
	UserEmail string    `json:"user_email"`
	Date      time.Time `json:"date"`
	Date_2    time.Time `json:"date_2"`
}

type GetTokenUsageBySourceRow struct {
	Source           string      `json:"source"`
	PromptTokens     interface{} `json:"prompt_tokens"`
	CompletionTokens interface{} `json:"completion_tokens"`
	CallCount        interface{} `json:"call_count"`
}

func (q *Queries) GetTokenUsageBySource(ctx context.Context, arg GetTokenUsageBySourceParams) ([]GetTokenUsageBySourceRow, error) {
	rows, err := q.db.QueryContext(ctx, getTokenUsageBySource, arg.UserEmail, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTokenUsageBySourceRow
	for rows.Next() {
		var i GetTokenUsageBySourceRow
		if err := rows.Scan(
			&i.Source,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.CallCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTokenUsageByStep = `-- name: GetTokenUsageByStep :many
SELECT step,
       COALESCE(SUM(prompt_tokens), 0)     AS prompt_tokens,
       COALESCE(SUM(completion_tokens), 0) AS completion_tokens,
       COALESCE(SUM(call_count), 0)        AS call_count
FROM token_usage
WHERE user_email = ? AND date >= ? AND date < ?
GROUP BY step
ORDER BY prompt_tokens DESC
`

type GetTokenUsageByStepParams struct {
	UserEmail string    `json:"user_email"`
	Date      time.Time `json:"date"`
	Date_2    time.Time `json:"date_2"`
}

type GetTokenUsageByStepRow struct {
	Step             string      `json:"step"`
	PromptTokens     interface{} `json:"prompt_tokens"`
	CompletionTokens interface{} `json:"completion_tokens"`
	CallCount        interface{} `json:"call_count"`
}

// Dashboard: per-step breakdown over a date range (inclusive start, exclusive end).
func (q *Queries) GetTokenUsageByStep(ctx context.Context, arg GetTokenUsageByStepParams) ([]GetTokenUsageByStepRow, error) {
	rows, err := q.db.QueryContext(ctx, getTokenUsageByStep, arg.UserEmail, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTokenUsageByStepRow
	for rows.Next() {
		var i GetTokenUsageByStepRow
		if err := rows.Scan(
			&i.Step,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.CallCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertGmailToken = `-- name: UpsertGmailToken :exec
INSERT INTO gmail_tokens (user_email, token_json, updated_at)
VALUES (?, ?, DATETIME('now'))
ON CONFLICT (user_email) 
DO UPDATE SET token_json = EXCLUDED.token_json, updated_at = DATETIME('now')
`

type UpsertGmailTokenParams struct {
	UserEmail string `json:"user_email"`
	TokenJson string `json:"token_json"`
}

func (q *Queries) UpsertGmailToken(ctx context.Context, arg UpsertGmailTokenParams) error {
	_, err := q.db.ExecContext(ctx, upsertGmailToken, arg.UserEmail, arg.TokenJson)
	return err
}

const upsertTokenUsage = `-- name: UpsertTokenUsage :exec
INSERT INTO token_usage (user_email, date, step, model, source, report_id, prompt_tokens, completion_tokens, total_tokens, call_count, filtered_count)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (user_email, date, step, model, source, report_id)
DO UPDATE SET
    prompt_tokens = token_usage.prompt_tokens + EXCLUDED.prompt_tokens,
    completion_tokens = token_usage.completion_tokens + EXCLUDED.completion_tokens,
    total_tokens = token_usage.total_tokens + EXCLUDED.total_tokens,
    call_count = token_usage.call_count + EXCLUDED.call_count,
    filtered_count = token_usage.filtered_count + EXCLUDED.filtered_count
`

type UpsertTokenUsageParams struct {
	UserEmail        string        `json:"user_email"`
	Date             time.Time     `json:"date"`
	Step             string        `json:"step"`
	Model            string        `json:"model"`
	Source           string        `json:"source"`
	ReportID         int64         `json:"report_id"`
	PromptTokens     sql.NullInt64 `json:"prompt_tokens"`
	CompletionTokens sql.NullInt64 `json:"completion_tokens"`
	TotalTokens      sql.NullInt64 `json:"total_tokens"`
	CallCount        sql.NullInt64 `json:"call_count"`
	FilteredCount    sql.NullInt64 `json:"filtered_count"`
}

func (q *Queries) UpsertTokenUsage(ctx context.Context, arg UpsertTokenUsageParams) error {
	_, err := q.db.ExecContext(ctx, upsertTokenUsage,
		arg.UserEmail,
		arg.Date,
		arg.Step,
		arg.Model,
		arg.Source,
		arg.ReportID,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.TotalTokens,
		arg.CallCount,
		arg.FilteredCount,
	)
	return err
}
