// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tokens.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const deleteGmailToken = `-- name: DeleteGmailToken :exec
DELETE FROM gmail_tokens WHERE user_email = ?
`

func (q *Queries) DeleteGmailToken(ctx context.Context, userEmail string) error {
	_, err := q.db.ExecContext(ctx, deleteGmailToken, userEmail)
	return err
}

const getDailyTokenUsage = `-- name: GetDailyTokenUsage :one
SELECT COALESCE(SUM(prompt_tokens), 0), COALESCE(SUM(completion_tokens), 0) 
FROM token_usage 
WHERE user_email = ? AND date = ?
`

type GetDailyTokenUsageParams struct {
	UserEmail string    `json:"user_email"`
	Date      time.Time `json:"date"`
}

type GetDailyTokenUsageRow struct {
	Coalesce   interface{} `json:"coalesce"`
	Coalesce_2 interface{} `json:"coalesce_2"`
}

func (q *Queries) GetDailyTokenUsage(ctx context.Context, arg GetDailyTokenUsageParams) (GetDailyTokenUsageRow, error) {
	row := q.db.QueryRowContext(ctx, getDailyTokenUsage, arg.UserEmail, arg.Date)
	var i GetDailyTokenUsageRow
	err := row.Scan(&i.Coalesce, &i.Coalesce_2)
	return i, err
}

const getGmailToken = `-- name: GetGmailToken :one
SELECT token_json FROM gmail_tokens WHERE user_email = ?
`

func (q *Queries) GetGmailToken(ctx context.Context, userEmail string) (string, error) {
	row := q.db.QueryRowContext(ctx, getGmailToken, userEmail)
	var token_json string
	err := row.Scan(&token_json)
	return token_json, err
}

const getMonthlyTokenUsage = `-- name: GetMonthlyTokenUsage :one
SELECT COALESCE(SUM(prompt_tokens), 0), COALESCE(SUM(completion_tokens), 0) 
FROM token_usage 
WHERE user_email = ? AND date >= ? AND date < ?
`

type GetMonthlyTokenUsageParams struct {
	UserEmail string    `json:"user_email"`
	Date      time.Time `json:"date"`
	Date_2    time.Time `json:"date_2"`
}

type GetMonthlyTokenUsageRow struct {
	Coalesce   interface{} `json:"coalesce"`
	Coalesce_2 interface{} `json:"coalesce_2"`
}

func (q *Queries) GetMonthlyTokenUsage(ctx context.Context, arg GetMonthlyTokenUsageParams) (GetMonthlyTokenUsageRow, error) {
	row := q.db.QueryRowContext(ctx, getMonthlyTokenUsage, arg.UserEmail, arg.Date, arg.Date_2)
	var i GetMonthlyTokenUsageRow
	err := row.Scan(&i.Coalesce, &i.Coalesce_2)
	return i, err
}

const upsertGmailToken = `-- name: UpsertGmailToken :exec
INSERT INTO gmail_tokens (user_email, token_json, updated_at)
VALUES (?, ?, DATETIME('now'))
ON CONFLICT (user_email) 
DO UPDATE SET token_json = EXCLUDED.token_json, updated_at = DATETIME('now')
`

type UpsertGmailTokenParams struct {
	UserEmail string `json:"user_email"`
	TokenJson string `json:"token_json"`
}

func (q *Queries) UpsertGmailToken(ctx context.Context, arg UpsertGmailTokenParams) error {
	_, err := q.db.ExecContext(ctx, upsertGmailToken, arg.UserEmail, arg.TokenJson)
	return err
}

const upsertTokenUsage = `-- name: UpsertTokenUsage :exec
INSERT INTO token_usage (user_email, prompt_tokens, completion_tokens, total_tokens, date)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (user_email, date)
DO UPDATE SET 
    prompt_tokens = token_usage.prompt_tokens + EXCLUDED.prompt_tokens,
    completion_tokens = token_usage.completion_tokens + EXCLUDED.completion_tokens,
    total_tokens = token_usage.total_tokens + EXCLUDED.total_tokens
`

type UpsertTokenUsageParams struct {
	UserEmail        string        `json:"user_email"`
	PromptTokens     sql.NullInt64 `json:"prompt_tokens"`
	CompletionTokens sql.NullInt64 `json:"completion_tokens"`
	TotalTokens      sql.NullInt64 `json:"total_tokens"`
	Date             time.Time     `json:"date"`
}

func (q *Queries) UpsertTokenUsage(ctx context.Context, arg UpsertTokenUsageParams) error {
	_, err := q.db.ExecContext(ctx, upsertTokenUsage,
		arg.UserEmail,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.TotalTokens,
		arg.Date,
	)
	return err
}
