// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: translations.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const deleteTaskTranslations = `-- name: DeleteTaskTranslations :exec
DELETE FROM task_translations WHERE message_id = ?
`

func (q *Queries) DeleteTaskTranslations(ctx context.Context, messageID sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, deleteTaskTranslations, messageID)
	return err
}

const getTaskTranslation = `-- name: GetTaskTranslation :one
SELECT translated_text FROM task_translations WHERE message_id = ? AND language_code = ?
`

type GetTaskTranslationParams struct {
	MessageID    sql.NullInt64 `json:"message_id"`
	LanguageCode string        `json:"language_code"`
}

func (q *Queries) GetTaskTranslation(ctx context.Context, arg GetTaskTranslationParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getTaskTranslation, arg.MessageID, arg.LanguageCode)
	var translated_text string
	err := row.Scan(&translated_text)
	return translated_text, err
}

const getTaskTranslationsBatch = `-- name: GetTaskTranslationsBatch :many
SELECT message_id, translated_text FROM task_translations 
WHERE language_code = ? AND message_id IN (/*SLICE:message_ids*/?)
`

type GetTaskTranslationsBatchParams struct {
	LanguageCode string          `json:"language_code"`
	MessageIds   []sql.NullInt64 `json:"message_ids"`
}

type GetTaskTranslationsBatchRow struct {
	MessageID      sql.NullInt64 `json:"message_id"`
	TranslatedText string        `json:"translated_text"`
}

func (q *Queries) GetTaskTranslationsBatch(ctx context.Context, arg GetTaskTranslationsBatchParams) ([]GetTaskTranslationsBatchRow, error) {
	query := getTaskTranslationsBatch
	var queryParams []interface{}
	queryParams = append(queryParams, arg.LanguageCode)
	if len(arg.MessageIds) > 0 {
		for _, v := range arg.MessageIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:message_ids*/?", strings.Repeat(",?", len(arg.MessageIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:message_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTaskTranslationsBatchRow
	for rows.Next() {
		var i GetTaskTranslationsBatchRow
		if err := rows.Scan(&i.MessageID, &i.TranslatedText); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}


const upsertTaskTranslation = `-- name: UpsertTaskTranslation :exec
INSERT INTO task_translations (message_id, language_code, translated_text)
VALUES (?, ?, ?)
ON CONFLICT (message_id, language_code) 
DO UPDATE SET translated_text = EXCLUDED.translated_text
`

type UpsertTaskTranslationParams struct {
	MessageID      sql.NullInt64 `json:"message_id"`
	LanguageCode   string        `json:"language_code"`
	TranslatedText string        `json:"translated_text"`
}

func (q *Queries) UpsertTaskTranslation(ctx context.Context, arg UpsertTaskTranslationParams) error {
	_, err := q.db.ExecContext(ctx, upsertTaskTranslation, arg.MessageID, arg.LanguageCode, arg.TranslatedText)
	return err
}
