// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"database/sql"
)

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, email, name, slack_id, wa_jid, picture, created_at FROM users
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.SlackID,
			&i.WaJid,
			&i.Picture,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserAliasesByEmail = `-- name: GetUserAliasesByEmail :many
SELECT alias_name FROM user_aliases a
JOIN users u ON a.user_id = u.id
WHERE u.email = ?1
`

func (q *Queries) GetUserAliasesByEmail(ctx context.Context, email sql.NullString) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getUserAliasesByEmail, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var alias_name string
		if err := rows.Scan(&alias_name); err != nil {
			return nil, err
		}
		items = append(items, alias_name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, slack_id, wa_jid, picture, created_at FROM users WHERE email = ?1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.SlackID,
		&i.WaJid,
		&i.Picture,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmailSimple = `-- name: GetUserByEmailSimple :one
SELECT COALESCE(name, '') as name FROM users WHERE email = ?1
`

func (q *Queries) GetUserByEmailSimple(ctx context.Context, email sql.NullString) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmailSimple, email)
	var name string
	err := row.Scan(&name)
	return name, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, slack_id, wa_jid, picture, created_at FROM users WHERE id = CAST(?1 AS INTEGER)
`

func (q *Queries) GetUserByID(ctx context.Context, dollar_1 int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, dollar_1)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.SlackID,
		&i.WaJid,
		&i.Picture,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserDetails = `-- name: UpdateUserDetails :exec
UPDATE users
SET
    name = COALESCE(?2, name),
    picture = COALESCE(?3, picture),
    wa_jid = COALESCE(?4, wa_jid),
    slack_id = COALESCE(?5, slack_id)
WHERE email = ?1
`

type UpdateUserDetailsParams struct {
	Email   sql.NullString `json:"email"`
	Name    sql.NullString `json:"name"`
	Picture sql.NullString `json:"picture"`
	WaJid   sql.NullString `json:"wa_jid"`
	SlackID sql.NullString `json:"slack_id"`
}

func (q *Queries) UpdateUserDetails(ctx context.Context, arg UpdateUserDetailsParams) error {
	_, err := q.db.ExecContext(ctx, updateUserDetails,
		arg.Email,
		arg.Name,
		arg.Picture,
		arg.WaJid,
		arg.SlackID,
	)
	return err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (email, name, picture) 
VALUES (?1, ?2, ?3) 
ON CONFLICT(email) DO UPDATE SET 
    name = COALESCE(NULLIF(EXCLUDED.name, ''), users.name),
    picture = COALESCE(NULLIF(EXCLUDED.picture, ''), users.picture)
RETURNING id, email, name, slack_id, wa_jid, picture, created_at
`

type UpsertUserParams struct {
	Email   sql.NullString `json:"email"`
	Name    sql.NullString `json:"name"`
	Picture sql.NullString `json:"picture"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, upsertUser, arg.Email, arg.Name, arg.Picture)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.SlackID,
		&i.WaJid,
		&i.Picture,
		&i.CreatedAt,
	)
	return i, err
}
