// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, name, picture) 
VALUES (?1, ?2, ?3) 
ON CONFLICT(email) DO UPDATE SET 
    name = EXCLUDED.name, 
    picture = EXCLUDED.picture
RETURNING 
    id, 
    COALESCE(email, '') as email, 
    COALESCE(name, '') as name, 
    COALESCE(slack_id, '') as slack_id, 
    COALESCE(wa_jid, '') as wa_jid, 
    COALESCE(picture, '') as picture, 
    created_at
`

type CreateUserParams struct {
	Email   sql.NullString `json:"email"`
	Name    sql.NullString `json:"name"`
	Picture sql.NullString `json:"picture"`
}

type CreateUserRow struct {
	ID        int64        `json:"id"`
	Email     string       `json:"email"`
	Name      string       `json:"name"`
	SlackID   string       `json:"slack_id"`
	WaJid     string       `json:"wa_jid"`
	Picture   string       `json:"picture"`
	CreatedAt sql.NullTime `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.Name, arg.Picture)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.SlackID,
		&i.WaJid,
		&i.Picture,
		&i.CreatedAt,
	)
	return i, err
}

const createUserReturningAll = `-- name: CreateUserReturningAll :one
INSERT INTO users (email, name, picture) 
VALUES (?1, ?2, ?3) 
ON CONFLICT(email) DO UPDATE SET 
    name = COALESCE(NULLIF(EXCLUDED.name, ''), users.name),
    picture = COALESCE(NULLIF(EXCLUDED.picture, ''), users.picture)
RETURNING 
    id, 
    COALESCE(email, '') as email, 
    COALESCE(name, '') as name, 
    COALESCE(slack_id, '') as slack_id, 
    COALESCE(wa_jid, '') as wa_jid, 
    COALESCE(picture, '') as picture, 
    created_at
`

type CreateUserReturningAllParams struct {
	Email   sql.NullString `json:"email"`
	Name    sql.NullString `json:"name"`
	Picture sql.NullString `json:"picture"`
}

type CreateUserReturningAllRow struct {
	ID        int64        `json:"id"`
	Email     string       `json:"email"`
	Name      string       `json:"name"`
	SlackID   string       `json:"slack_id"`
	WaJid     string       `json:"wa_jid"`
	Picture   string       `json:"picture"`
	CreatedAt sql.NullTime `json:"created_at"`
}

func (q *Queries) CreateUserReturningAll(ctx context.Context, arg CreateUserReturningAllParams) (CreateUserReturningAllRow, error) {
	row := q.db.QueryRowContext(ctx, createUserReturningAll, arg.Email, arg.Name, arg.Picture)
	var i CreateUserReturningAllRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.SlackID,
		&i.WaJid,
		&i.Picture,
		&i.CreatedAt,
	)
	return i, err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT 
    id, 
    COALESCE(email, '') as email, 
    COALESCE(name, '') as name, 
    COALESCE(slack_id, '') as slack_id, 
    COALESCE(wa_jid, '') as wa_jid, 
    COALESCE(picture, '') as picture, 
    created_at 
FROM users
`

type GetAllUsersRow struct {
	ID        int64        `json:"id"`
	Email     string       `json:"email"`
	Name      string       `json:"name"`
	SlackID   string       `json:"slack_id"`
	WaJid     string       `json:"wa_jid"`
	Picture   string       `json:"picture"`
	CreatedAt sql.NullTime `json:"created_at"`
}

func (q *Queries) GetAllUsers(ctx context.Context) ([]GetAllUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllUsersRow
	for rows.Next() {
		var i GetAllUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.SlackID,
			&i.WaJid,
			&i.Picture,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserAliasesByEmail = `-- name: GetUserAliasesByEmail :many
SELECT alias_name FROM user_aliases a
JOIN users u ON a.user_id = u.id
WHERE u.email = ?1
`

func (q *Queries) GetUserAliasesByEmail(ctx context.Context, email sql.NullString) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getUserAliasesByEmail, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var alias_name string
		if err := rows.Scan(&alias_name); err != nil {
			return nil, err
		}
		items = append(items, alias_name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT 
    id, 
    COALESCE(email, '') as email, 
    COALESCE(name, '') as name, 
    COALESCE(slack_id, '') as slack_id, 
    COALESCE(wa_jid, '') as wa_jid, 
    COALESCE(picture, '') as picture, 
    created_at 
FROM users 
WHERE email = ?1
`

type GetUserByEmailRow struct {
	ID        int64        `json:"id"`
	Email     string       `json:"email"`
	Name      string       `json:"name"`
	SlackID   string       `json:"slack_id"`
	WaJid     string       `json:"wa_jid"`
	Picture   string       `json:"picture"`
	CreatedAt sql.NullTime `json:"created_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email sql.NullString) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.SlackID,
		&i.WaJid,
		&i.Picture,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmailSimple = `-- name: GetUserByEmailSimple :one
SELECT COALESCE(name, '') as name FROM users WHERE email = ?1
`

func (q *Queries) GetUserByEmailSimple(ctx context.Context, email sql.NullString) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmailSimple, email)
	var name string
	err := row.Scan(&name)
	return name, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT 
    id, 
    COALESCE(email, '') as email, 
    COALESCE(name, '') as name, 
    COALESCE(slack_id, '') as slack_id, 
    COALESCE(wa_jid, '') as wa_jid, 
    COALESCE(picture, '') as picture, 
    created_at 
FROM users 
WHERE id = CAST(?1 AS INTEGER)
`

type GetUserByIDRow struct {
	ID        int64        `json:"id"`
	Email     string       `json:"email"`
	Name      string       `json:"name"`
	SlackID   string       `json:"slack_id"`
	WaJid     string       `json:"wa_jid"`
	Picture   string       `json:"picture"`
	CreatedAt sql.NullTime `json:"created_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, dollar_1 int64) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, dollar_1)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.SlackID,
		&i.WaJid,
		&i.Picture,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserNamePicture = `-- name: UpdateUserNamePicture :exec
UPDATE users SET name = ?1, picture = ?2 WHERE email = ?3
`

type UpdateUserNamePictureParams struct {
	Name    sql.NullString `json:"name"`
	Picture sql.NullString `json:"picture"`
	Email   sql.NullString `json:"email"`
}

func (q *Queries) UpdateUserNamePicture(ctx context.Context, arg UpdateUserNamePictureParams) error {
	_, err := q.db.ExecContext(ctx, updateUserNamePicture, arg.Name, arg.Picture, arg.Email)
	return err
}

const updateUserSlackID = `-- name: UpdateUserSlackID :exec
UPDATE users SET slack_id = ?1 WHERE email = ?2
`

type UpdateUserSlackIDParams struct {
	SlackID sql.NullString `json:"slack_id"`
	Email   sql.NullString `json:"email"`
}

func (q *Queries) UpdateUserSlackID(ctx context.Context, arg UpdateUserSlackIDParams) error {
	_, err := q.db.ExecContext(ctx, updateUserSlackID, arg.SlackID, arg.Email)
	return err
}

const updateUserWAJID = `-- name: UpdateUserWAJID :exec
UPDATE users SET wa_jid = ?1 WHERE email = ?2
`

type UpdateUserWAJIDParams struct {
	WaJid sql.NullString `json:"wa_jid"`
	Email sql.NullString `json:"email"`
}

func (q *Queries) UpdateUserWAJID(ctx context.Context, arg UpdateUserWAJIDParams) error {
	_, err := q.db.ExecContext(ctx, updateUserWAJID, arg.WaJid, arg.Email)
	return err
}
