// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wa_messages.sql

package db

import (
	"context"
)

const insertWAMessage = `-- name: InsertWAMessage :exec
INSERT OR IGNORE INTO wa_messages (
    message_id, email, chat_jid, chat_name, sender,
    direction, body, reply_to, has_attachment, is_forwarded,
    mentions, ts
) VALUES (
    ?1, ?2, ?3, ?4, ?5,
    ?6, ?7, ?8, ?9, ?10,
    ?11, ?12
)
`

type InsertWAMessageParams struct {
	MessageID     string `json:"message_id"`
	Email         string `json:"email"`
	ChatJid       string `json:"chat_jid"`
	ChatName      string `json:"chat_name"`
	Sender        string `json:"sender"`
	Direction     string `json:"direction"`
	Body          string `json:"body"`
	ReplyTo       string `json:"reply_to"`
	HasAttachment int64  `json:"has_attachment"`
	IsForwarded   int64  `json:"is_forwarded"`
	Mentions      string `json:"mentions"`
	Ts            int64  `json:"ts"`
}

func (q *Queries) InsertWAMessage(ctx context.Context, arg InsertWAMessageParams) error {
	_, err := q.db.ExecContext(ctx, insertWAMessage,
		arg.MessageID,
		arg.Email,
		arg.ChatJid,
		arg.ChatName,
		arg.Sender,
		arg.Direction,
		arg.Body,
		arg.ReplyTo,
		arg.HasAttachment,
		arg.IsForwarded,
		arg.Mentions,
		arg.Ts,
	)
	return err
}

const listWAMessages = `-- name: ListWAMessages :many
SELECT id, message_id, email, chat_jid, chat_name, sender,
       direction, body, reply_to, has_attachment, is_forwarded,
       mentions, ts, created_at
FROM wa_messages
WHERE (?1 = '' OR email = ?1)
  AND (?2 = '' OR chat_jid = ?2)
  AND (?3 = '' OR direction = ?3)
  AND (?4 = 0  OR ts >= ?4)
  AND (?5 = 0  OR ts <= ?5)
ORDER BY ts DESC
LIMIT ?6 OFFSET ?7
`

type ListWAMessagesParams struct {
	Column1 interface{} `json:"column_1"`
	Column2 interface{} `json:"column_2"`
	Column3 interface{} `json:"column_3"`
	Column4 interface{} `json:"column_4"`
	Column5 interface{} `json:"column_5"`
	Limit   int64       `json:"limit"`
	Offset  int64       `json:"offset"`
}

func (q *Queries) ListWAMessages(ctx context.Context, arg ListWAMessagesParams) ([]WaMessage, error) {
	rows, err := q.db.QueryContext(ctx, listWAMessages,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WaMessage
	for rows.Next() {
		var i WaMessage
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.Email,
			&i.ChatJid,
			&i.ChatName,
			&i.Sender,
			&i.Direction,
			&i.Body,
			&i.ReplyTo,
			&i.HasAttachment,
			&i.IsForwarded,
			&i.Mentions,
			&i.Ts,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
