// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wa_messages.sql

package db

import (
	"context"
	"database/sql"
)

const insertWAMessage = `-- name: InsertWAMessage :exec
INSERT OR IGNORE INTO wa_messages (
    message_id, email, chat_jid, chat_name, sender,
    direction, body, reply_to, has_attachment, is_forwarded,
    mentions, ts, raw_json
) VALUES (
    ?1, ?2, ?3, ?4, ?5,
    ?6, ?7, ?8, ?9, ?10,
    ?11, ?12, ?13
)
`

type InsertWAMessageParams struct {
	MessageID     string `json:"message_id"`
	Email         string `json:"email"`
	ChatJid       string `json:"chat_jid"`
	ChatName      string `json:"chat_name"`
	Sender        string `json:"sender"`
	Direction     string `json:"direction"`
	Body          string `json:"body"`
	ReplyTo       string `json:"reply_to"`
	HasAttachment int64  `json:"has_attachment"`
	IsForwarded   int64  `json:"is_forwarded"`
	Mentions      string `json:"mentions"`
	Ts            int64  `json:"ts"`
	RawJson       string `json:"raw_json"`
}

func (q *Queries) InsertWAMessage(ctx context.Context, arg InsertWAMessageParams) error {
	_, err := q.db.ExecContext(ctx, insertWAMessage,
		arg.MessageID,
		arg.Email,
		arg.ChatJid,
		arg.ChatName,
		arg.Sender,
		arg.Direction,
		arg.Body,
		arg.ReplyTo,
		arg.HasAttachment,
		arg.IsForwarded,
		arg.Mentions,
		arg.Ts,
		arg.RawJson,
	)
	return err
}

const listReplayableWAMessages = `-- name: ListReplayableWAMessages :many
SELECT message_id, chat_jid, raw_json, scan_attempts
FROM wa_messages
WHERE email = ?1
  AND processed_at IS NULL
  AND raw_json != ''
  AND scan_attempts < ?2
  AND created_at <= ?3
  AND (popped_at IS NULL OR popped_at <= ?4)
  AND ts >= ?5
ORDER BY ts
LIMIT ?6
`

type ListReplayableWAMessagesParams struct {
	Email        string       `json:"email"`
	ScanAttempts int64        `json:"scan_attempts"`
	CreatedAt    string       `json:"created_at"`
	PoppedAt     sql.NullTime `json:"popped_at"`
	Ts           int64        `json:"ts"`
	Limit        int64        `json:"limit"`
}

type ListReplayableWAMessagesRow struct {
	MessageID    string `json:"message_id"`
	ChatJid      string `json:"chat_jid"`
	RawJson      string `json:"raw_json"`
	ScanAttempts int64  `json:"scan_attempts"`
}

// Why: replay reads only messages not yet consumed (processed_at IS NULL), with a
// captured payload (raw_json != ”), under the retry cap, past the write-settle grace
// period, not currently held by another in-flight pop (or that hold gone stale), and
// within the lookback window -- so a crashed scan does not resurrect ancient history.
func (q *Queries) ListReplayableWAMessages(ctx context.Context, arg ListReplayableWAMessagesParams) ([]ListReplayableWAMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, listReplayableWAMessages,
		arg.Email,
		arg.ScanAttempts,
		arg.CreatedAt,
		arg.PoppedAt,
		arg.Ts,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReplayableWAMessagesRow
	for rows.Next() {
		var i ListReplayableWAMessagesRow
		if err := rows.Scan(
			&i.MessageID,
			&i.ChatJid,
			&i.RawJson,
			&i.ScanAttempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWAMessages = `-- name: ListWAMessages :many
SELECT id, message_id, email, chat_jid, chat_name, sender,
       direction, body, reply_to, has_attachment, is_forwarded,
       mentions, ts, created_at
FROM wa_messages
WHERE (?1 = '' OR email = ?1)
  AND (?2 = '' OR chat_jid = ?2)
  AND (?3 = '' OR direction = ?3)
  AND (?4 = 0  OR ts >= ?4)
  AND (?5 = 0  OR ts <= ?5)
ORDER BY ts DESC
LIMIT ?6 OFFSET ?7
`

type ListWAMessagesParams struct {
	Column1 interface{} `json:"column_1"`
	Column2 interface{} `json:"column_2"`
	Column3 interface{} `json:"column_3"`
	Column4 interface{} `json:"column_4"`
	Column5 interface{} `json:"column_5"`
	Limit   int64       `json:"limit"`
	Offset  int64       `json:"offset"`
}

type ListWAMessagesRow struct {
	ID            int64  `json:"id"`
	MessageID     string `json:"message_id"`
	Email         string `json:"email"`
	ChatJid       string `json:"chat_jid"`
	ChatName      string `json:"chat_name"`
	Sender        string `json:"sender"`
	Direction     string `json:"direction"`
	Body          string `json:"body"`
	ReplyTo       string `json:"reply_to"`
	HasAttachment int64  `json:"has_attachment"`
	IsForwarded   int64  `json:"is_forwarded"`
	Mentions      string `json:"mentions"`
	Ts            int64  `json:"ts"`
	CreatedAt     string `json:"created_at"`
}

func (q *Queries) ListWAMessages(ctx context.Context, arg ListWAMessagesParams) ([]ListWAMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, listWAMessages,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWAMessagesRow
	for rows.Next() {
		var i ListWAMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.Email,
			&i.ChatJid,
			&i.ChatName,
			&i.Sender,
			&i.Direction,
			&i.Body,
			&i.ReplyTo,
			&i.HasAttachment,
			&i.IsForwarded,
			&i.Mentions,
			&i.Ts,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWAMessagesForChatSince = `-- name: ListWAMessagesForChatSince :many
SELECT message_id, sender, body, has_attachment, ts, raw_json
FROM wa_messages
WHERE email = ?1
  AND chat_name = ?2
  AND ts > ?3
ORDER BY ts
`

type ListWAMessagesForChatSinceParams struct {
	Email    string `json:"email"`
	ChatName string `json:"chat_name"`
	Ts       int64  `json:"ts"`
}

type ListWAMessagesForChatSinceRow struct {
	MessageID     string `json:"message_id"`
	Sender        string `json:"sender"`
	Body          string `json:"body"`
	HasAttachment int64  `json:"has_attachment"`
	Ts            int64  `json:"ts"`
	RawJson       string `json:"raw_json"`
}

// Why: reassess-wa-backlog needs raw_json (for ReplyToID matching) and a chat_name
// filter that ListWAMessages does not expose (it filters chat_jid only).
func (q *Queries) ListWAMessagesForChatSince(ctx context.Context, arg ListWAMessagesForChatSinceParams) ([]ListWAMessagesForChatSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, listWAMessagesForChatSince, arg.Email, arg.ChatName, arg.Ts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWAMessagesForChatSinceRow
	for rows.Next() {
		var i ListWAMessagesForChatSinceRow
		if err := rows.Scan(
			&i.MessageID,
			&i.Sender,
			&i.Body,
			&i.HasAttachment,
			&i.Ts,
			&i.RawJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
