// Code generated by whatap-go-inst init; DO NOT EDIT.
// This file declares whatap instrumentation dependencies for go mod tidy.
// Imports are based on detected frameworks in your project.

package main

import (
	// Standard library (used by injected code)
	_ "context"
	_ "os"

	// Core whatap packages
	_ "github.com/whatap/go-api/httpc"
	_ "github.com/whatap/go-api/logsink"
	_ "github.com/whatap/go-api/trace"
	_ "github.com/whatap/go-api/instrumentation/net/http/whataphttp"
	_ "github.com/whatap/go-api/instrumentation/github.com/gorilla/mux/whatapmux"
	_ "github.com/whatap/go-api/instrumentation/database/sql/whatapsql"
)
